### ISSUE TITLE
Add to Favourite option

### ISSUE THREAD

**Issue by ghost** [jonjomckay/fritter#1]
Add to favourite option like Barinsta has or Follow/Subscribe option like NewPipe has.

**Comment by jonjomckay** [comment]
This idea is already on my list! I also like how NewPipe has a local subscription feature. I also plan to implement support for Lists, which might be a good middle ground at first.

**Comment by ScriptForAll** [comment]
Do you also plan to implement categories for the subscriptions similar to NewPipe?
If that were to be implemented into the app, I think it would be awesome.

**Comment by peterflock** [comment]
**Firstly: Thank you! This app has so much potential!** 🎉

If this app can be what NewPipe is for Youtube it would be totally killer and solution to one of my "big problems".

I like to suggest to add:
1. Add "Follow" the account
2. List those follows (subscriptions)
3. Ability to create "lists" to group those followed accounts
4. Ability to read "timeline" for those lists (similar to NewPipes "What's New")
4. Ability to import/export those lists and followers (subscriptions)

As a bonus I offer bounty $45 paid in BTC over Lightning. 💸

**Comment by q1nt** [comment]
Repeating others that local subscriptions are all this app needs. IMO Fritter has the potential to become a FOSS classic like NewPipe--great job, dev!

**Comment by jonjomckay** [comment]
Thanks all! I've been working on a first draft of this over the last few days - I should have something within the next week or so that allows you to follow accounts and view a basic timeline.

It's modelled on the way Newpipe does its similar thing, as I agree it's the gold standard in local subscriptions. 

@peterflock thank you for the generous bounty offer! Let me know what you need from me - my email is on my profile.

**Comment by q1nt** [comment]
Hi JonJo I'm q1nt who commented on your Github for Fritter. I'd like to make a donation for Fritter. If you accept them what's the best way to get it to you? 

On April 2, 2021 8:43:17 PM GMT+08:00, Jonjo McKay ***@***.***> wrote:
>Thanks all! I've been working on a first draft of this over the last
>few days - I should have something within the next week or so that
>allows you to follow accounts and view a basic timeline.
>
>It's modelled on the way Newpipe does its similar thing, as I agree
>it's the gold standard in local subscriptions. 
>
***@***.*** thank you for the generous bounty offer! Let me know what
>you need from me - my email is on my profile. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jonjomckay/fritter/issues/1#issuecomment-812513656

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jonjomckay** [comment]
@q1nt thank you! I accept sponsorship [via GitHub](https://github.com/sponsors/jonjomckay) (feel free to sponsor and cancel if you don't want a recurring monthly!). I can also accept PayPal via the email address in my profile, and BTC at the address `1DaXsBJVi41fgKkKcw2Ln8noygTbdD7Srg`.

**Comment by jonjomckay** [comment]
I've pushed #10, which adds support for very basic local subscriptions. I'd be grateful for any feedback! You can download an APK from the latest build, which should be available as an artifact [here](https://github.com/jonjomckay/fritter/actions).

**Comment by q1nt** [comment]
Progressing nicely. I installed release #15 and was able to subscribe. The only glitch I found was that the subscription didn't show up in Following tab/list immediately after adding it. First I needed to switch to the Trending tab, then back on the Following tab, and then I could see the subscription I added.

**Comment by lukas-conlance** [comment]
@jonjomckay I installed the apk, looks very nice 👍Would be awesome if there was a "stream" containg all posts from the subscriptions.

**Comment by peterflock** [comment]
I have installed and tested the APK:
- The search is not working properly. I am trying to search for full name "Peter Flock" in a query and it shows me some tweets instead of list of Twitter users
- I have the very same issue as @q1nt  that after following (some random person) I have to restart app to see it.
- The feed for new tweets from my subscriptions is the most missing feature.

**Comment by q1nt** [comment]
After accidentally swiping down on the following list/tab I noticed the subscription list refreshed itself. Maybe add a button or text to alert the user to do that?

**Comment by candiesdoodle** [comment]
Hi
This is my new favourite Open source software. Will be following keenly. Just one request at the moment. Please bring back feed view  of the subscriptions :)

**Comment by jonjomckay** [comment]
I've merged in a (hopefully) fully working model for local subscriptions, including subscription groups and a feed view for each group (or all subscriptions). I'll give it a few days to see if there are any blocking bugs, and then release it on F-Droid.

In the meantime, you can download [the latest development build here](https://github.com/jonjomckay/fritter/actions) if you'd like to "beta test"!

**Comment by WindHun7er** [comment]
Thanks for adding this master feature in the last release! From my side, everything works perfectly! 

To echo @peterflock :
> 5. Ability to import/export those lists and followers (subscriptions)

I think the next essential step to improve this feature would be to add a way to export and import this list. When you have several hundreds of followed accounts it can quickly become a serious problem if you have to uninstall and reinstall the app for some reason or simply if you have to change your smartphone... 

This app is exactly what I needed to finally replace my twitter app and fully enjoy nitter !

(By the way, why did you remove the possibility to choose the nitter instance in the new releases ?)

**Comment by peterflock** [comment]
Great job! :tada: 

Here is my test:
- It took me while to figure out that I can manage subscription in a group by long-press.
- I miss possibility to add someone to group from profile detail (now I have to first subscribe him and then add him to group)
- I am unable to copy text from tweets.

**Comment by peterflock** [comment]
- Also some color/icons picker for groups can be handy. When I have many groups (10+) is became hard to orient.

**Comment by peterflock** [comment]
- When I open someones profile, there is no info about it (description, etc..)
- Replies are mixed with normal tweets and it is not possible to see on what has been replied to.

------

It is a great progress :heart_eyes: Good job! The app is now usable and it already brings value!

**Comment by peterflock** [comment]
Bounty was paid out. Thank you for your great work.

**Comment by jonjomckay** [comment]
Closing this now, as it's been fully implemented. All other requests and bugs are being tracked as separate tickets.

Thanks to all for the feedback, and to those who placed a bounty on this feature!
