### ISSUE TITLE
Fritter 2.6.0 

### ISSUE THREAD

**Issue by FOSS-Love** [jonjomckay/fritter#104]
#### Groups sorting 
I presume that no one uses auto sort options of groups as there will be less than 10 groups a user might create so manual sorting will be useful.
#### Header 
Irrespective of the page we are in, it is showing trending as the header when default tab is set to sub and showing subscriptions as the header when default tab is set to trending . 
![Screenshot_2021-05-20-15-26-20-71](https://user-images.githubusercontent.com/83025165/118959228-bf57d680-b927-11eb-9eb3-be93005ac7e9.jpg)

#### Sliding through trending, subs and saved
There is a bit lag ( i mean that animation isnt smooth ) when sliding is made to trending when compared to the sliding made between subs and saved.
#### Tweet footer
 A option to choose what to show. retweet counts, likes, seems useless for some users and this way we could even avoid getting slider (which is a bit annoying to have) on small screens.
#### The retweet mark
Instead of indenting soo much for a retweeted tweet just small indent without retweet icon would be minimal and looks good.
![Screenshot_2021-05-20-15-23-40-82_1](https://user-images.githubusercontent.com/83025165/118959060-96374600-b927-11eb-84c3-3415bcf73cd4.jpg)

#### Verified tick
Verified tick in search results will be helpful as checking every account is bit of a work to do.
#### Comments
At present the comments card is aligned center to the screen with huge padding around, but the comments look soo compact in this look, removing padding around might help.
#### Lengthy profilenames
Tweet header of lengthy profilenames are creating a distortion with the time posted. May be the time needs to be lowered,  in alignment with the username, instead of being center aligned with username and profilename.
![Screenshot_2021-05-20-15-22-11-07](https://user-images.githubusercontent.com/83025165/118958560-288b1a00-b927-11eb-8ba2-a105035d3c13.jpg)

#### retweets footers
When there is a retweet with a comment the two footers gets stacked one upon other which  looks unpleasant, so removing the footer for the tweet that got retweeted, we will be left with only one footer visible which will look fine.
![Screenshot_2021-05-20-15-20-40-76](https://user-images.githubusercontent.com/83025165/118958358-f7aae500-b926-11eb-9b62-9a0115d88d86.jpg)

**Comment by jonjomckay** [comment]
Thank you for the comprehensive list of suggestions! I've split them out into #45, #117, #118, #119, #120, #121, #122 and #123, so they can be more easily worked on and tracked.

I'll close this issue now, but please subscribe to any/all of those others to follow their progress 🙂
