### ISSUE TITLE
Please allow any user to login to Twitter via Fritter.

### ISSUE THREAD

**Issue by 42837531** [jonjomckay/fritter#105]

**Comment by eredrolo** [comment]
No, let this remain as a viewer. You can try [Twidere](https://github.com/TwidereProject/Twidere-Android) if you want a client.

**Comment by 42837531** [comment]
Twidere is wonderful. Thanks.

**Comment by 42837531** [comment]
> No, let this remain as a viewer. You can try [Twidere](https://github.com/TwidereProject/Twidere-Android) if you want a client.

Twidere is wonderful. Thanks.

**Comment by alphanerdgen** [comment]
NOOOOOOOOOOOOOO!!! 😨

**Comment by jonjomckay** [comment]
Sorry, this doesn't match up with what Fritter is aiming for! Please see [here](https://github.com/jonjomckay/fritter/discussions/75#discussioncomment-725584) for an answer I gave on where I see Fritter fitting in. There's also some more information on [fritter.cc](https://fritter.cc) regarding privacy Fritter's other ideals.

As mentioned by @eredrolo, Twidere is a decent alternative if you want to use an account.
