### ISSUE TITLE
Database exception in subscriptions and saved tweets screen.

### ISSUE THREAD

**Issue by Trailblazerr1** [jonjomckay/fritter#107]
Thanks for this wonderful app.
Today I installed v2.6.1 from github releases and found database error on groups, subscriptions and settings screen as shown below:
<p float="left">
<img src="https://user-images.githubusercontent.com/16671238/119177596-29888c80-ba8a-11eb-8cf1-957bee98c044.jpg" alt="drawing" width="250"/>

<img src="https://user-images.githubusercontent.com/16671238/119177824-7e2c0780-ba8a-11eb-9848-3fa9bf7fcbf3.jpg" alt="drawing" width="250"/>
</p>

**Resolution steps taken:** 
1. I tried uninstalling and installing app again and it didn't help. Also used on another device and have same issue. 
2. Installed v2.5.0 and v2.6.0, both are working fine. The issue only occurs in v2.6.1 .

**Comment by jonjomckay** [comment]
It looks like the database migrations didn't run - can you try with the latest build from the `master` branch? I've hopefully fixed it there. You can download it [here](https://github.com/jonjomckay/fritter/actions/runs/866942151)

**Comment by Trailblazerr1** [comment]
I installed the above app, on opening it just shows a blank white screen forever (No text or anything, just white screen) .  Restarting or reinstalling didn't help.

**Comment by Trailblazerr1** [comment]
I rechecked with v2.6.2, the issue isn't occurring anymore. Thanks a lot for the resolution.
