### ISSUE TITLE
doesn't show all comments

### ISSUE THREAD

**Issue by givena** [jonjomckay/fritter#108]
when you go to read the comments of a tweet with a lot of replies not all of them show

**Comment by jonjomckay** [comment]
@givena can you give an example of a tweet where this is happening? I'll check it out

**Comment by eredrolo** [comment]
@jonjomckay Any tweet with 10 or more replies has this issue. Only 6-9 replies are shown for every tweet. Maximum replies is always 9.

It would be nice to have a **Load more replies** button like Nitter or to automatically load more replies when we reach end of the page.
