### ISSUE TITLE
Bookmarking/Unbookmarking Tweets Triggers a Refresh

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#109]
In v 2.6.1, the screen loads again after I bookmark or unbookmark a tweet. The desired action does happen eventually but this forced refresh is a bit annoying. This wasn't the case before.

**Update**:  Now using 2.6.2. This issue comes up only in Groups.

**Comment by LuckyDingo** [comment]
I have this problem as well, but it only happens when viewing subscriptions (all or group.)
