### ISSUE TITLE
App not loading/displaying anything

### ISSUE THREAD

**Issue by matterharz** [jonjomckay/fritter#112]
I'm on v2.6 and this has been going on since at least v2.3 (the first version I actually installed): no trends, no search (and, of course, no timeline.)

Curiously, it worked exactly once, just after installing it for the first time. Reinstalled it several times to no avail.

Tested on Oneplus 2 running LineageOS for microG 17.1 and Oneplus 3 running LineageOS 18.1.

See attached screenshots. (The 2nd one was made after tapping the cogwheel.)
![Screenshot_20210524-091547_Fritter](https://user-images.githubusercontent.com/76849821/119310952-c3aa2980-bc70-11eb-8089-d8c2a6a5ac98.png)
![Screenshot_20210524-091600_Fritter](https://user-images.githubusercontent.com/76849821/119310991-cf95eb80-bc70-11eb-915d-5a4904d229b5.png)
![Screenshot_20210524-091626_Fritter](https://user-images.githubusercontent.com/76849821/119311022-d91f5380-bc70-11eb-81a9-73b659604f0a.png)
![Screenshot_20210524-091633_Fritter](https://user-images.githubusercontent.com/76849821/119311051-e1778e80-bc70-11eb-8ae5-a7aa455365ca.png)

**Comment by jonjomckay** [comment]
This looks like something is blocking connections to Twitter (`Connection refused`) . Are you running a firewall or VPN, either on your device or network? Or are you located in a country that blocks access to Twitter? I know users in Iran can't use it, for example.

**Comment by matterharz** [comment]
You're absolutely right, I had totally forgotten about the low-level adblocker (Energized Protection Magisk module) I installed weeks ago. Whitelisted twitter.com and it's working fine now. Sorry about the noise!
