### ISSUE TITLE
Can't subscribe to any feeds

### ISSUE THREAD

**Issue by NRG-600** [jonjomckay/fritter#115]
Facing infinite loop of loading and unable to subscribe to any feeds !

[Screenshot_20210526_144451_com.jonjomckay.fritter.jpg](https://user-images.githubusercontent.com/37657519/119635608-7b863500-be31-11eb-9ba1-e4bc24bb0afc.jpg)

![Screenshot_20210526_145035_com.jonjomckay.fritter.jpg](https://user-images.githubusercontent.com/37657519/119635918-c3a55780-be31-11eb-84c7-c094d4f73523.jpg)

**Comment by jonjomckay** [comment]
@NRG-600 can you try again with the latest version (v2.6.2)? This looks like it's being caused by an issue with the database migrations from v2.6.1, which should now be fixed.

**Comment by pokegamer5547** [comment]
New user here and i'm having same issue, using v2.6.1 from fddroid.

**Comment by jonjomckay** [comment]
Closing as no response from OP, and appears to be fixed by v2.6.2.

@NRG-600 please re-open if you're still encountering the same issue.
