### ISSUE TITLE
[Feature Request] Improvements to the video player UI

### ISSUE THREAD

**Issue by eredrolo** [jonjomckay/fritter#127]
When playing a video in portrait mode, the video progress bar is very small which makes it hard to seek the video. I would like if the progress bar is longer and it's easier to seek the video.

![Screenshot_20210528-210631](https://user-images.githubusercontent.com/74611933/120009284-6c51e380-bff9-11eb-8b1d-14abdedeb2fa.jpg)

# Suggested changes-
- The pause/play button can be moved to the center of the video. 
- The buttons for speed and download can be moved to a menu to make space for the progress bar **OR**
- The progress bar can be moved to above or below the buttons.

**Comment by FOSS-Love** [comment]
Yes the ui doesn't feel right. And the scroll isnt smooth when there are consecutive tweets with videos. I assume that is bcz of the player controls. Removing player controls, in normal view and give them only inside the full screen mode, that might work.

**Comment by jonjomckay** [comment]
Thanks for the request! I've updated the player controls, and they'll be in v2.9.0.

>This upgrades `chewie` to the latest version, and imports the new
`MaterialDesktopControls`, which are a bit more user friendly, and
small screen friendly.
>
> The progress bar is now displayed above the controls, allowing it to be
seen on narrower device screens in portrait mode, and it also moves the
player actions to a menu.
