### ISSUE TITLE
Group feed keeps loading if both tweed filters are selected

### ISSUE THREAD

**Issue by RequestPrivacy** [jonjomckay/fritter#134]
On 2.6.2 I still have the problem of the indefinitely loading group feed. It keeps loading if both of the filters are checked (see picture). Unchecking either one helps and the group feed finally loads. Possibly this still has something to do with #95 ?

![Loading_groupfeed](https://user-images.githubusercontent.com/72392544/120113186-e05ec980-c168-11eb-9122-4bc33ea4cc86.png)

**Comment by login22rvp** [comment]
I think it got resolved now. Try the latest version. 2.7

**Comment by RequestPrivacy** [comment]
Yeah got new F-Droid 2.7.1 version and it works like a charm. Thanks for the fix & hard work.
