### ISSUE TITLE
Fix poll options displaying incorrectly in light theme

### ISSUE THREAD

**Issue by mrn** [jonjomckay/fritter#135]
![Screenshot_20210531-224703__01.jpg](https://user-images.githubusercontent.com/10130438/120241899-ff8e5180-c263-11eb-9539-9e664d78416c.jpg)

Poll options have a white text, so when the bar is too short the text is invisible on a white background. Originally on Twitter the bars are light grey with black text.

**Comment by jonjomckay** [comment]
Thanks for the bug report! The fix will be in v2.9.0.

> This changes the colour scheme used to more closely match how Twitter
iself renders the poll options, allowing the options to be more
visible in both light and dark mode.
