### ISSUE TITLE
Wont download 

### ISSUE THREAD

**Issue by StratigusTheGreat** [jonjomckay/fritter#136]
Won't download and then says to create a bug report. Trying to download on my phone from f-droid.

**Comment by jonjomckay** [comment]
Sorry about that - could you give some more information about what's not downloading? If you've submitted a bug report, please could you send a reply to the email saying this is your issue, so I can link them up? If not, maybe a screenshot would give some context.

**Comment by jonjomckay** [comment]
Closing as no response.
