### ISSUE TITLE
[Bug] Getting a "Send crash report" popup when opening anything

### ISSUE THREAD

**Issue by eredrolo** [jonjomckay/fritter#139]
Everytime I open any group, profile, settings or search, I get the send crash report popup but the app hasn't crashed and is working fine in the background. I can select the **Don't send report** option and it works fine.

It started after updating to version 2.7.1 from F-Droid.

**Comment by jonjomckay** [comment]
This should be addressed by 4599853db74cc9c37b3338cff9c40448a2f39868. @eredrolo if you didn't already, would you mind emailing through the crash report? It'd be helpful if you could mention that it's your bug report for this issue too, but no worries if you prefer to remain anonymous over email!

**Comment by eredrolo** [comment]
Thank you for the fix.

I'm using the Tutanota client but when I press the Send report, it is only opening a blank email compose page in the Tutanota app without any log or send to email.

**Comment by eredrolo** [comment]
It works with the FairEmail client. I have sent the report.
