### ISSUE TITLE
Where to put account credentials?

### ISSUE THREAD

**Issue by EliasA** [jonjomckay/fritter#142]
I feel a bit stupid asking this but after browsing the settings of this fine piece of free software I still have a question: where do I enter my Twitter account details in order to login and send tweets?

If some kind of documentation exists I could not find it.

**Comment by givena** [comment]
hello there, there isn't an option to login into your account currently. You can suggest this, but I doubt it's going to be added.

**Comment by EliasA** [comment]
If Fritter is meant to be used without logging in, IMHO it should not be called a Twitter client. Sending messages is an integral part of a social media service. Software that lacks this functionality is not a client to that social media service. Calling Fritter a Twitter messages browser would be more accurate.

**Comment by jonjomckay** [comment]
Sorry, Fritter isn't designed to be a full-fat social media app - it's designed to interact with Twitter (follow users, have a feed, save tweets and media, etc.), but without needing to divulge any personal information, or require an account to use, keeping your data as private as possible.

This should be sufficiently documented on [fritter.cc](https://fritter.cc), but please let me know if you feel there's any information missing!

For a client that does support both reading and writing tweet data, Twidere X is pretty decent as an alternative 🙂

**Comment by EliasA** [comment]
Thank you!

Fritter is described as a free, open-source Twitter client 

here https://f-droid.org/en/packages/com.jonjomckay.fritter/
and here: https://github.com/jonjomckay/fritter/blob/master/README.md

There is no link to fritter.cc on these pages. All I am saying that a user who downloads Fritter from F-droid is likely to make a faulty assumption on what Fritter is based on the description and the documentation available at that time.
