### ISSUE TITLE
Add the ability to import followers from Twitter

### ISSUE THREAD

**Issue by jonjomckay** [jonjomckay/fritter#143]
If someone wants to import the users they are following from an existing Twitter account, we should support that.

One caveat is that this would only work with a public account, but perhaps we could also support a bookmarklet or similar that can export a logged-in user's followed list to the JSON format we expect?

NewPipe has this functionality, using YouTube Takeout as the source.

~It should also allow the user to choose a group to import the users into, e.g. if the user wants to import from multiple accounts and keep some separation.~ Group support will come in the future.

* Add a link to the import screen when no subscriptions exist

**Comment by jonjomckay** [comment]
I've just pushed super basic support for importing all followed users from a public Twitter account. Right now, you're not able to pick and choose who to import, or which groups, but I'm planning on adding that soon - I just want to get a beta/MVP of this out as I know a lot of you are waiting for it!

You can get to the screen by tapping the new "Import" button on the subscriptions screen: 

<img src="https://user-images.githubusercontent.com/456645/123511461-62afb000-d679-11eb-9691-23dfdec45ae6.jpg" width="350" />

Please, let me know of any feedback, good or bad 🙂

**Comment by jdaviescoates** [comment]
I'm on v2.13.0+20210716 but I'm not seeing that. When I click import it just opens recent files.

**Comment by jdaviescoates** [comment]
Ah, my mistake, I was looking in Settings -> Import. But then I re-read and saw you wrote 

> You can get to the screen by tapping the new "Import" button *on the subscriptions screen:*

I wasn't clear to me what the Import button on the subscriptions screen was, but after clicking on everything I learned it's the one with arrows going up and down

![Screenshot_20210905-115102_Fritter](https://user-images.githubusercontent.com/2113743/132124158-28520c63-4948-446a-ac06-cd5991085c79.png)

Just successfully imported the 5569 of the 5570 people I follow on Twitter (I wonder which one got left out, and why...)

**Comment by jdaviescoates** [comment]
Well, I say successful, but actually it won't load my feed. I guess due to Twitter limits or something? (I sent a report via Sentry)

![Screenshot_20210905-125922_Fritter](https://user-images.githubusercontent.com/2113743/132126011-aee2d99e-658b-41c7-bbbe-e35ca79823aa.png)

**Comment by jonjomckay** [comment]
@jdaviescoates yes, Fritter probably won't be able to cope very well with so many subscriptions - it might even result in you being rate limited or blocked by Twitter, as so many requests will need to be made. You might achieve better results by using the Groups functionality, splitting your subscriptions into more manageable (for Fritter) chunks.

**Comment by jonjomckay** [comment]
This is now being shipped as GA in the upcoming v2.15.0!

**Comment by jdaviescoates** [comment]
> This is now being shipped as GA in the upcoming v2.15.0!

Please excuse my ignorance but what is GA?

**Comment by jonjomckay** [comment]
@jdaviescoates general availability - no longer in beta 🙂

**Comment by RayLennox** [comment]
How about import subscriptions from fritter as a temporary workaround, while we're rate limited? Thanks for your work on this project.

**Comment by zengodgr** [comment]
> Well, I say successful, but actually it won't load my feed. I guess due to Twitter limits or something? (I sent a report via Sentry)
> 
> ![Screenshot_20210905-125922_Fritter](https://user-images.githubusercontent.com/2113743/132126011-aee2d99e-658b-41c7-bbbe-e35ca79823aa.png)

maybe have a way of login in? 
lets say on a special browser/extention where it will work as a middle man and all requests go through the normal x website and scraped page by page?

of course using thia way you would need to rate limit yourself cause a automatic system of gettong those tweets and user info will be much faster than a human browsing x in his phone or browser

**Comment by justingoldberg** [comment]
If it's rate limited, maybe allow it to run it the background and/or ask the user after a 24 hour period to continue pulling the rest of the following list.

**Comment by Adeyoelabbb** [comment]
![Screenshot_20240116-174050_Squawker.jpg](https://github.com/jonjomckay/fritter/assets/146090851/22191695-e736-427f-92b7-6af657693a5d)

What's wrong with squawker it displays the above screenshot?

**Comment by happysramdom-debug** [comment]
I don't know why see this problem typing my account correctly

![Image](https://github.com/user-attachments/assets/b5c862a4-dddf-4242-a32b-1d0e3002626f)
