### ISSUE TITLE
Videos are not showing to be downloaded in the recent update 2.9.0.

### ISSUE THREAD

**Issue by eraofphysics** [jonjomckay/fritter#146]
The download button in videos is not showing.

**Comment by jonjomckay** [comment]
v2.9.0 updated the video player UI to fit better on narrower screens (#127), so the download button is now under the menu. Please can you confirm if it appears there on your device?

**Comment by eraofphysics** [comment]
Yeah, the download button is under the menu, but the downloading video
format/extension is .m3u8, can't be played on Mobile vlc.

**Comment by eraofphysics** [comment]
This problem is for some videos not all.
