### ISSUE TITLE
Replying the video Freezes the app

### ISSUE THREAD

**Issue by login22rvp** [jonjomckay/fritter#152]
I am on latest version. Whenever i reply the video the overall app freezes. 

PS: superb development done.. Lots of new intresting and intuitive features.

**Comment by login22rvp** [comment]
Replay*

**Comment by selurvedu** [comment]
Same here.

**Comment by selurvedu** [comment]
Probably the same bug as in #147.

**Comment by jonjomckay** [comment]
This is a duplicate of #147, so I'll close this ticket for now. Please follow the other issue for updates!
