### ISSUE TITLE
Add patchnotes to releases

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [jonjomckay/fritter#154]
I have yet to came across an option to view patchnotes and I quite like to read them especially for a project that I also like and is quickly expanding. So adding patchnotes would be useful.

**Comment by nidunc** [comment]
F-Droid shows the changelog for the latest version.  
You can also view all changelogs here: https://github.com/jonjomckay/fritter/tree/master/fastlane/metadata/android/en-US/changelogs (they don’t include the version numbers, though, only the dates on which they were published, so you’d have to figure out which version number each changeling belongs to yourself).

**Comment by jonjomckay** [comment]
The release notes are also listed on the repository's [Releases](https://github.com/jonjomckay/fritter/releases) page within a few hours of a new version being published.

There's also #125 which would display the release notes somewhere inside the app itself.

Closing for now, as I think the request has been answered, but please re-open if you think there's something else!
