### ISSUE TITLE
Data can not be imported in the latest version 2.10.0.

### ISSUE THREAD

**Issue by eraofphysics** [jonjomckay/fritter#155]

**Comment by eraofphysics** [comment]
Data can not be imported in the latest version 2.10.0.

**Comment by login22rvp** [comment]
I am not able to export data as well in V2.10

**Comment by jonjomckay** [comment]
Could you give some more details of any errors you're getting, or what exactly isn't working? I'm still able to both export and import on v2.10.0 so any help would be appreciated!

**Comment by WindHun7er** [comment]
Same here.

Model: SM-N986B/DS
OS: Android 11 + One UI 3.1
App version: v2.10.0]

Steps to reproduce the behavior:
1. Go to 'Settings' then to 'Export'
2. Select what you want to export
3. Click on the button to export
4. Nothing happens. No error displayed.

**Comment by jonjomckay** [comment]
Thanks all - I was able to reproduce this in the end, and have applied a fix for the next version!
