### ISSUE TITLE
Channels can not be subscribed in the latest version 2.10.0.

### ISSUE THREAD

**Issue by eraofphysics** [jonjomckay/fritter#156]
Channels can't be subscribed in the recent version 2.10.0.

**Comment by jonjomckay** [comment]
Could you give some more details on what exactly you mean by "can't be subscribed"? If there's an error message, please supply it in the description.

v2.9.0 added a menu to the subscribe button, so it's now two taps to subscribe.

**Comment by eraofphysics** [comment]
Sir I have already uninstalled the latest version and reinstalled the
version 2.9.0.

**Comment by jonjomckay** [comment]
Closing due to no response, and I think this is already fixed in either the v2.11 or v2.12 series anyway 🙂
