### ISSUE TITLE
[REQ] Be able to re-order tabs, and add groups as home screen tabs

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#160]
Default Order in 2.9.0: 

Feed | Subscription | Trends | Saved Tweets

Don't care much about Trends. They tend to be either toxic or unrelatable. Would like to easily view my Saved tweets instead by moving it to the left.

Version: 2.9.0

**Comment by WeeBull** [comment]
In addition, it would be good to be able to place the groups we have as tabs.

**Comment by kaladin-syl** [comment]
I'd prefer an option to remove the 'Trends' tab altogether.
