### ISSUE TITLE
[BUG] Some videos don't load

### ISSUE THREAD

**Issue by Lightson73540** [jonjomckay/fritter#161]

**Comment by jonjomckay** [comment]
Thanks for the bug report. Would you be able to fill in the rest of the bug issue template? I'll need some kind of reproduction (e.g. a tweet where the video doesn't load) and at least which version of Android you're using. Thanks!

**Comment by Lightson73540** [comment]
Thanks for the answer. I'm using Android 4.2.2. And there is the video: https://twitter.com/YaoYaoQwQ/status/1405463080834797569

And there's my screenshot

![Screenshot_2021-06-17-20-52-07](https://user-images.githubusercontent.com/86080053/122486903-5c05a680-cfb0-11eb-9371-0bdcf5f45bd1.png)

Sorry for the bad english! =)

**Comment by jonjomckay** [comment]
Awesome, thank you!

I'm not able to make the error happen, but I think it might be to do with how old your version of Android is (4.2.2). I have added the error message into the video player now, so if something goes wrong, it will show a message, which should help me fix (or figure out) the problem.

The error message will be in the next version of Fritter, or if you want to try it out quicker, you can download the APK from [here](https://github.com/jonjomckay/fritter/actions/runs/950375396)

**Comment by Lightson73540** [comment]
Thanks, sir. I'm waiting the next version

**Comment by Lightson73540** [comment]
Hi, sir. I upgraded to v2.10.0+20210615 version, and I have the same problem in the screenshot. And no error message was displayed

**Comment by jonjomckay** [comment]
From @Alcidauk in #172:

> **Describe the bug**
> After starting video play, if I try to jump at another timestamp, the whole app freeze. I then need to kill it.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to a tweet with embedded video
> 
>     2. Start playing video
> 
>     3. Click on the timeline.
> 
> 
> **Screenshots**
> I don't think a screen will help but I can provide ond if needed.
> 
> **Device**
> Moto Z with GSF, android 10 (lineageOs), fritter 2.10.0.
> 
> Nota: a huge thanks for this amazing app. It's really much simplier to use this app instead of twitter website !

Also from #172, from @JJFlash-IT:

> **Describe the bug**
> After starting video play, if I try to jump at another timestamp, the whole app freeze. I then need to kill it.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to a tweet with embedded video
> 
>     2. Start playing video
> 
>     3. Click on the timeline.
> 
> 
> **Screenshots**
> I don't think a screen will help but I can provide ond if needed.
> 
> **Device**
> Moto Z with GSF, android 10 (lineageOs), fritter 2.10.0.
> 
> Nota: a huge thanks for this amazing app. It's really much simplier to use this app instead of twitter website !

**Comment by Lightson73540** [comment]
**Describe the bug**
Yes sir, I got it! It's the same video. I tried to play in version v2.11.2+20210620

**To Reproduce**
Steps to reproduce the behavior:

> 1. Go to a tweet with embedded video
> 2. The player shows this message instead of thumbnail

P.S.: This bug just happens sometimes, I can watch some other videos.

**Screenshots**
![Screenshot_2021-06-24-17-41-35](https://user-images.githubusercontent.com/86080053/123331427-aa1d2b80-d515-11eb-94c6-4e3351ec445e.png)

**Device**

- Samsung Galaxy S4
- Android 4.2.2

**Comment by Screenshared** [comment]
I have same error with android 10 and app version 2.14.1

It happens when i scroll down to older account videos, bookmarks and media tab

**Comment by jonjomckay** [comment]
Thanks all for your reports - this should finally be fixed in the next (v2.15.0) version! The commit 595b565 details why this was happening.
