### ISSUE TITLE
[FR] Link previews

### ISSUE THREAD

**Issue by backme7** [jonjomckay/fritter#17]

**Comment by jonjomckay** [comment]
@backme7 could you elaborate a bit more on what you'd looking for from this feature? I'm unsure what link previews might be here 😅

**Comment by backme7** [comment]
![IMG_20210423_111925](https://user-images.githubusercontent.com/79310789/115824903-21551700-a422-11eb-84fe-dad80121d654.jpg)
![IMG_20210423_111038](https://user-images.githubusercontent.com/79310789/115824933-2a45e880-a422-11eb-9f71-3773ba9ae2a1.jpg)
