### ISSUE TITLE
[BUG] For some users the tweets are not displayed, but an error.

### ISSUE THREAD

**Issue by DocSniper** [jonjomckay/fritter#173]
**Describe the bug**
For some users (e.g.: @2ContextPpl) the tweets are not displayed, but an error: "Null check operator used on a null value".

**To Reproduce**
Search the user, e.g. @2ContextPpl and click to see the tweets.

**Screenshots**
![Screenshot_2ContextPpl](https://user-images.githubusercontent.com/3104188/122670284-7e224300-d1c1-11eb-884f-659ab6ce4100.png)

**Device**
LOS 17.1, Fritter 2.11.2

**Comment by jonjomckay** [comment]
This one should be fixed now, and going out in v2.12.0. It looks like that profile has a pinned tweet, but the tweet no longer exists, so Fritter was barfing on it 😅
