### ISSUE TITLE
[BUG] For subscribed users that no longer exist, an error is displayed.

### ISSUE THREAD

**Issue by DocSniper** [jonjomckay/fritter#174]
**Describe the bug**
For users that no longer exist, the error "Null is not a subtype of type Map<dynamic, dynamic>" is displayed.
Here it would certainly be better to recognize this and display a corresponding message to delete the subscription.

**To Reproduce**
When clicking on a user in the Subscriptions list that does not (no longer) exist.

**Screenshots**
![Screenshot_non_existing_user](https://user-images.githubusercontent.com/3104188/122670549-f0dfee00-d1c2-11eb-8214-0f0aff8ff7b8.png)

**Device**
LOS 17.1, Fritter 2.11.2

**Comment by jonjomckay** [comment]
Would you be able to supply the username of the now-deleted user? I think Twitter will return a different response than a usernametthat never existed, so Fritter will need to handle them slightly differently.

**Comment by DocSniper** [comment]
Yes certainly, the username was: @cov19treatments
But I found another one, maybe with different error, but this account doesn't exist anymore either: @PHockertz

**Comment by jonjomckay** [comment]
Thanks for those account names - I was able to add in handling for suspended and missing profiles like those two. The fix will go out in v2.12.0!
