### ISSUE TITLE
[REQ] Optimize thread & reply depiction

### ISSUE THREAD

**Issue by RequestPrivacy** [jonjomckay/fritter#179]
**Describe the problem that needs solving**
See explanation image

**Describe the solution you'd like**
See explanation image

![Thread](https://user-images.githubusercontent.com/72392544/123317820-f9675a00-d51d-11eb-8d1b-b95a9f4bba93.png)

**Comment by jonjomckay** [comment]
This is a limitation that I'm not sure how to address unfortunately. For the API being used by groups/feeds, Twitter sends back no information on conversations or threads, and only sends back tweets from users that are requested in the query (i.e. your subscriptions). If a thread contains tweets from an account you're not subscribed to, or that account isn't in the current group, those tweets aren't returned.

However, Fritter does try its best with the tweets it is sent back - it will try to build a thread, even if it's only a partial one, but I'm not too sure how to load in any missing tweets (or even to know what those missing tweets are, without making `O(n)` API calls)

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
