### ISSUE TITLE
[REQ] Share text rather than copy

### ISSUE THREAD

**Issue by dkanada** [jonjomckay/fritter#180]
**Problem**

The context menu for selected text only supports copy as far as I can tell. Several apps that I use can handle text shared from other apps, which seems to be unavailable here.

**Solution**

When text is selected, an option to share the text is available. In Java or Kotlin this can be [handled manually](https://stackoverflow.com/questions/9948373) with intents. It's normally available for any selected text, so I assume the issue here is something with Dart.

**Comment by jonjomckay** [comment]
I'll look into this, but in the meantime, the "Share" button on tweets does let you share the full tweet content to any other supported intent.

**Comment by rancidfrog** [comment]
@jonjomckay 
Is it possible to allow for the sharing of images directly.
As in, either in context menu or image view, have share image
Currently in image view there is only save button on top right corner,
![](https://i.imgur.com/wQu1BbG.jpg)

While in context menu there is share tweet, content, or save,
![](https://i.imgur.com/6MNeowD.jpg)

**Comment by genodeftest** [comment]
@rancidfrog : Your request is covered in #336.
