### ISSUE TITLE
[REQ] Add ability to hide the number of likes/retweets on posts

### ISSUE THREAD

**Issue by matt-auckland** [jonjomckay/fritter#181]
This is a nice feature of Instagram that I enjoy, would be great if fritter had it too!

**Describe the solution you'd like**
Basically just add toggles in the fritter settings to show/hide the number of likes or number of retweets on tweets.

**Comment by eredrolo** [comment]
This looks same as #120. You can follow that issue for this feature.

**Comment by matt-auckland** [comment]
Yeah looks like that covers that same issue, thanks for pointing it out. Will close this.
