### ISSUE TITLE
[BUG] High RAM usage

### ISSUE THREAD

**Issue by eredrolo** [jonjomckay/fritter#182]
**Description**
Fritter's RAM usage increases as I scroll through the feed. My phone only has 2 GB RAM, so this causes the phone to slow down and freeze after ~10 mins.

I would like if the memory management is improved.

**To Reproduce**
1. Open any feed
2. Scroll down
3. See the RAM usage increasing

**Screenshots**
RAM usage at the start -  
![Screenshot_20210626-152439](https://user-images.githubusercontent.com/74611933/123509402-ede96f80-d692-11eb-8345-f4d4b4918fa2.jpg)
 
RAM usage after some time -  
![Screenshot_20210626-144328](https://user-images.githubusercontent.com/74611933/123509428-14a7a600-d693-11eb-8905-b662571c933d.jpg)

**Device**
Xiaomi Redmi Note 3
Android 10
Fritter 2.11.2 (F-droid)

**Comment by jonjomckay** [comment]
I've just pushed an improvement to memory usage in 595b565, which should lower things by quite a lot!

In a test on my phone, scrolling to the same point in my feed:

|                  | Usage (MB) |
|------------------|------------|
| Before (RSS)     | 714.18     |
| Before (Android) | 435.77     |
| After (RSS)      | 196.07     |
| After (Android)  | 55.04      |

These improvements will go out in v2.15.0, and will also be available in the next [development build](https://github.com/jonjomckay/fritter/actions)
