### ISSUE TITLE
[REQ] Option to sort tweets from old to new

### ISSUE THREAD

**Issue by VesperLlama** [jonjomckay/fritter#183]
**Description**
Currently, tweets are sorted by new to old. Sometimes people tweet something in reference to an older tweet and you have to go down to get the context for that tweet to understand it.

**Solution**
I would like if the tweets are sorted in chronological order (old to new). This would make them easier to follow.

An option can be added to only display tweets newer than X time (6 hr, 12 hr, 1 day, etc). Then the tweets can be sorted from old to new.

**Comment by jonjomckay** [comment]
Unfortunately, I don't think this is going to be possible - at least not efficiently possible. I'm not using any official API from Twitter, so Fritter is at the mercy of their unofficial web APIs, and those have very limited sorting capabilities.

For this to work efficiently, I'd need to have the ability to limit how far back a search using the API can go, and another option to sort reverse chronologically (or rather, chronologically), but that's not possible, as far as I can tell.

I'll keep this open for now, but I can't commit to it until I know for sure that it's possible.

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
