### ISSUE TITLE
[REQ] Saving images without prompting.

### ISSUE THREAD

**Issue by vivianandrea** [jonjomckay/fritter#184]
Hi,

Describe the problem that needs solving

Everytime you use save button app need you to choose location where to save.
Button to save image is on right top side of screen which is not optimal for larger devices.
Describe the solution you'd like

Save button always should download image to the first choosed location without prompting everytime.
Change location of save button to the right bottom side. Also please give option to save image without entering into picture view like is done with videos.
Greetings

**Comment by jonjomckay** [comment]
This is now supported as part of the v3.0.0 betas. You can set a default download directory on the Settings screen.
