### ISSUE TITLE
[REQ] Ability to open a tweet in the app

### ISSUE THREAD

**Issue by Victor239** [jonjomckay/fritter#185]
**Describe the problem that needs solving**
If I open a tweet on my web browser, I can't use Open in App or the Share intent menu to open the tweet inside of Fritter.

**Describe the solution you'd like**
Ability to open a single tweet view in Fritter.

**Comment by eredrolo** [comment]
![Screenshot_20210630-000216](https://user-images.githubusercontent.com/74611933/123849907-fe217900-d936-11eb-997a-74184776bfdb.jpg) 

It shows for me in the Open in menu. Have you set up a different default app to open the link?

**Comment by Victor239** [comment]
Ah nevermind, yeah setting a different default app is why.

**Comment by eredrolo** [comment]
Please close the issue if your problem has been resolved.
