### ISSUE TITLE
No retweets on Groups and all

### ISSUE THREAD

**Issue by mndsc** [jonjomckay/fritter#186]
Hello and congrats for your work!  

I have an issue with retweets. I'm using Fritter v2.12.0+200625 on Android 8.2 (but it did happen on previous versions, too). 
Even though I select the 'Include retweets' option on 'Groups' and 'All', I can't see them on timeline. I can view them when I visit a profile but not on the Groups or All timeline. 

Thank you.

**Comment by jonjomckay** [comment]
This is a limitation imposed by Twitter unfortunately. Ticking the "include retweets" option for feeds does send the correct parameter to Twitter, but they only sometimes seem to send back retweets, and more often than not, no retweets are returned at all.

Closing for now, as there's nothing I can do 😢
