### ISSUE TITLE
[BUG] Some tokens cannot be parsed from a _Mint to a String

### ISSUE THREAD

**Issue by Xenoslyce** [jonjomckay/fritter#187]
**Describe the bug**
Fritter does not allow me to view profile, search results, or anything. It just gives a "type '_Mint' is not a subset of type 'String?'"

**To Reproduce**
1. Go to a profile, search, or do anything that would use Twitter
2. See the bug and weep

**Device**
moto e5 supra, Android 8.0.0, Fritter v2.12.0+20210625

**Comment by Xenoslyce** [comment]
I originally submit this bug under the F-Droid version but this seems to be effecting the latest GitHub version as well.

**Comment by jonjomckay** [comment]
Hmm, looking at the reports coming into Sentry, this looks like Twitter has maybe changed their token type from a String into an integer? I'm still able to use things as normal so it could be a slow rollout they're performing...

I'm out of town until tomorrow, but I'll check this out as soon as I'm back (unless someone else fancies giving it a go!

**Comment by Xenoslyce** [comment]
Seems to have fixed itself, oddly enough.

**Comment by jonjomckay** [comment]
Reopening this as it still needs to be handled, as other users are encountering the problem.
