### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by Gottarocket** [jonjomckay/fritter#188]
I use this as my search and feeds are tracked to recommend but I would like an option thats on twitter to subscribe to an category like science , news, cybersecurity and so on amd get its feed and also if you can integrate appwrite for pus notifications on new tweets so I can delete twitter for good

**Comment by jonjomckay** [comment]
A directory of recommendations sounds like something that's out of scope for Fritter, at least for now unfortunately.

Support for push notifications is being tracked in #110.
