### ISSUE TITLE
Certificate verify failes

### ISSUE THREAD

**Issue by dev-cow1** [jonjomckay/fritter#189]
I'm using Lineageos with Afwall. This works well for many weeks.
Since about 4weeks I got an error using fritter: HandshakeException: Handshake error in Client (OS Error:
Certificate_verify_failed: unable to get local issuer certificate(handshake.cc359))
Somit seems that something had changed. is there anything I habe to reconfigure in Afwall?

**Comment by jonjomckay** [comment]
I'm unfamiliar with Afwall, but that error sounds like something else is intercepting HTTPS requests to Twitter on your device. That's not currently supported by Fritter - connections to `api.twitter.com` and `twitter.com` must be using the original TLS certificates for Fritter to be able to handle them.
