### ISSUE TITLE
[BUG] Replies Showing up in the 'Feed' Tab

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#190]
In version **2.12.0**, I can see replies in the Feed tab. Can't find any option to hide replies in that tab like there's for Groups. Bug?

**Comment by alphanerdgen** [comment]
@jonjomckay Here's a screenshot:

![Fritter Feed](https://user-images.githubusercontent.com/83120103/125197713-757ed300-e27c-11eb-8133-d2b26100eb7d.png)

**Comment by jonjomckay** [comment]
The settings button isn't currently displayed on the Feed tab, but you should be able to change the settings under the "All" group in the meantime, as they're the same thing under the hood.

**Comment by paulverbeke** [comment]
Thanks ☺️ didn't realized there's was filters there. The UX to find this filter view doesn't looks very conventional.
But I can't complain as this app you built is really great, thanks for your hard work !

**Comment by paulverbeke** [comment]
I've uncheck "Include replies" and most of the replies were correctly excluded, but I still see some of them ![](https://i.imgur.com/snpBm3v.jpg)

**Comment by jonjomckay** [comment]
This is now fixed as part of the v3.0.0 betas.
