### ISSUE TITLE
[BUG] Feed and "All" Group Doesn't Load

### ISSUE THREAD

**Issue by SuperSonicHub1** [jonjomckay/fritter#193]
**Describe the bug**
Fritter errors out on interacting with the Feed tab or All group.

**To Reproduce**
1. Go to Feed or the All group.
3. See error.

**Screenshots**
![Feed tab](https://user-images.githubusercontent.com/25624882/125814610-612f7b6f-0c71-4ffa-aaf5-c92ef00e6a49.png)

**Device**
Google Pixel 3a
Android 11
v2.12.0+20210625

**Comment by med93600** [comment]
Same issue with Xiaomi Poco x3

The behaviour is strange, if I decrease the number of following, the Feed Works.

**Comment by SuperSonicHub1** [comment]
> Same issue with Xiaomi Poco x3 Android 11 fritter : 
> v2.12.0+20210625
> The behaviour is strange, if I decrease the number of following, the Feed Works.

Do you think it might be an upper limit to the number of profiles that the Twitter API will look up at once?

**Comment by med93600** [comment]
Maybe 
I'm a New user or fritter, I installed it today
In my all group I have 400 items
I have created a dummy group with about 60 items. Error ! I decreased to 40. Working. And I have increased
Step by step with a max of 66 working. Now I tried to increase but error. But now for exemple 58 items and it doesn't Work
Very strange

**Comment by SuperSonicHub1** [comment]
Really? I actually follow around 35 people.

**Comment by jonjomckay** [comment]
Fritter should already be batching large sets of users into different API calls so it doesn't hit the maximum, and I'm not able to reproduce this with a large set of users.

I've just pushed some improvements (d163643)  to how these kinds of errors are displayed and reported, which should be going into the next version (v2.13.0). If anyone on this thread is able to [download and install the latest development build](https://github.com/jonjomckay/fritter/runs/3087684865) and either report or screenshot the new errors here, I might be able to fix them ready for the next version!

**Comment by SuperSonicHub1** [comment]
I cannot replicate the bug anymore, even though I've been dealing with it
for two weeks, so I won't be able to help.

**Comment by med93600** [comment]
Hi I have installed the 2.13.0 version
I have this error 
![Screenshot_2021-07-16-22-33-23-887_com jonjomckay fritter](https://user-images.githubusercontent.com/36095524/126005559-ca27ebed-7a62-4cc8-8602-fe6a58429c55.jpg)

When I disable "include replies", it Works

**Comment by WindHun7er** [comment]
Same problem (issue #82) same error obtained with v2.13.0. 

I tried to disable the replies and the all group is working again on my side, but until when (it seems to me that I had already tried this before and the error had finally reappeared... but I may be wrong...) 
Strange...

**Comment by jonjomckay** [comment]
Thanks @med93600 and @WindHun7er (and everyone else who reported and submitted this error) - the new error reporting helped finally track down what was causing this! The Twitter API has a limit of 500 characters when searching, and this bug was causing Fritter to limit to 502 instead, making Twitter throw an (unhelpful, but obvious once you know the problem) error.

The fix will be in v2.14.0 (or the next development build).

**Comment by SuperSonicHub1** [comment]
Great!

**Comment by jonjomckay** [comment]
@SuperSonicHub1 is this still happening, even with the latest version (v2.14.0 or v2.14.1)?

**Comment by SuperSonicHub1** [comment]
No, not anymore. I'll close this issue.
