### ISSUE TITLE
Fold the Subscription List

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#195]
For the sake of privacy and also UI, please provide a way to fold the subscription list. That'd be great for users like me who prefer Groups over Subscriptions list. By folding it I could get it out of the way and also prevent others from seeing which accounts I'm following (even though they're your typical tech, gov-related accounts).

There used to be an option—a drop-down arrow icon— to do that for Groups but it's not there anymore.

**Comment by jonjomckay** [comment]
This should already be possible - the Group and Subscription section titles should be tappable, which collapses and expands the respective sections. They should be coloured blue, which is used in Fritter as the "this thing is tappable" indicator.

Though, please let me know if they're not working on your device!
