### ISSUE TITLE
Add swipe gesture to exit from media view

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [jonjomckay/fritter#197]
**Describe the problem that needs solving**
A clear description of what the problem is. E.g. I'm always frustrated when [...]

We can only go back from an opened video viewer for example, with a back navigation command and the arrow at the top-left. It would be useful to have a swipe gesture that exits.

**Describe the solution you'd like**
A clear description of what you want to happen.

Either swiping from the left to right or from the bottom to top would exit from the media view.

**Comment by jonjomckay** [comment]
This is now supported as part of the v3.0.0 betas, by swiping down.
