### ISSUE TITLE
Video player had error

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [jonjomckay/fritter#198]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
A clear description of what the bug is.

Certain videos do not load and give error.

**To Reproduce**

Random

**Context**

Example:
 https://twitter.com/jacksfilms/status/1417178934479769603

Code:

`Video player had error g.a.a.a.j0:
MediaCodecVideoRenderer error, index=0,
format=Format(2, null, null, video/avc,
avc1.640020, 2176000, null, [1280, 720, -1.0], [-1, -1]), format_supported=YES`

_also please make errors copy-able_
**Device**
Your device model, OS version and Fritter version.

Unrelated, Android 10, Lineage 17.1, v2.12.0+20210625

**Comment by IHateTheProgrammingClass** [comment]
Same bug on version v2.13.0+20210716. Only the part that's in () different.

**Comment by WindHun7er** [comment]
I think it's the same bug as #161 . 
The same thing also happens for me (even in release 2.14.0). The first videos load correctly and then later in the feed (all or groups) the error happens for all the video media. 

**Device**
Model SM-N986B/DS, 
Android 11/One UI 3.1, 
Fritter v2.14.0

**Comment by Screenshared** [comment]
I have same error 
Android 10 
Fritter 2.14.1

**Comment by jonjomckay** [comment]
Thanks all for your reports - this should finally be fixed in the next (v2.15.0) version! The commit 595b565 details why this was happening.

**Comment by IHateTheProgrammingClass** [comment]
@jonjomckay
