### ISSUE TITLE
add RTL support

### ISSUE THREAD

**Issue by alefvanoon** [jonjomckay/fritter#2]
please add RTL support for Persian and Arabic .
![image](https://user-images.githubusercontent.com/53198048/111159378-49916080-85ae-11eb-9e6a-90107be7a8be.png)

**Comment by jonjomckay** [comment]
@alefvanoon I think I've fixed this, but I'm not 100% sure. Please could you check the screenshots in #5 and confirm?

**Comment by alefvanoon** [comment]
thanks.
now its working great with persian and arabic.
