### ISSUE TITLE
[BUG] Japanese kanji characters

### ISSUE THREAD

**Issue by ghost** [jonjomckay/fritter#200]
**Describe the bug**
although i have my phone set to japanese, the app still shows tweets (written in japanese) with chinese kanji characters...

**Device**
OnePlus 7 Pro, Android version 11, Fritter version 2.12.0

**Comment by jirogoro** [comment]
It looks to have been fixed after Japanese locale was added in version 2.16.

**Comment by jonjomckay** [comment]
Closing, as reported as fixed and the original reporter has closed their GitHub account, so impossible to confirm their specific bug is fixed.
