### ISSUE TITLE
[BUG] Cannot view profile of author of Tweet

### ISSUE THREAD

**Issue by SuperSonicHub1** [jonjomckay/fritter#201]
**Describe the bug**
When trying to view the author of a Tweet, sometimes the app will simply be unresponsive.

**To Reproduce**
1. Go to Feed.
1. Click on  a "Replying to."
2. Click on author's profile image and username.
3. Nothing happens.

**Screenshots**
https://user-images.githubusercontent.com/25624882/126406684-2407ea8e-32a8-49f3-b13a-4c0ec9d281fa.mp4

**Device**
Pixel 3a
Android 11
v2.13.0+20210716

**Comment by jonjomckay** [comment]
This should be fixed in 62c9874652a1c19ff32424e26a22fc401ae53213, and will go out in v2.15.0!

**Comment by SuperSonicHub1** [comment]
Great!
