### ISSUE TITLE
[UI][BUG] Reload button is missing any feedback (no spinner)

### ISSUE THREAD

**Issue by ghost** [jonjomckay/fritter#203]
**Describe the bug**
I am using an Orbot and sometimes (quite often in fact), Twitter blocks an IP. I have to get new exit node and then click [Refresh] in Fritter.

Problem is, there is no "loading" indication, so I have to look into Orbots up/down speeds to confirm, that it is loading in the background.

**To Reproduce**
1. Use Orbot, connect to Ror
2. Find an exit node that is blockd
3. Change exit node in Orbot
4. Hit refrest
5. No indication that it is loading in the backgroun is show, the feed just shows up after some time (if successful)
6. If not successful, the screen stays the same (no info that it failed again)

**Screenshots**
![signal-2021-07-23-094029](https://user-images.githubusercontent.com/78184669/126751494-80e84d08-670e-4f80-a8a6-bf783aab5da3.png)

**Device**
- Irrelevant

**Comment by jonjomckay** [comment]
This will be fixed in the next version.
