### ISSUE TITLE
Don't go top page after added a bookmark

### ISSUE THREAD

**Issue by Screenshared** [jonjomckay/fritter#208]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
Hello.
I would like to report a annoying bug, that make the main list of post go at top each time I add a bookmark.
Is it possible to keep the spage scroll even after added a post to bookmarks?

**To Reproduce**
Steps to reproduce the behaviour
2. Add a bookmark in a post that isnt on top of the list.
**Device**
Android 11

**Comment by oksya8and8** [comment]
I'm suffering from this bug myself. I'm hoping for a quick response from the developers.

**Comment by jonjomckay** [comment]
Good news - this should already be fixed in the upcoming version!

**Comment by jonjomckay** [comment]
Fixed in v2.15.0.
