### ISSUE TITLE
[BUG] Some Polish characters don't work in the profile search

### ISSUE THREAD

**Issue by Aga-C** [jonjomckay/fritter#209]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
The following Polish characters do not work when searching for profiles: "ć", "ł", "ń", "ś", "ź". When they are a part of the searched strings there are no results, when on Twitter it works normally.
When I change Polish characters to their simpler counterparts like "c", "l" etc. searching works, but it's more natural to use proper characters.

**To Reproduce**
1. Open Fritter.
2. Tap the search icon.
3. Enter "ćwiek", "jarosław", "zieliński", "świstak" or "paździoch".

**Screenshots**
![obraz](https://user-images.githubusercontent.com/85929121/127449268-f24586c6-350e-4884-913b-5029bca0f94b.png)

**Device**
OnePlus 9 Pro, Android 11, v2.13.0

**Comment by jonjomckay** [comment]
The fix for this will go out in the next version (v2.16.0)!
