### ISSUE TITLE
Missing information in a tweet and its replies.

### ISSUE THREAD

**Issue by WindHun7er** [jonjomckay/fritter#22]
Since the release 2.0.0, when you open a tweet you don't see all the information about likes, retweets, replies, etc...

Release 1.1.0 :
![Screenshot_20210423-083608_Fritter](https://user-images.githubusercontent.com/80457123/115829198-fad9b080-a40e-11eb-953d-b4368dc23035.jpg)

Release 2.1.0 : 
![Screenshot_20210423-083331_Fritter](https://user-images.githubusercontent.com/80457123/115829057-cbc33f00-a40e-11eb-92a4-5bb92f477119.jpg)

**Comment by jonjomckay** [comment]
Looks like this one broke in the migration from Nitter to the Twitter API. I've fixed it in b59b4dc356f931ce0f5a9522e68523cff1855423. Thanks for reporting!
