### ISSUE TITLE
[REQ] Hide or reduce the number of answers in the feed

### ISSUE THREAD

**Issue by Darkempire78** [jonjomckay/fritter#222]
**Describe the problem that needs solving**
Fritter is awesome, but my feed is spammed by answers. 2/3 of my feed is answers. 
By default in Twitter most of anwers are hiden and 9/10 of the feed are tweets.

It's for the moment the only problem preventing me from using Fritter

**Describe the solution you'd like**
To solve this issue, I suggest to add an option to hide every answers in the feed or add a configurable percentage (e.g: 80% of answers are hiden)

**Comment by jonjomckay** [comment]
You can actually do this already! If you open the "All" group, you can toggle options for that group from the menu at the top right. The Feed tab uses this group under the hood, so it applies to both.

It's not the greatest UX, but I'm working on it :)
