### ISSUE TITLE
[REQ] When opening a link exit the app when navigating back

### ISSUE THREAD

**Issue by IHateTheProgrammingClass** [jonjomckay/fritter#224]
**Describe the problem that needs solving**
A clear description of what the problem is. E.g. I'm always frustrated when [...]

When opening a Twitter link externally, it opens the app and shows the content, but instead of exiting it goes to the main feed.

**Describe the solution you'd like**
A clear description of what you want to happen.

Don't go to the main feed and exit.

**Comment by geominorai** [comment]
Agreed. It is annoying to have to use the back button twice to exit, especially when opening the link from a website or app like Reddit containing multiple Twitter links in the same post.

If some users prefer going back to the feed with the first back button, it may be better to have an option to toggle that in app settings.

**Comment by jonjomckay** [comment]
This has now been fixed in aa54d3a19e27b010593b4798354382340f5a67ca, and will be going out in the next release.
