### ISSUE TITLE
[REQ] 

### ISSUE THREAD

**Issue by ValuePrivacy** [jonjomckay/fritter#225]
I'm always frustrated when I have to force close the app to simply refresh my feed.

I'd like to see a pull to refresh feature or a reload button.

This has to be the only feature that I cannot stand not having after switching from the official app.

**Comment by salevdns** [comment]
There already is #100 and a7ddad783f56e6d5b955bf37d17b1775e5bb44dc implements it, so the next release will have that feature.
This issue can be closed.

**Comment by jonjomckay** [comment]
Closing this, as it was released in v2.14.0!
