### ISSUE TITLE
[BUG] Returning from a reply or retweet to feed view tweets are reloaded and newest tweet is shown.

### ISSUE THREAD

**Issue by DocSniper** [jonjomckay/fritter#237]
When returning from a reply or retweet to feed view, the tweets are reloaded from the server and jumped up to the newest tweet. But it should be the same as in the Groups/All view. If you do the same thing in Groups/All, it is as you would expect. If you click back, you're right back at the tweet where you clicked Replies/Retweets before.

Edit: My OS Version is LineageOS 17.1 / Android 10

**Comment by moberrauch** [comment]
I can confirm that this was introduced with the newest update to 2.14.0.

**Comment by jaredduggan** [comment]
This bug has made fritter almost unusable. If clicking on any link or thread and you attempt to go back you are brought back to the top of your feed and it is refreshed. It is hard to get past even 10 or 20 tweets before its so frustrating I quit using it.

**Comment by richburbidge** [comment]
I'm having the same issue. Running on a Pixel 4, Android 11, Calyxos 2.9.0. Fritter version v2.14.0+20210910.  It started with the last update.

**Comment by lsahnicne** [comment]
Xiaomi Redmi 4X
Android 6.0.1

Whenever i return to the Feed screen it is automatically reloaded and positioned at the top of the feed. Prior to the latest release, the feed did not refresh automatically and the position did not reset.

Video: https://litter.catbox.moe/kv6v5y.mp4

**Comment by jonjomckay** [comment]
Thanks @lsahnicne - your video showed me the exact problem! I've just pushed a fix for this in v2.14.1.

Sorry to all for causing this regression 🙂

**Comment by jaredduggan** [comment]
Trying to install the new version from github and getting the error app name is null and won't install. Anyone else?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jonjomckay** [comment]
@jaredduggan try downloading the APK again - it could be a corrupted download

**Comment by jaredduggan** [comment]
I have tried downloading it three times all with the same error. Has anyone else successfully installed the apk for 2.14.1?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by jaredduggan** [comment]
I guess I will wait for the update to hit F Droid and try then.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by lsahnicne** [comment]
@jaredduggan
If you installed Fritter from F-droid then you won't be able to update it with an .apk from GitHub. If i remember correctly, it's Android security shenanigans that require all updates to an app be from the same source as the initial installation.
