### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Telmote** [jonjomckay/fritter#240]
The possition of the feed is not saved and automatically returns to the most recent tweet

**Comment by jonjomckay** [comment]
I'm not 100% sure from the description, but this is a duplicate of either #57 or #237, so closing for now.

If this is a duplicate of #237, then a fix has been made and released in the latest version (v2.14.1), which is available to download from [GitHub releases](https://github.com/jonjomckay/fritter/releases), or from F-Droid in a few days!
