### ISSUE TITLE
[REQ] having the ability to toggle viewing replies on the main feed (and user bio) 

### ISSUE THREAD

**Issue by Relected** [jonjomckay/fritter#242]
on my main feed I always see my followings replying to others on my timeline, I want it so I can choose when to hide replies or not o  my feed, cuz my feed feels bloated 

Also I can't see people's bios whenever I try to clock on them (this could be solved by using nitter?)

**Comment by jonjomckay** [comment]
You can actually do this already! If you open the "All" group, you can toggle options for that group from the menu at the top right. The Feed tab uses this group under the hood, so it applies to both.

It's not the greatest UX, but I'm working on it :)

I'll close this in favour of #190 so its not being tracked in multiple places.

As for the profile bit, we already have a ticket tracking that too (#223), so subscribe to that to get notified when it's implemented!

**Comment by Relected** [comment]
@jonjomckay I appreciate your response but this doesn't work, in fact it does nothing. I still get random replies on my feed (with or without the filter)

**Comment by jonjomckay** [comment]
@Relected can you leave a reply on #190 with a link to some tweet(s) that still appear in your feed even with the filter applied? It'd come in very handy in trying to fix it :)
