### ISSUE TITLE
[REQ] See the number of followers/subscribers of a user when you are on his profile

### ISSUE THREAD

**Issue by Darkempire78** [jonjomckay/fritter#245]
**Describe the problem that needs solving**
We cannot see the number of followers/subscribers of a user when you are on his profile.

**Describe the solution you'd like**
Add the number of followers/subscribers of a user when you are on his profile below the account name or the subscribe button (like in Twitter)

**Comment by nowakommunikation** [comment]
This is still missing? 
Seems like an important feature. 
Had to call the profile in a browser to see the number of followers of an account.
