### ISSUE TITLE
[BUG] Clicking on "Replying to" and then saving that tweet causes the feed to scroll back up.

### ISSUE THREAD

**Issue by SuperSonicHub1** [jonjomckay/fritter#247]
**Describe the bug**
In your feed, if you click on "Replying to" to see a Tweet's parent, and then save said parent, after going back you'll be sent to the top of the feed

**To Reproduce**
1. Go to 'Feed'
2. Click on 'Replying to'
3. Save tweet
4. Go back
5. You'll be at the top of your feed.

**Screenshots**
https://user-images.githubusercontent.com/25624882/135859706-d1d4e7c1-a5d5-4f20-9adb-c417e64476cb.mov

**Device**
Your device model, OS version and Fritter version.
Pixel 3a
Android 11
v2.14.1+20210926

**Comment by frogtile** [comment]
This also happens on the Feed, saving a Tweet causes a scroll up and reload.

**Comment by frogtile** [comment]
> No longer happens!

Confirmed

**Comment by jonjomckay** [comment]
Thanks both!
