### ISSUE TITLE
[BUG] Downloaded images have truncated filenames, invalid extension

### ISSUE THREAD

**Issue by Travisyard** [jonjomckay/fritter#255]
**Describe the bug**
When saving an image, the file name is truncated and the extension is at least partially missing.

**To Reproduce**
1. Open a tweet with at least one image attached ([here's an example Tweet that I know has this bug](https://twitter.com/GrantBrisbee/status/1447277690898182144))
2. Tap any of the images to open it fullscreen
3. Tap the download button in the top-right corner
4 Save the file

Expected behavior: filename ends in ".jpg" and image is visible in stock gallery app.

Observed behavior: (in the above example tweet) filename ends in ".j" and image is not visible in stock gallery app. In other tweets it is possible that the extension is entirely absent.

Workaround: manually change filename via file browser or during save to end in ".jpg".

**Screenshots**

![image](https://user-images.githubusercontent.com/32996640/136975795-6c3b01e1-ce28-4295-ad39-4967d4be4a27.png)

**Device**
Version 2.14.1 (20211926) from F-Droid
dotOS v5.2 (AOSP 11)
Stock Gallery app and Simple Photos (F-Droid)
Stock Files app and Material Files (F-Droid)

**Comment by Travisyard** [comment]
> I believe this has been an issue since my PR #221 was merged.
> 
> I'm not very familiar with Flutter/Dart so it might be worth looking into my changes to see whether I've gone about it wrong.

I'm also not very familiar with Flutter/Dart, but I don't see anything wrong in what you did here.

**Comment by Gottarocket** [comment]
On my end doest save without extensions Filemanager recognize it as bin file

**Comment by jonjomckay** [comment]
The fix for this will go out in the next version (v2.16.0)!

**Comment by e-zk** [comment]
Awesome!
