### ISSUE TITLE
[BUG] Swiping to home is registered as scroll

### ISSUE THREAD

**Issue by Donkey-Doug** [jonjomckay/fritter#263]
**Describe the bug**
When trying to trigger the home gesture, fritter registers a scroll.

**Screenshots**

https://user-images.githubusercontent.com/50382414/137813520-d4c6e41d-71cf-4ea8-929f-283490c0efd9.mp4

**Device**
Xiaomi Mi 9T Pro
Android 10 (lineageos without google play services)
Fritter version 2.14.1

**Comment by jonjomckay** [comment]
Please could you fill in the rest of the bug template? I'm not able to reproduce this, so I need to narrow it down, based on at least the version of Fritter and Android, and maybe the device that you're using.

**Comment by Donkey-Doug** [comment]
@jonjomckay Do I still need to provide more info?

**Comment by jonjomckay** [comment]
This should be fixed in d90cd5b263ae5466671e3441b0fabea41221548b, and released in the next version!
