### ISSUE TITLE
[BUG]Importing does not work.

### ISSUE THREAD

**Issue by oksya8and8** [jonjomckay/fritter#265]
If you open Subscriptions after importing, the app will stop working.

**Comment by oksya8and8** [comment]
From v2.14.1 ---> v2.15.0
Operation becomes impossible.
No error message.

Pixel3a
Android11

https://user-images.githubusercontent.com/63846715/137891879-e4a4d392-dd85-429c-b193-e9f343743ebe.mp4

**Comment by jonjomckay** [comment]
@oksya8and8 thanks! I think I've narrowed it down, and I'll release a 2.15.1 to fix it today.
