### ISSUE TITLE
[REQ] Default download location

### ISSUE THREAD

**Issue by Donkey-Doug** [jonjomckay/fritter#266]
Please make it possible to select a download location in settings. Currently the app ask where to save a file every time.

**Comment by Mek101** [comment]
I'll queue myself. I manly use twitter to follow artists, and having to choose the download folder every time is a pain. I think adding a switch to specify a fixed download location in the settings would be the ideal solution

**Comment by jonjomckay** [comment]
This is now available in the latest beta, available here and on F-Droid!
