### ISSUE TITLE
Download Media

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#27]
An option to download media will be great!

**Comment by jonjomckay** [comment]
This would be nice, but my only concern would be that the app would need to ask for another (potentially broad) permission. I think it can be done without needing the "access all storage" permission, but then downloads wouldn't be accessible from outside Fritter. 

I'll do some investigation 🙂

**Comment by geebotron** [comment]
I was going to request a similar feature: The ability to "share" media to other apps.
E.g. You see a funny meme posted as an image inside a tweet - and you want to share the image on WhatsApp etc.
