### ISSUE TITLE
[REQ] combine "share tweet content" and "share tweet link"

### ISSUE THREAD

**Issue by dodumosu** [jonjomckay/fritter#272]
**Describe the problem that needs solving**
The share functions work great, but would it be possible to combine them, so it's clear that the shared content is a tweet? I sometimes share tweets via WhatsApp, and I have to share and copy twice to show that it's not an original thought I'm sharing, but leave the tweet text immediately visible to the recipient, and not require that they have to visit Twitter to get what I shared.

**Describe the solution you'd like**
Possibly add a third share option for something combined, or replaced both current share options with what I'm describing above. I don't know if making it an app setting might be bloat.

**Comment by afreakyelf** [comment]
Hi @dodumosu , Can I work on this?

**Comment by jonjomckay** [comment]
This will be going out in v2.17.0!
