### ISSUE TITLE
[REQ] View only main tweets, not tweet replies

### ISSUE THREAD

**Issue by DealsBeam** [jonjomckay/fritter#274]
**Describe the problem that needs solving**
When you subscribe to an account it shows the main tweets and reply tweets from that account

**Describe the solution you'd like**
A feature to only show tweets, not tweet replies

**Comment by jonjomckay** [comment]
This is already supported, if I'm understanding your question correctly!

To filter out replies for a group (including the All group), open the group up, then tap the menu button at the top right. This will bring up some checkboxes - one of which is "Include replies". Unticking this will prevent replies from showing up in that group.

If you instead mean when viewing a profile directly, there are now tabs across the top of the profile - Tweets, and Tweets with replies. The first of these will filter out replies.

Let me know if this helped, or if I'm misunderstanding something!

**Comment by Darkempire78** [comment]
it doesn't really work @jonjomckay 
![Screenshot_20220113-110749](https://user-images.githubusercontent.com/50015928/149309972-0b63422a-f7ae-459a-85b7-780b11f3dbe2.png)

![IMG_20220113_110805](https://user-images.githubusercontent.com/50015928/149309974-c8b5c4f7-9c8d-48c9-bb2f-0e66b14930c2.png)

**Comment by yamatt** [comment]
> To filter out replies for a group (including the All group), open the group up, then tap the menu button at the top right. This will bring up some checkboxes - one of which is "Include replies". Unticking this will prevent replies from showing up in that group.

This solved it for me, but I wouldn't have found it without these instructions as I don't really use the groups tab, so I didn't think to explore there.

To expand on it: Go to the Groups tab (second tab), press the _All_ box and a new view pops up. Press the 3 dots on the top right and from there you can turn off replies and retweets.

**Comment by Mrnofish** [comment]
Yeah, as a new user I found this pretty confusing and off-putting.

Sure, the option is there but very well hidden, doubt I would have ever looked for it under the All group hamburger menu.

**Comment by dhishkyaon** [comment]
@Mrnofish 100% agree

The only solution i can think off is just provide a filter option on the main feed of the app so that it will be visible to all. I had the same issue. I didn't even looked inside the Group options and im sure most people aren't aware of this option.

What do you think @jonjomckay ?

**Comment by jonjomckay** [comment]
I've added the "All" group menu to the Feed screen ([0443027](https://github.com/jonjomckay/fritter/commit/0443027e970d87ec03f213fed316f4d2fb3915b1)), and the change will be going out in v2.17.0.

Feel free to try out one of the CI versions of Fritter to see if it's any better for you. Thanks!
