### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Akko87** [jonjomckay/fritter#277]
I use graphene OS which tells you when your clipboard is being accessed.

I've received two notifications that fritter is pasting from my clipboard when I havnt actually pasted anything.

Is there a reasonable explanation for this?

**Comment by ManeraKai** [comment]
A quick look in the source code, there's just two places:
1. https://github.com/jonjomckay/fritter/blob/master/lib/settings/settings.dart#L374
2. https://github.com/jonjomckay/fritter/blob/master/lib/settings/settings.dart#L408

They only paste to clipboard and don't get data from it. Maybe it's from a 3-party-package, that needs a deeper inspection: https://github.com/jonjomckay/fritter/blob/master/pubspec.yaml#L23

**Comment by Akko87** [comment]
> A quick look in the source code, there's just two places:
> 
> 1. https://github.com/jonjomckay/fritter/blob/master/lib/settings/settings.dart#L374
> 2. https://github.com/jonjomckay/fritter/blob/master/lib/settings/settings.dart#L408
> 
> They only paste to clipboard and don't get data from it. Maybe it's from a 3d party package, that needs a deeper inspection: https://github.com/jonjomckay/fritter/blob/master/pubspec.yaml#L23

Okay, well I've tested this again on graphene OS and it has happened randomly at different intervals whenever   I have a full clipboard. It seems a little bit dodgy to me . Will definitely have to uninstall for the time being unless some light can be shed on this issue.

**Comment by jonjomckay** [comment]
This is a duplicate of #238, so I'd recommend following that thread. As @ManeraKai has said, Fritter itself doesn't do anything with the clipboard unless you tell it to - its a bug in Flutter itself, which will be fixed in the next major version.

Closing for now, so be sure to subscribe to #238 for updates!
