### ISSUE TITLE
Cannot Copy Tweet Text

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#28]
Unable to copy a tweet's text even after long-pressing on it.

**Comment by WindHun7er** [comment]
This has been added in v2.2.0 (79f6b5a) but it's not yet complete because it now prevents access to the tweet replies.

**Comment by alphanerdgen** [comment]
@WindHun7er Thanks for the reply. I'm using version 2.0.0. (Hope F-Droid updates it asap.)

**Comment by alphanerdgen** [comment]
This has been fixed in 2.2.0. Closing it.
