### ISSUE TITLE
[REQ] Please support http/socks proxy

### ISSUE THREAD

**Issue by rustforfuture** [jonjomckay/fritter#280]
**Describe the problem that needs solving**
A clear description of what the problem is. E.g. I'm always frustrated when [...]

Please support http/socks proxy for those reigns that blocked the website or for other use cases (networks that need it)

**Describe the solution you'd like**
A clear description of what you want to happen.

Please support http/socks proxy for those reigns that blocked the website or for other use cases (networks that need it)

Thank you very much

**Comment by givena** [comment]
i believe you can also use orbot

**Comment by jonjomckay** [comment]
Closing as a duplicate of #191.
