### ISSUE TITLE
Properly color the navigation bar

### ISSUE THREAD

**Issue by robotwombat** [jonjomckay/fritter#282]
![image, 50%](https://user-images.githubusercontent.com/44946401/140622930-550f4028-c254-4953-9752-98ad15e86cdd.png)
_Photo's contrast was decreased_
The navbar color in Fritter currently does not match the rest of the app. In the example above, the navbar is black while the dark theme is a dark grey. The navbar should match the dark theme's color, and vice versa in light mode.

For example, here's how NewPipe looks:
![image](https://user-images.githubusercontent.com/44946401/140622897-fcbbe00a-8848-482c-995d-3fabef96e5c9.png)
The navbar color matches the rest of the theme.

Thanks :)

**Comment by Syberiyxx** [comment]
This is a more serious issue than your screenshots show
![Screenshot_20220120-072540_Fritter](https://user-images.githubusercontent.com/2048087/150357560-3193333d-6ff9-4d73-a8d6-b82a4de10200.jpg)

**Comment by jonjomckay** [comment]
This is fixed in the v3.0.0 betas!
