### ISSUE TITLE
[BUG] Account following infinite of the same account

### ISSUE THREAD

**Issue by BobIsMyManager** [jonjomckay/fritter#283]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
A twitter account is seemingly following infinite of the same account

**To Reproduce**
1. Go to https://twitter.com/SenseClient on fritter
2. Tap on following
3. See error

**Screenshots**
![Screenshot_2021-11-07-17-52-35-633_com jonjomckay fritter](https://user-images.githubusercontent.com/70704875/140656062-a83a2fc7-02db-457e-a7a5-a80e37b1fca6.jpg)

**Device**
Redmi Note 9 pro, Android 11, Fritter 2.15.1

**Comment by jonjomckay** [comment]
The fix for this will go out in the next version (v2.16.0)!
