### ISSUE TITLE
[BUG] New group creation no longer works

### ISSUE THREAD

**Issue by cobratbq** [jonjomckay/fritter#284]
**Describe the bug**
The new group dialog does not respond when clicking on 'Ok' to create the new group.
This wasn't an issue before. I have several existing groups, which all function as expected. (AFAICT)

**To Reproduce**
1. Click 'New' to create new group.
2. Fill in any name.
3. (optionally select some members)
4. Click OK.

At this point, nothing happens. The dialog stays. No further response or sign of activity/change. Cancel button works, but afterwards no group is created.

**Screenshots**
N/A

**Device**
Samsung Galaxy. Android 11.
Version 2.15.1+202110192. (F-Droid)

**Comment by cobratbq** [comment]
Issue occurs in same dialog as issue #278. This might be related.

**Comment by tebeliment** [comment]
+1

**Comment by jonjomckay** [comment]
The fix for this will go out in the next version (v2.16.0)!
