### ISSUE TITLE
[REQ] Set % of each group in feed

### ISSUE THREAD

**Issue by rating89us** [jonjomckay/fritter#289]
**Describe the problem that needs solving**
If I have two groups, group A with 5 users and group B with 40 users, tweets of the group B (with more users) will display much more frequently in my general feed.

**Describe the solution you'd like**
Allow to set a % of each group in the general feed (group A: 60% group B: 40%).

**Comment by jonjomckay** [comment]
Unfortunately this isn't something Fritter is able to support, as it's not an option supplied by the Twitter API - we can only display what they send us back to display.
