### ISSUE TITLE
Room for Improvement in UI

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#29]
Suggestions:

There should be an arrow for Subscriptions just like there's one for Groups.

List of Subscriptions shouldn't be in expanded state by default.

Show Groups as tabs on the bottom.

Move the tabs (trending, Subscriptions) to the bottom along with the search icon and the gear icon. Makes it easier to navigate on big phones. Just keep the name of the page on top.

That's all I can think of, for now.

**Comment by alphanerdgen** [comment]
**Some More Suggestions for UI** @jonjomckay 

Okay, so I was thinking that even though the purpose of Fritter is to be a Twitter viewer, that's what it's not doing, at least not right off the bat.

When we open the app (v 2.2.0), we see trending hashtags (that too worldwide). Next, we have to swipe left to get to accounts, but even then a few more taps are required to view tweets.

Tweets should be at the front and centre of Fritter, not hashtags or a long list of subscriptions. To achieve that, I suggest displaying Groups (Lists) in the form of Tabs (which can be customized to be either at the top or at the bottom for easy access in big phones).

The first tab could be the ALL group. This will be the HOME feed. But it'll be empty initially so perhaps a + sign with the words "Add an Account" could be displayed in the centre.

Or maybe move the option to add groups or hashtags to SETTINGS. From there groups can also be reordered or removed (including Home if the user prefers seeing other groups instead).

**Comment by jonjomckay** [comment]
Thanks for these! I'll mull them over and see how some might turn out.

Currently, most of the inspiration has come from Newpipe, especially the subscription view, so it'd be nice to keep parity with that. But only if it doesn't actively cause UX issues...

**Comment by alphanerdgen** [comment]
@jonjomckay I don't think Newpipe's UI is ideal for Fritter. The former is primarily for watching videos while the latter is for reading and interacting with content in the form of text.

**Comment by peterflock** [comment]
My understanding of philosophy of the Fritter is that it is "read-only". I would not be happy to see any kind of login+reply functionality added into Fritter.

**Comment by HikaruIchijyo** [comment]
> Thanks for these! I'll mull them over and see how some might turn out.
> 
> Currently, most of the inspiration has come from Newpipe, especially the subscription view, so it'd be nice to keep parity with that. But only if it doesn't actively cause UX issues...

maybe chk harpy ui & get some inspirations from there

**Comment by iamtalhaasghar** [comment]
UX problem:
Everytime we click on a trend item from trending tab to see tweets for that trend, keyboard pops up and takes sizeable chunk of screen. I have to press back button to close keyboard to see the trending tweets.

Suggesstion:
1. The texfield at the top of a trend display screen should not be focused by default so that keyboard doesnt show up.

2. But user should be able to focus the textfield and search tweets for another trend.

**Comment by iamtalhaasghar** [comment]
Uploading recording_20220828_132501_001.mp4…

**Comment by iamtalhaasghar** [comment]
https://user-images.githubusercontent.com/46928648/187065203-e558c7e6-fec7-49fd-a4c5-8558d16fcccb.mp4

**Comment by jonjomckay** [comment]
Closing this, as v3.0.0 has a major overhaul of the app's UI. Please open new, individual issues if you think there's anything outstanding or missing in the new UI!
