### ISSUE TITLE
Image format error before downloading it

### ISSUE THREAD

**Issue by AhmedPie** [jonjomckay/fritter#291]
**Describe the bug**
When I click on any image and then click on the download icon.. it shows me directly the files application from my phone to determine where to download the application and at the bottom of the screen there is the name of the image and its format, where the image file format appears to me: image.j only!

And to fix the bug, I have to add "pg" after the "j" , for example:
image.j ==> image.jpg

**To Reproduce**
1. Go to 'images'
2. Click on 'Download icon'
3. See error
Images format is "j" not "jpg".

**Screenshots**
![IMG_20211210_101502](https://user-images.githubusercontent.com/79719273/145533098-a22e8cbd-8fa4-432d-92d7-b31dffbbaa55.jpg)
![IMG_20211210_101605](https://user-images.githubusercontent.com/79719273/145533103-3cfa9141-a28d-4077-912e-bec3bb9e1347.jpg)

**Device**
Your device model: Realme GT
OS version: Android 11
Fritter version: 2.15.0

**Comment by AhmedPie** [comment]
I have updated to 2.15.1

**Comment by lazytownfan** [comment]
@AhmedPie Could you please repoen this issue? I still experience this bug.

I was about to open a new GH issue, but then I found the reported bug.

**Device Info**
Device Model: Pixel 4a
OS version: Android 12 (latest GrapheneOS release SQ1A.220105.002.2022011009)
Fritter version: 2.15.1 (via F-Droid)
