### ISSUE TITLE
[BUG] I can't install the lastest version: 2.15.1 (202110192)

### ISSUE THREAD

**Issue by Lightson73540** [jonjomckay/fritter#294]
1. Download the lastest version on F-droid store
2. Run the apk installer
3. Shows that error message

![mbss_20211216_194401_866](https://user-images.githubusercontent.com/86080053/146460788-5092c43e-8ffa-4bca-9c99-f2b7be95ed8b.png)

**Device**
Samsung Galaxy J1 Mini
Android 5

**Comment by jonjomckay** [comment]
This is probably because you have the GitHub version installed - they are signed using different keys, so you need to uninstall the GitHub version if you want to install the F-Droid version, and vice versa. You'll also need to uninstall it from any secondary profiles on the device too.
