### ISSUE TITLE
[REQ] View user profile

### ISSUE THREAD

**Issue by yamatt** [jonjomckay/fritter#297]
**Describe the problem that needs solving**
It is currently not possible to see a user's profile from within the app. This can mean it is difficult to know if an account is parody or deliberate missinformation.

**Describe the solution you'd like**
To be able to select the user from their tweet and see their user profile information such as their full image, and description.

**Comment by jonjomckay** [comment]
This has been implemented and will be released with v2.16.0! See #204, #223 for more details.
