### ISSUE TITLE
[Feature Request] Option to Hide Media Preview

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#30]
Fritter shows media preview by default while using Wi-Fi or mobile data. An option to disable media preview will help save not just data but also the user from embarrassment in case something NSFW shows up in the feed!

**Comment by WindHun7er** [comment]
Maybe you can try to install v2.1.0 or higher ? I think the video player has changed in 9280a39 and it seems to me that the video does not launch by default since then.

**Comment by WindHun7er** [comment]
By the way, talking about the new video player it is probably smaller but it is definitely too simple. It lacks at least a video progress bar. The first one was more convenient on this aspect in my opinion.

**Comment by alphanerdgen** [comment]
@WindHun7er I installed the latest version (2.2.0) and the app still displays photos and videos automatically in WiFi as well as mobile data.

**Comment by jonjomckay** [comment]
This option would be a nice value-add. Twitter also returns different sized media in the response, so there's also the possibility of the user being able to choose to display a lower quality image which could save bandwidth but still display _something_
