### ISSUE TITLE
[REQ] Add Link Handling for Nitter links

### ISSUE THREAD

**Issue by MetalNeo** [jonjomckay/fritter#308]
**Describe the problem that needs solving**
I use Nitter to provide RSS feeds for Twitter and I want to be able to easily open these posts inside of Fritter instead of the browser.

**Describe the solution you'd like**
I would like if Fritter could redirect Nitter links to the app, and convert the link if necessary.

**Comment by jonjomckay** [comment]
This will be going out in v2.17.0!
