### ISSUE TITLE
Display Tweets instead of Accounts when Searching for a Hashtag

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#31]
Search for # Covid19 and Fritter will show you a list of accounts first. People usually look for tweets when they search for a specific hashtag.

**Comment by jonjomckay** [comment]
Agree - detecting a hashtag and showing the tweets tab should be a nice UX improvement

**Comment by jonjomckay** [comment]
Fixed in a4f597036621fbc079013f97949d5848d5e6990a, and will be going out in v2.9.0!
