### ISSUE TITLE
[BUG] Image file is saved without extension when downloaded

### ISSUE THREAD

**Issue by rating89us** [jonjomckay/fritter#317]
**Describe the bug**
When clicking on the download button of an image, it will save the image file but without the file extension (.jpg, for instance). Since the image file has no extension, it will not display on the gallery app.

**To Reproduce**
1. Open an image in a tweet
2. Click on Download button
3. Image is saved without file extension (user has to add .jpg every time)

**Device**
Pixel 4a with Graphene OS (Android 12), running Fritter v2.15.1

**Comment by GrafWasili** [comment]
I can reproduce this issue using v2.15.1 on Graphene OS, it exists at least for a couple of releases.

It seems only the first 30 characters of the generated file name ever appear in the FlutterFileDialog (it's possible to edit the file name and add the extension by hand tough).

A simple solution would be to simply omit the username or shorten it to a fixed length when generating the filename. 
This doesn't answer the question as to why this happens (something about the way Graphene OS handles things? or a bug in FlutterFileDialog?) but would make it work.

Any opinions on this? I could provide a pull request with such a solution if so desired.

**Comment by jonjomckay** [comment]
This is fixed in the latest version (v2.16)! Here's the commit in case you were curious what it was: https://github.com/jonjomckay/fritter/commit/d522a9bfc65e989897c2d8cd3d838307b5adac01

The update is available via GitHub already, and will make its way to F-Droid in the next week or so.
