### ISSUE TITLE
[BUG] An app doesn't work at all

### ISSUE THREAD

**Issue by DanielProg39** [jonjomckay/fritter#326]
When I open an application, is says this: 
![Screenshot_2022-01-25-14-47-36-111_com jonjomckay fritter](https://user-images.githubusercontent.com/63293432/150979682-420c04f6-9345-46a4-8f35-fe194ebc0fbe.jpg)
If I open someone's accunt, I see this:
![Screenshot_2022-01-25-14-57-34-888_com jonjomckay fritter](https://user-images.githubusercontent.com/63293432/150981415-d469485a-c945-41ec-b859-ed76d5072720.jpg)
It doesn't work whether I use a Wi-Fi or 4G. Rebooting the phone doesn't help either. Couple days ago everything worked well.
System: Android 11, MIUI Global 12.5.5 Enhanced.

**Comment by Nojuuu** [comment]
https://github.com/jonjomckay/fritter/issues/324#issuecomment-1021080102

**Comment by DanielProg39** [comment]
> [#324 (comment)](https://github.com/jonjomckay/fritter/issues/324#issuecomment-1021080102)

Oh, thanks! How couldn't I notice this before…
