### ISSUE TITLE
[BUG] Null check operator used on a null value

### ISSUE THREAD

**Issue by samhrvrdx** [jonjomckay/fritter#327]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
I can't use the application anymore.

**Screenshots**
![Screenshot_20220126-111214.png](https://user-images.githubusercontent.com/74729601/151144894-6797643a-4b02-4d85-92a1-6312fd01bae3.png)

**Device**
On Google Pixel 3a, Android 12, french, Fritter 2.16.0

**Comment by Aga-C** [comment]
https://github.com/jonjomckay/fritter/issues/324#issuecomment-1021080102

**Comment by samhrvrdx** [comment]
Oh sorry, thank you.
