### ISSUE TITLE
Display Threads Completely and in Correct Sequence

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#33]
Opened a thread but Fritter displayed only two tweets from it.

App Version: 2.0.0
Android: 11
Repo: F-droid

**Comment by alphanerdgen** [comment]
Can only see the thread in this manner (see pic). But the way Twitter shows it is more convenient. 

![Thread](https://user-images.githubusercontent.com/83120103/115962483-45574c00-a539-11eb-8ddf-7bc258697346.png)

**Comment by jonjomckay** [comment]
Yes, this is a big one. I need to examine the tweet metadata a bit deeper to figure out how to detect and display threads 🤔

**Comment by alphanerdgen** [comment]
@jonjomckay I wonder if we can kill two birds (this one and #24) with one stone: hiding replies in a feed.

This is how a thread appears in a group's feed or if you check the user's profile directly. Replies after replies.

![1](https://user-images.githubusercontent.com/83120103/116566335-4b2ba380-a924-11eb-88dc-cdf09b2e4bb6.png)

And this is how the same thread is shown after you tap on one of the tweets in that thread. IIRC, this is similar to how Twitter displays threads. So, if the users opts to hide replies, then they'll only see the first tweet of a thread, which is what we want.

![2](https://user-images.githubusercontent.com/83120103/116566652-8cbc4e80-a924-11eb-9b37-c2117d937e5e.png)

The one small issue with the second method of viewing a thread is that there's no way go back directly to the feed timeline. You can only go back one tweet at a time.

**Comment by jonjomckay** [comment]
Sorry for the long wait on this one - it should be implemented and will go out in v2.11.0!
