### ISSUE TITLE
[REQ] Filter Feed to show images/media only

### ISSUE THREAD

**Issue by Mesmer55** [jonjomckay/fritter#330]
For someone who follows almost solely artists, it is cumbersome to have to go through every tweet to find the ones with media. 

A filter option on the Feed tab, to show only posts including media, would be great. Thanks.

**Comment by RevolverTexture1** [comment]
This feature is already available in the Groups which is located on the Subscriptions tab but unfortunately it does not work for me 
![Screenshot_2022-01-27-19-03-28-65.jpg](https://user-images.githubusercontent.com/98118332/151418642-a6bdf54b-a785-4498-8d18-09248bac33e2.jpg)
![Screenshot_2022-01-27-19-03-23-91_1.jpg](https://user-images.githubusercontent.com/98118332/151418676-3324f52f-af0b-4ad1-a8a9-8eab44b997f3.jpg)

**Comment by Mesmer55** [comment]
There is no "Show only tweets _with media_" option yet afaik. Not in Feed, not in Groups. Adding such a filter for a specific group for example could be useful too. 

(Also, in the screenshot you provided there seems to be a visual glitch with the translate and retweet buttons. It started happening to me too. Might have to check other issue submissions for it.)

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
