### ISSUE TITLE
Disable the version check at the start

### ISSUE THREAD

**Issue by amit3s** [jonjomckay/fritter#331]
I use fritter via the fdroid store. Each time I use the app, I get a loud noise with a warning notification letting me know about fetching a new version.

Trouble is, I'm already on the newest version, but that doesn't matter to fritter. It warns anyway.

And I don't like the idea of a forced phones home feature, can this be an option, if not completely removed?

Thanks,

**Comment by nahuhh** [comment]
Disable "calling home"*

Thanks

**Comment by jonjomckay** [comment]
#334 has added an option to toggle this check, which will be going out in v2.17.0 🙂
