### ISSUE TITLE
t.co links are not clickable

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#34]
Links shortened by Twitter's own url shortner are not clickable while others are. See attached pic.

App Version: 2.2.0

![Fritter](https://user-images.githubusercontent.com/83120103/115961945-90bc2b00-a536-11eb-97ac-278c0028fadb.png)

**Comment by backme7** [comment]
Ig it's because it is the link of the video that is already attached with the tweet
![IMG_20210424_201705](https://user-images.githubusercontent.com/79310789/115962787-2ecdd800-a4da-11eb-8d79-d7db458389a0.jpg)

**Comment by backme7** [comment]
The best will be to somehow remove the redundant t.co link that appears along with the image/video.

**Comment by alphanerdgen** [comment]
@backme7 Oh, so the t.co links are only used for media files? All right, I didn't know that. 

Yeah, I agree those redundant links should be removed.

**Comment by xander-page** [comment]
t.co links can also be used to shorten external links. This definitely needs fixing.

![20210424_121411](https://user-images.githubusercontent.com/80866902/115967208-e1ac2f00-a4f6-11eb-8dc7-d94b3b9f3204.jpg)

**Comment by pluja** [comment]
This is an important issue from my point of view. Not being able to click links makes the user experience worse as links are a very important part from a lot of tweets. Also text from tweets can't be selected so I can't copy & paste the URL. Should I open a different issue for the text selection problem?

**Comment by jonjomckay** [comment]
Thanks for reporting - links without corresponding tweet text are a case I didn't realise existed, hence them not currently working, but I'll see if I can fix it. @backme7 is correct that most `t.co` links are just media links, and those should be able to be safely stripped, so hopefully I can find a way to do that consistently.

@pluja text should already be selectable in the 2.2.0 version, but you might have to wait for F-Droid to pick the update up - it sometimes lags behind by a few days 😅

**Comment by jonjomckay** [comment]
It looks like this was fixed already - probably in v2.1.0 with the new support for tweet entities (mentions, hashtags and URLs). I've just pushed something I committed this morning that should solve the trailing `t.co` links (which were actually a red herring and just essentially mean the tweet contains at least one entity 😅)

**Comment by theotheroracle** [comment]
does the app open t.co links ?
