### ISSUE TITLE
[BUG] Replies still being shown in main feed despite being disabled

### ISSUE THREAD

**Issue by yamatt** [jonjomckay/fritter#344]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
Despite following the guidance on how to disable tweet replies in #274 a new account I'm following still shows the replies.

**To Reproduce**
1. Disable tweet replies as per #274 
2. Follow a new account who replies to tweets
3. See replies in main feed

**Screenshots**
![Screenshot_20220203-073340](https://user-images.githubusercontent.com/618054/152301040-af65300b-0337-4268-a818-b06817614b6a.png)

**Device**
Your device model, OS version, device locale/language and Fritter version

Sony Experia 5 ii
Android 11
English
Fritter version v2.16.3+202201232 from f-droid

**Comment by kajdo** [comment]
You are not alone. Also happens for me ... Also unchecked all replies in groups

**Comment by JanikWie** [comment]
Hi there. I have the same problem. I noticed that  on my device this bug only exist in groups that are bigger than 33 accounts.

**Comment by jonjomckay** [comment]
This should be fixed in [3ae1fd8](https://github.com/jonjomckay/fritter/commit/3ae1fd8174679803b953c5f2f6e39463fefcbfcc), and will be going out in v2.17.0!
