### ISSUE TITLE
[BUG] Retweets do not show full text

### ISSUE THREAD

**Issue by DAVIDJAND** [jonjomckay/fritter#345]
**Describe the bug**
When viewing a feed, retweets only show a certain number of characters, and often are cutoff with "..."

**To Reproduce**
1. Go to individual user's Twitter feed
2. Click on Tweets or Tweets & Replies
3. See Retweets in feed. An ellipsis appears if character count exceeds 140 characters, but character count includes "RT @username:" and "..."

**Device**
Galaxy A32 5G
Android 11
Fritter version: v2.16.3+20220123

**Comment by jonjomckay** [comment]
@nannadroid could you supply a link to the tweet or profile that reproduces this for you? Also, which version of Fritter are you using? This should only be fixed in the 3.0.0 betas so far.

**Comment by nannadroid** [comment]
> @nannadroid could you supply a link to the tweet or profile that reproduces this for you? Also, which version of Fritter are you using? This should only be fixed in the 3.0.0 betas so far.

Oh ok. I'm using official release, 2.x.x. I joined the beta program just now. But not seeing later versions. Any hints how i can get latest beta versions? Thank you!
