### ISSUE TITLE
[BUG] catastrophic failure: bad guest token

### ISSUE THREAD

**Issue by paulverbeke** [jonjomckay/fritter#346]
Describe the bug
When trying to open a thread or a profile, I've got a catastrophic failure with the message bad guest token

To Reproduce

1. Go on my feed
2. Click either on the username of the tweet or the link to open the thread and replies
3. Black screen with catastrophic failure with the message bad guest token

Device
OnePlus 8T
Android 11
Fritter version: v2.16.3

**Comment by fusionneur** [comment]
Same catastrophic failure is shown when searching

**Comment by fusionneur** [comment]
I cleared app's cache, and then it worked fine

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
