### ISSUE TITLE
[REQ] Preserve scroll state after adding people to groups

### ISSUE THREAD

**Issue by Gabri3l** [jonjomckay/fritter#349]
**Describe the problem that needs solving**
Any time I go on someone's profile from the main feed and add them to a group, if I hit back it brings me back to the top of the timeline instead of where I was before.

**Describe the solution you'd like**
Ideally it would be nice to just resume from where you left off instead of being sent to the top of the timeline every time.

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
