### ISSUE TITLE
[BUG] remove telemetry

### ISSUE THREAD

**Issue by ruta0** [jonjomckay/fritter#354]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
Telemetry `sentry_flutter` found & is currently being used as a logging tool.

Why does it need to be there for a privacy centric client app?

```dart
// main.dart

var sentryOptions = SentryOptions(dsn: 'https://d29f676b4a1d4a21bbad5896841d89bf@o856922.ingest.sentry.io/5820282');
  sentryOptions.sendDefaultPii = false;
  sentryOptions.attachStacktrace = true;

  var sentryClient = SentryClient(sentryOptions);
  var sentryHub = Hub(sentryOptions);
  sentryHub.bindClient(sentryClient);
```

**To Reproduce**
n/a

**Screenshots**
n/a

**Device**
Pixel 6, Android 12, en, v2.16.3

**Comment by Aga-C** [comment]
The app description says: "Fritter uses Sentry for opt-in error reporting, which is not enabled by default."

**Comment by kamzil** [comment]
This feature seems to be opt-out, not opt-in, as it is enabled by default. At least the checkbox is checked when you install the app.

**Comment by jonjomckay** [comment]
The usage of Sentry is opt-in. It's not enabled by default - when the first error happens, the user is presented with a dialog asking whether they want to turn it on or not, or even submit the error once without enabling Sentry permanently.
