### ISSUE TITLE
[BUG] NoSuchMethodError when loading replies for some tweets

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#356]
**Describe the bug**
Some tweets cannot be opened (or show fine on the Feed tab but cannot be opened to see the replies) due to throwing a `NoSuchMethodError` error.

Examples:
https://twitter.com/nexta_tv/status/1497771921823383554
https://twitter.com/nexta_tv/status/1497721398248316928
https://twitter.com/IAPonomarenko/status/1497708482455351315
https://twitter.com/KyivIndependent/status/1498150543939629059

What these all seem to have in common is at least one of the replies were deleted or the reply's corresponding account was banned.

**To Reproduce**
1. Go to Feed tab and click an affected tweet or open Twitter link via Fritter
2. See error

**Screenshots**
<img src="https://user-images.githubusercontent.com/13911156/155933884-e434b6a1-cadb-47dd-a17a-b1cb51ebce78.png" width="400" />

**Device**
Model: Samsung Galaxy S9+
OS: Android 10
Language: English
Fritter Version: v2.16.3+202201232

**Comment by geominorai** [comment]
This error also occurs for age-restricted tweets when not logged in.

**Comment by igorskyflyer** [comment]
+1, happens to me as well
