### ISSUE TITLE
[BUG] Choppy scrolling

### ISSUE THREAD

**Issue by silverwings15** [jonjomckay/fritter#360]
**Describe the bug**
Scrolling is choppy on a 90hz+ panel due to presumably running at 60fps.

**To Reproduce**
1. Install Fritter from F-Droid
2. Search for accounts and subscribe to them
3. Scroll through the feed
4. Animation/scroll movement is choppy and lacks smoothness

**Device**
Pixel 6, fritter v 2.16.3

**Comment by hejops** [comment]
This is especially noticeable when selecting the "go to top" button. Maybe the scroll animation could be disabled for this action.

**Comment by silverwings15** [comment]
> overall scrolling feels like 30 fps

it's been fixed in the 3.0 beta

**Comment by silverwings15** [comment]
really? i don't have the same experience on a 90hz screen. maybe i'm just used to it by now, but gonna reopen the issue for you anyway

**Comment by C8opmBM** [comment]
the choppiness is still there.
android 13, latest beta.

**Comment by jonjomckay** [comment]
I'm at the mercy of Flutter here unfortunately. The debug version now runs at >60fps most of the time on my 120fps device, so I'll close this as fixed, at least as much as I can in Fritter.
