### ISSUE TITLE
[REQ] or [BUG]? No way to launch fritter from url

### ISSUE THREAD

**Issue by ballo** [jonjomckay/fritter#365]
**Describe the problem that needs solving**
If I do a web search and there's a redirect to Twitter, it doesn't launch the app. If I copy the URL I can't just paste it in the app. NewPipe recognizes when I'm posting a YouTube link or ID and so at least there's a cumbersome work-around. I see no solution with fritter. 
**Describe the solution you'd like**
fritter should have a smarter search at the very least. I don't see how anybody uses this app with a browser as it is currently. I'm not going to open Twitter then search for stuff.

**Comment by ballo** [comment]
Update: found a workaround but stand by my previous stance that the search ought to be more intelligent like NewPipe

**Comment by numeropi** [comment]
I can still prove that this still not working... When using nitter and if I have actividated in its android settings that it should collect links from twitter.com  , etc... (those that appear suggested...), it won't change the screeen, for example when clicking on the following link:

https://twitter.com/i/spaces/1yNGaYgjvvnGj

**Comment by jonjomckay** [comment]
Fritter does support opening Twitter links directly - to both tweets and profiles directly. Please supply a link to a Twitter resources that Fritter does support, but that doesn't work, and I'll check it out.

You might want to check that Fritter is set as the default app for Twitter links on your device, as it's possible another app has priority (e.g. your browser).
