### ISSUE TITLE
[BUG] all feed prioritizes some subscriptions

### ISSUE THREAD

**Issue by ch-sander** [jonjomckay/fritter#368]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
The feed for all tweets will show the most recent tweets in the correct chronological order across all subscriptions but for tweets older than two hours it will show only tweets of the most recently added subscriptions...

**To Reproduce**
3. See error

**Screenshots**

**Device**
Your device model, OS version, device locale/language and Fritter version.

**Comment by corentinfuret** [comment]
I can confirm this issue on 2.16.3. However, instead of "older than two hours" it seems to me that only the twenty first tweets are in correct order.

**Comment by jonjomckay** [comment]
I think this may be fixed now in the latest development build. Are you able to confirm? You can download it from GitHub Actions above.

**Comment by corentinfuret** [comment]
Yes, the issue disappeared several months ago.

**Comment by jonjomckay** [comment]
Thanks. Closing this issue then!

**Comment by ch-sander** [comment]
I have to say though that some tweets happen to appear twice in the all feed. But that's not a problem for me.

Thanks for the fix anyway
