### ISSUE TITLE
Feature Request: Import/Export

### ISSUE THREAD

**Issue by Cstrrider** [jonjomckay/fritter#37]
It would be helpful to be able to export and  reimport a list of all subscribed twitter handles for changing devices and factory resets.

**Comment by jonjomckay** [comment]
Fully agree - I'm working on this already!

**Comment by peterflock** [comment]
As an extension to this the support for Android Backup Service can be added (http://android-doc.github.io/google/backup/index.html)

LineageOS added SeedVault so it is no longer Google dependent.
