### ISSUE TITLE
[REQ] no way to search tweets as default

### ISSUE THREAD

**Issue by ballo** [jonjomckay/fritter#370]
**Describe the problem that needs solving**
A clear description of what the problem is. E.g. I'm always frustrated when [...]
I will never ever use the search feature to search for people. I will only search for tweets.
**Describe the solution you'd like**
A clear description of what you want to happen.
I would like to either flip the default search so it searches for tweets first by default, or eliminate searching for users.

**Comment by ballo** [comment]
It's especially frustrating not being able to go back to the previous search after clicking on a tweet. The entire search resets. The only work-around is to use Twitter's search using a browser. Easily the most annoying part of this app.

**Comment by jonjomckay** [comment]
Closing as the tweet search functionality has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
