### ISSUE TITLE
[REQ] ability to copy tweet URL 

### ISSUE THREAD

**Issue by ballo** [jonjomckay/fritter#373]
So I can bookmark a tweet (useless feature), I can share a tweet URL, but I can't copy it. So in order to get the tweet URL I have to share it to another app then copy it.
Do I have that right?

**Comment by jonjomckay** [comment]
No, you can choose "Share tweet link" on the menu on every tweet, which will show the Android share menu, and in the header should be a large "Copy" button.

If your ROM or vendor Android doesn't show this button, I think it's something to raise to them - Fritter adheres to Android's guidelines for this stuff, and I don't intend to step outside of those bounds 🙂
