### ISSUE TITLE
[REQ] Ability to add an account to a list without showing up in main feed

### ISSUE THREAD

**Issue by 5rxp** [jonjomckay/fritter#375]
I'm a huge fan of Fritter, and have a minor feature request! 

**Describe the problem that needs solving**
I have a list which I add accounts to, that I like to have in one place, but really don't like seeing their tweets unless I am viewing that list. When I "Add to list", I don't want to "Subscribe", and have the content show up in my home feed.

**Describe the solution you'd like**
I can imagine a few solutions, depending on what is less work:

1. Add a "mute" option to the account after you follow it. Toggling mute would hide the tweets from the home feed.
2. Add an option to a list, which would be something like "Exclude list from home feed", which would exclude all the accounts in that list from the home feed.
3. When you "Unsubscribe" from an account, don't remove it from the lists that it was added to. This could be completed with an alert confirming if the user wants to remove the account from all lists, or just "All". This would preserve the current functionality, maintaining backwards compatibility.

If somebody could point me in the right direction, I wouldn't be opposed to giving it a shot myself, but I have not done android specific development before. Seems like it's a pretty straight forward feature, just adding a property (muted) to each account stored, and filtering on that property on the home page!

Thank you all for your hard work!

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
