### ISSUE TITLE
[BUG] Timestamps/Dates not showing for some older tweets

### ISSUE THREAD

**Issue by ValuePrivacy** [jonjomckay/fritter#376]
When viewing older tweets (Specifically @TheRoaringKitty) I cannot view times nor dates when each specific tweet was posted. Currently showing how many months, minutes, or hours ago instead of specifics. I like the current view for tweets less than an hour old.

**Comment by jonjomckay** [comment]
Please could you supply a link to a tweet where the dates aren't displaying? Thank you!

**Comment by ValuePrivacy** [comment]
https://twitter.com/TheRoaringKitty/status/1406054126555967495

Older tweets appear as "about a year ago" instead of the published date such as the standard twitter app offers. Unsure if possible to implement the date along with the time posted.

**Comment by bovergaauw** [comment]
Clicking on the date to get the exact time and date of a tweet would be very useful

**Comment by jonjomckay** [comment]
This is now supported as part of the v3.0.0 betas.
