### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by conradaaron21** [jonjomckay/fritter#378]
Hello, I have BlackBerry Passport supporting Android 4.3 and lower. I downloaded the last 5 versions of fritter but when I installed and clicked the app, it does not work. I can even see any content of the app. Could you please make an update for this stuation?

**Comment by h4xor666** [comment]
Pretty sure this isn't a bug, you're just using an extremely outdated version of Android.

**Comment by conradaaron21** [comment]
But fritter's last version supports for Android. 4.1

**Comment by jonjomckay** [comment]
Fritter does intend to support all the way back to Android 4.1, but I think this may be an issue with the emulation layer used by BB OS 10. I would guess that it probably doesn't support Flutter, which Fritter uses. Probably something to do with the graphics stack.

There's not much I can do unfortunately, as I don't have a BlackBerry Passport to test on. You might find some help on the [Crackberry forums](https://forums.crackberry.com/) though!
