### ISSUE TITLE
Can't load profile

### ISSUE THREAD

**Issue by EfraMP** [jonjomckay/fritter#38]
I can't load some profiles. It appears "Something went wrong loading the profile! The error was: type 'Null' is not a subtype of type 'Map<String, dynamic>'"

**Comment by jonjomckay** [comment]
Can you confirm if this is still broken in the most recent version (2.2.0)? If it is still not working, please could you supply a profile that reproduces the issue?

**Comment by EfraMP** [comment]
Ok, I've just updated and it's working. Thanks :)
