### ISSUE TITLE
[BUG] New subscriptions include all replies in home feed

### ISSUE THREAD

**Issue by Skirmisher** [jonjomckay/fritter#380]
Since sometime in the last month or so, any users I make new subscriptions to in Fritter have all of their tweets appear in Fritter's home feed, including replies (to any user). The posts are organized by thread like in the per-user view, instead of showing only the thread roots. This is very distracting and makes it hard to effectively navigate the timeline, even with only a couple users exhibiting the issue.

Users I'm already subscribed to aren't affected, and retain the original behavior.

**Device**
Cosmo Communicator
Android 9.1 (English US)
Fritter 2.1.3 (F-Droid)

**Comment by rck** [comment]
I'm just here to second that. I can not confirm that it was better once as I started to use the app today and all my users are new. But what I can confirm is that I see all replies in the feed, which unfortunately makes the TL pretty unusable.

Fritter v2.16.3+202201232 from Froid

**Comment by toas-koas** [comment]
I have the same issue
Android 12 19-20220712-dos-taimen
Pixel 2XL
Version 2.16.3

**Comment by jonjomckay** [comment]
This should now be fixed in 3.0.0-beta1, as the "Include replies" and "Include retweets" group options now work consistently.

Please re-open if this is still an issue for you, along with a reproducing user. Thanks!
