### ISSUE TITLE
[REQ] Search tweet within user

### ISSUE THREAD

**Issue by Gottarocket** [jonjomckay/fritter#387]
**Describe the problem that needs solving**
A clear description of what the problem is. E.g. I'm always frustrated when [...]

Cant search a tweet within a user profile only global search is possible

**Describe the solution you'd like**
A clear description of what you want to happen.

Option to select global or user to restrict where search needs to be done or have a filter to filter by new popular or date

**Comment by jonjomckay** [comment]
Closing as tweet searching has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
