### ISSUE TITLE
[REQ] 

### ISSUE THREAD

**Issue by maro7777** [jonjomckay/fritter#388]
**Describe the problem that needs solving**
A clear description of what the problem is. E.g. 

I can not seperatly select subscription in defferent groups. Only in the Feed group. 

**Describe the solution you'd like**
Allow entering a subscription group and be able to manage the subscription group wise.

**Comment by jonjomckay** [comment]
I'm not sure I understand - sorry!

There are three ways you can add a user to a group:

1. On their profile page, by tapping the icon at the top right of the header
2. On the subscriptions tab, by tapping the icon on the right hand side of the user
3. By holding and pressing down on a group

Please let me know if this does not address your issue 🙂

**Comment by maro7777** [comment]
What i mean is: option 3 when I press long at a group. I want to see only the subscriptions of that group. And be able to move subscribtons between groups. I hope I am understandable. I love Fritter thank u very much for ur great work. 

On August 22, 2022 5:50:21 PM GMT+02:00, Jonjo McKay ***@***.***> wrote:
>I'm not sure I understand - sorry!
>
>
>
>There are three ways you can add a user to a group:
>
>
>
>1. On their profile page, by tapping the icon at the top right of the header
>
>2. On the subscriptions tab, by tapping the icon on the right hand side of the user
>
>3. By holding and pressing down on a group
>
>
>
>Please let me know if this does not address your issue 🙂 >
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/jonjomckay/fritter/issues/388#issuecomment-1222546817
>
>You are receiving this because you authored the thread.
>
>
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
