### ISSUE TITLE
[BUG] Video Controls Cutoff

### ISSUE THREAD

**Issue by locuturus** [jonjomckay/fritter#389]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
On my Pixel 4a the video player controls are partially cropped out and very difficult to interact with. Note the effect is minor at regular screen density and becomes more apparent as DPI is increased.

**To Reproduce**
1. Increase density on phone
2. Play any video in Fritter
3. See error as in screenshot

**Screenshots**
![462DPI_20220428-133737](https://user-images.githubusercontent.com/19397973/165842572-d3b49696-3a8f-4f09-bf4a-ee3007c5cc2b.png)
![500DPI_20220428-134036](https://user-images.githubusercontent.com/19397973/165842588-d273c072-03e2-4d9d-b388-c17df46e17bf.png)
![626DPI_20220428-131323](https://user-images.githubusercontent.com/19397973/165842608-c63e405b-26ea-4e58-83e5-33473f429daa.png)

**Device**
Pixel 4a, OS Android 12 QPR3 Beta 2, USA/English, Fritter 2.16.3

**Comment by jonjomckay** [comment]
This should be fixed in the latest version (3.0.0-beta1). Please re-open with a comment and screenshot if it's still broken for you. Thanks!

**Comment by locuturus** [comment]
I confirm this bug is fixed for the main feed, and for the groups feed. However this or a similar bug is present for videos viewed directly from a user's page. The 3-dot menu is lowered from the top and the scrub bar isn't visible at all:
![Screenshot_20220822-094206](https://user-images.githubusercontent.com/19397973/185975032-73a21b1e-6d2b-4fc3-90fa-cd606fe9d45a.png)
