### ISSUE TITLE
Replies are Messed Up

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#39]
Check out the screenshots.

App Version: 2.2.0

![Elon Twitter](https://user-images.githubusercontent.com/83120103/116285305-a25a3880-a7ab-11eb-8b39-1ccd7c04c320.png)
![Elon Fritter](https://user-images.githubusercontent.com/83120103/116285328-a7b78300-a7ab-11eb-80b6-8933ae477e22.png)

**Comment by jonjomckay** [comment]
@alphanerdgen this looks like it was fixed in v2.2.1 - can you confirm? I've noticed that I did manage to stop replies from being shown in the profile screen when I added support for cards, so I've pushed a fix for that in 3ebe1564815ce60b6dcd4134a816bb5a19028500.

**Comment by alphanerdgen** [comment]
@jonjomckay It's fixed. Checked in 2.2.2. Thank you.
