### ISSUE TITLE
[REQ] Allow certain groups/subscriptions to be excluded from the main/all feed

### ISSUE THREAD

**Issue by TurtleIdiot** [jonjomckay/fritter#394]
**The problem I am facing**
There is currently no way to prevent certain subscriptions or groups from being displayed in the main feed. For example, I am subscribed to an account that posts a LOT and it takes up most of my main feed. This could also help users that are subscribed to NSFW accounts and would not want inappropriate content being the first thing shown when opening the app

**A possible solution**
It would be very helpful to have an "Exclude from main feed" checkbox when making or editing a subscription group that doesn't show the specified accounts in the main feed but the tweets are still available if the user clicks on the group in the subscriptions tab

Thanks

**Comment by moocow1452** [comment]
An alternate fix could be to set your default feed to something other than all.

**Comment by TurtleIdiot** [comment]
> An alternate fix could be to set your default feed to something other than all.

How do I set that? I've tried that before and I can't find the option for it anywhere

**Comment by moocow1452** [comment]
Was offering that as an alternative change, not as a fix that already existed, sorry.

**Comment by TurtleIdiot** [comment]
Ah, makes sense. No worries!

**Comment by jonjomckay** [comment]
Sorry, I don't think this will be supported - the All feed is explicitly that: a feed containing all of your subscriptions. The supported way to achieve what you'd like to do is to create a group containing the subscriptions you'd like to see. Adding this will be essentially duplicating functionality, whereas I think maybe promoting groups to the same level as the All feed (i.e. @moocow1452's suggestion) is probably a better way forward.

I wasn't too keen on having the All feed on the home screen, for reasons like this, but it was a highly requested feature 😕
