### ISSUE TITLE
[REQ] Force Downloading of .MP4 Instead of .M3U8

### ISSUE THREAD

**Issue by OkyDooky** [jonjomckay/fritter#395]
Currently, some video streams will only offer .m3u8 files instead of .mp4 to download, while Twidere automatically downloads all videos (and even .gifs) as .mp4.

This prevents me from downloading certain videos from within the app and have to use some other solution. There doesn't seem to be a consistent pattern, that I can see, between which videos get downloaded as .mp4 and which ones get downloaded as .m3u8, so I do not know what needs to be addressed.

Thanks for the app, either way. It really addresses a lot of problems and allows me to browse Twitter content while using Tor (via Orbot).

**Comment by jonjomckay** [comment]
Please could you supply a link to a tweet that downloads as an `m3u8` file instead of an `mp4`? Thank you!

**Comment by OkyDooky** [comment]
> Please could you supply a link to a tweet that downloads as an `m3u8` file instead of an `mp4`? Thank you!

Yes, sure! I have several differrent ones I found in my bookmarks (put them there due to this bug).
https://twitter.com/cwt_news/status/1556769267630104578
https://twitter.com/FrenEugenics/status/1555212926029631491
https://twitter.com/DunkinDAOnuts/status/1534518103459102721

Hope this helps!

**Comment by jonjomckay** [comment]
@OkyDooky thank you! This will be fixed and released in the next beta, or the final v3.0.0 release

**Comment by OkyDooky** [comment]
@jonjomckay Thanks! Looking forward to it.
