### ISSUE TITLE
[REQ] Keep display on while media is playing

### ISSUE THREAD

**Issue by Mrnofish** [jonjomckay/fritter#398]
**Describe the problem that needs solving**
When viewing e.g. a video that lasts longer than the screen time-out, without interacting with the device, the display will turn off and media will be paused.

**Describe the solution you'd like**
IMO the screen should stay on while media is playing.

**Comment by Mrnofish** [comment]
The videos posted on Twitter are generally short clips, so it might make sense to keep the display on for a while after it's done playing, in case the user wants to watch it again. Indefinitely though? That might be too much.

For reference, NewPipe keeps the screen on while it's playing but appears to revert to the system-set screen time-out as soon as it's done playing.

**Comment by Myzel394** [comment]
@Mrnofish I think NewPipe's style could fit to Fritter too! @jonjomckay what do you think?

**Comment by Myzel394** [comment]
@Mrnofish Do you mind sharing an account / a tweet with media so that I can test it? I don't use Twitter myself

**Comment by Mrnofish** [comment]
https://twitter.com/ThePeripheralPV/status/1567653644736286721

I hope you're a William Gibson fan ^___^ Seriously, at 1m50s this was the longest Twitter clip I could find digging through my feed.
