### ISSUE TITLE
Can't Open Links

### ISSUE THREAD

**Issue by backme7** [jonjomckay/fritter#4]
When clicking on a link in a tweet it just refreshes the page

**Comment by jonjomckay** [comment]
I've also noticed this. Clicking links to other profiles should now be working in the latest development version, but clicking links to external sites will take a bit more work to implement... I'll look into it and report back soon.

**Comment by jonjomckay** [comment]
This looks like it's working fine in the latest development build. @backme7 can you confirm, and I'll close?

**Comment by backme7** [comment]
Now the links are not even clickable.
![Uploading ca7579cb-2711-4f5a-938b-ef73690a94fb.jpg…]()

**Comment by backme7** [comment]
Now the links are not even clickable.

**Comment by backme7** [comment]
![ca7579cb-2711-4f5a-938b-ef73690a94fb](https://user-images.githubusercontent.com/79310789/115354735-c3cf8900-a1db-11eb-8639-87e0eb2a542c.jpg)

**Comment by jonjomckay** [comment]
Sorry, I totally misread this one (and forgot about my own reply 🙄).

I've finally implemented support for mentions, hashtags and external URLs, and merged it into the `master` branch. You can download the latest APK from [here](https://github.com/jonjomckay/fritter/actions) if you'd like to validate it before the next release!

**Comment by backme7** [comment]
Solved.
P.S. you are doing a great job.
