### ISSUE TITLE
Sharing content

### ISSUE THREAD

**Issue by login22rvp** [jonjomckay/fritter#40]
Is there any way to share the tweet or content through link from fritter app?

**Comment by jonjomckay** [comment]
Not currently, but I'll add it to the roadmap!

**Comment by login22rvp** [comment]
wow...Thank you :)

**Comment by login22rvp** [comment]
Just used the feature...Bro you are too awesome. 
I created my account on github and commented for the 1st time, and you included tht feature. I am feeling so nice. 

Thank you once again and superb work
