### ISSUE TITLE
[REQ] Add the same search/sort options for #search queries as the official website/client offers: Top, latest, persons, pictures, videos

### ISSUE THREAD

**Issue by tokariu** [jonjomckay/fritter#400]
if you currently search a #hashtag, or click on some #trends, Fritter only shows the "Top" search results for this #search-query. That means only a little portion (top voted and preselected from twitter) of a #search-query is shown to the Fritter user. 90% of the other results are hidden by default this way.

twitter officially supports multiple search options, namely: Top, Latest, Persona, Pictures, Videos.

As a user of Fritter we have no options to select from, f.i. "latest" as a search option ("latest" equals the url-parameter "&f=live" in a twitter search url. like: [Latest](https://twitter.com/search?q=%23weather&f=live) VS [Top](https://twitter.com/search?q=%23weather ) 

I find myself often angry not having enough results with this default option and therefor being forced to use the official website/client to have full search results and options. It is especially annoying if you want to find the latest tweets for a #hashtag and Fritter only shows the most popular but also older ones.

Fritter should have the same search options as the official Twitter website.

**Comment by ballo** [comment]
A decent search tool would make having a separate username search superfluous (which it kinda is already)

**Comment by fbobraga** [comment]
a way to refresh search results suffice my needs...

**Comment by locuturus** [comment]
+1
I actually thought hashtag search was entirely broken until I read this issue.

**Comment by fbobraga** [comment]
Well, I don't use twitter any more: Musk made it unusable for me

**Comment by locuturus** [comment]
I hear you there, but for the moment there are still a few use cases where Twitter is better for me than the alternatives. I'm using a little of everything now.

**Comment by jonjomckay** [comment]
Closing as tweet searching has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
