### ISSUE TITLE
[BUG] Pinned tweets are not shown

### ISSUE THREAD

**Issue by jcperil** [jonjomckay/fritter#410]
**Describe the bug**
The fact that a tweet is pinned in a Twitter account isn't reflected on Fritter. 

**To Reproduce**
1. Open the Twitter handle of [AppleTV+](https://twitter.com/AppleTVPlus) in any web browser.
2. Open the Twitter handle of [AppleTV+](https://twitter.com/AppleTVPlus) in Fritter.
3. Observation: Pinned tweets from Twitter are not reflected in Fritter.

**Screenshots**
Screenshots taken at the time of creating this issue:

From Twitter:
![twitter](https://user-images.githubusercontent.com/89805719/178066348-d864c938-1d0b-4c80-8d78-a7b31d92df31.jpg)

From Fritter:
![fritter](https://user-images.githubusercontent.com/89805719/178066346-c997dcf6-7b4c-4beb-a0e9-619656262682.jpg)

**Device**
- OS version: Android 12
- Fritter version: 2.16.3

**Comment by jonjomckay** [comment]
This looks like it's caused by a change on Twitter's side, where they no longer return the pinned tweets in the API response. I think there's an alternative way I can fetch that data though...

**Comment by jcperil** [comment]
It does not work.

**Device specifications:**
Device: Android 12 (stock)
App version: 3.0.0-beta3


**Attachments:**
Twitter screenshot below:
![twitter_hbo](https://user-images.githubusercontent.com/89805719/189478427-efb6d7e0-bf9f-4a3e-bbe3-802070eed492.png)

Fritter screenshot below:
![fritter_hbo](https://user-images.githubusercontent.com/89805719/189478433-397ea256-8dfe-41f3-bd9e-9fdfd6716cf0.png)
