### ISSUE TITLE
[Question] does this app only support android 12 onwards?

### ISSUE THREAD

**Issue by yant0** [jonjomckay/fritter#422]
Im stuck on android 11 version and i tried to install the newer ci builds but it says target android : 12. Is it possible to support older versions of android too? I really like this app it would be a bummer if i need a newer phone to install it.

**Comment by jonjomckay** [comment]
Fritter supports Android versions all the way back to 4.1 (Jelly Bean). I think what you might be seeing is that it's build using the SDK for Android 12 (`targetSdkVersion`), but the one to tell the earliest supported version is `minSdkVersion` 🙂 

@BigDogg99 you can download the latest CI build by going to the [Actions](https://github.com/jonjomckay/fritter/actions) tab, selecting the latest build, and at the bottom will be a table containing the CI outputs - one of them will be the APK.
