### ISSUE TITLE
[REQ] Remember feed positions when switching tabs

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#434]
**Describe the problem that needs solving**

All feeds currently return to the top when switching between navigation tabs (Tweets, Tweets &  Replies, Media, etc.), which is undesirable since we may have scrolled far down when reading and wish to return to it quickly.

It is also easy to accidentally switch tabs due to the sensitivity of the left and right swipe gestures. Swiping through an image gallery in the post can also accidentally trigger this. 

**Describe the solution you'd like**

Cache posts and remember scroll positions when switching between tabs so we can quickly return to them. If updating the feed is an issue, add a drag down from the top of the screen gesture to trigger a manual refresh, if new posts cannot be simply added to the top of the feed and have scroll positions be recalculated.

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
