### ISSUE TITLE
Inconsistency with Update suggestion

### ISSUE THREAD

**Issue by GameOverFlowChart** [jonjomckay/fritter#441]
The app suggests to update the app through f-droid but the new version on f-droid is marked as beta. The message to the user is therefore ambiguous. If an update is recommended than it shouldn't be marked as beta if an update is not recommended than the app shouldn't suggest to update it through f-droid.
I did not fill the form for bug requests because the form wants from me to make sure that I'm using the latest version, but I won't install software marked as beta.

**Comment by jonjomckay** [comment]
This should be user-fixable with the changes added in [33d77a8](https://github.com/jonjomckay/fritter/commit/33d77a8332e878c8a8576ebc899387aa033ef9b8). It allows the user to ignore a specific update version. You can also disable the update check on the settings screen, if you prefer!
