### ISSUE TITLE
Accent colour should not apply when using the true black theme option

### ISSUE THREAD

**Issue by Gottarocket** [jonjomckay/fritter#442]
**Describe the problem that needs solving**
Option to change accent color on Top. Aqua doesn't look good under true black IMO. Better allow users to customize

**Describe the solution you'd like**
Option in settings to choose accent color

**Comment by Tachi107** [comment]
Yeah, I've just upgraded to the beta and I really don't like the acqua top bar in the true black team. I really miss the minimalist 2.x look.

**Comment by jonjomckay** [comment]
Oops - this is actually a bug. When running in with the true black option, there should be no app bar colour. I'll fix this up for the next release.

In the meantime, @franck-x has added support for choosing a different theme, which I've just merged in, and should be available in the next CI build.
