### ISSUE TITLE
[REQ] Manage shown tabs in home screen

### ISSUE THREAD

**Issue by jcperil** [jonjomckay/fritter#443]
**Device specifications**
* Android: 12
* App version: 3.0.0-beta1

**Describe the problem that needs solving**
Currently, all tabs are shown on the home screen: Feeds, Subscriptions, Groups, Trending and Saved

![tabs](https://user-images.githubusercontent.com/89805719/187019944-0431aca2-000a-4e4a-8bfe-c6ed9678a187.jpg)

**Describe the solution you'd like**
An additional action `Manage tabs` in Settings that allows user to either tick or untick tabs depending on what they would like to see on their home screen.

**Comment by jonjomckay** [comment]
This is now available in the latest CI build, and will go out in the next version!
