### ISSUE TITLE
[REQ] Pull gesture to close full screen view of a picture

### ISSUE THREAD

**Issue by jcperil** [jonjomckay/fritter#444]
**Describe the problem that needs solving**
When you click on a picture, it opens in full screen view and the only way to close it is by pressing the back button.

**Describe the solution you'd like**
Allow pull up or pull down gesture (or both) to close the full screen view of a picture.

**Comment by geominorai** [comment]
The implementation causes this bug in the feed in beta3. It is attempting to "close" the feed instead of the image viewer:

https://user-images.githubusercontent.com/13911156/189459489-4fd7eeee-68f2-4cec-b73f-02194605f4a1.mp4

**Comment by geominorai** [comment]
The implementation also only works for images but not videos.

**Comment by jcperil** [comment]
Thank you for implementing this. Although, it requires some pressure to close. Please see the attachment below:

https://user-images.githubusercontent.com/89805719/189477525-6cc4ac6f-e843-42e7-86cd-cb35c756c405.mp4

The fullscreen view closes only if I pull with a lot of force. If I try to pull the image with a little force, it simply dances and comes back to the original position.
Is there way to reduce the minimum force required to close?

**Comment by jcperil** [comment]
> The implementation causes this bug in the feed in beta3. It is attempting to "close" the feed instead of a non-existent image viewer:
> 
>  Screen_Recording_20220909-164017_Fritter_1.mp4

I cannot reproduce this issue. I am on Android 12 and app version 3.0.0-beta3.

**Comment by geominorai** [comment]
> > The implementation causes this bug in the feed in beta3. It is attempting to "close" the feed instead of a non-existent image viewer:
> > 
> >  Screen_Recording_20220909-164017_Fritter_1.mp4
> 
> I cannot reproduce this issue. I am on Android 12 and app version 3.0.0-beta3.

It's also happening on the main feed on issue #477.

**Comment by jonjomckay** [comment]
It looks like this was caused by 82795fd62b959d66c05ccdebf35a429d942a871d accidentally being included inside an unrelated PR. I've fixed it up and pushed the change, so this should be working in the latest CI build, and the next beta build.
