### ISSUE TITLE
[REQ] better handle update notifications

### ISSUE THREAD

**Issue by grrrrr** [jonjomckay/fritter#446]
**Describe the problem that needs solving**

With the upgrade notification from v2.16.3 to v3.0.0-beta1, the notification there was a release would appear every time that you open fritter.

**Describe the solution you'd like**

The notification should appear once and not be shown again,  or alternatively allow the user to manually acknowledge it not be shown again.

**Comment by jonjomckay** [comment]
This is now solved, with an option on notifications to "Ignore this version". You can also disable the update check on the settings screen. The fix will go out in the next beta release, and v3.0.0 final.
