### ISSUE TITLE
Change the Way Retweets are Shown

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#45]
Instead of the ugly, intrusive blue strip, you could simply display a small, colored RT icon somewhere.

Or, you could show an RT the way you show a Quote Tweet (using a different color, obviously).

**Comment by jonjomckay** [comment]
I'll have a think about this. I wanted to make it clear that a tweet is a retweet, hence the blue vertical rule.

Out of curiosity, could you send a screenshot of how it displays on your device? It's quite thin and unintrusive on mine 😅

**Comment by alphanerdgen** [comment]
@jonjomckay Here's the screenshot. I find it thick. The tweet gets pushed to the right as as result. How about removing the RT icon and reducing the thickness? I think users will know that the blue strip indicates an RT.

![RT](https://user-images.githubusercontent.com/83120103/116990424-b5f82880-acf0-11eb-912a-d8a3e1065612.png)

**Comment by alphanerdgen** [comment]
@jonjomckay Suggestion: How about adding a thin, coloured stroke to all the edges of a card in order to denote a retweet? Minimal and unobtrusive.

**Comment by jonjomckay** [comment]
Thanks all - I've finally made the retweet indicator thinner, and it'll go out in v2.9.0!
