### ISSUE TITLE
[UI/UX Improvement] Errors are hard to get rid off (add swipe left?)

### ISSUE THREAD

**Issue by peterflock** [jonjomckay/fritter#46]
I am using Tor (orbot with netguard) and the requests sometimes fails.

Error cannot be swiped away (left or right).  After some trying I was able to get rid of it by somehow swiping it down.

I think best is to make it be swipable to the left/right.

Version: https://github.com/jonjomckay/fritter/releases/tag/v2.2.1 apk from github

![image](https://user-images.githubusercontent.com/78184669/116601420-0438b080-a91a-11eb-87ee-e2e02c68291e.png)

**Comment by jonjomckay** [comment]
Currently, I'm just displaying these errors using the standard [snackbar](https://material.io/components/snackbars) widget, so I don't have the option to change the swipe behaviour.

Maybe there's a better way to display them. Do you have an example of an app that does this better?

**Comment by peterflock** [comment]
> using the standard snackbar widget

Maybe it is somehow android version dependent. But I was not able to swipe it left/right. Maybe the `[X]` can help to solve the issue.

-----------
One additional idea is to keep the log of errors available in the menu (maybe under settings or some "Advanced" sub-menu) so one can go back to them a check what happened / debug.

**Comment by jonjomckay** [comment]
Errors are no longer displayed as snackbars, so closing this. Please open a new issue if you have feedback on the current error widgets!
