### ISSUE TITLE
[BUG] v3.0.0-beta1 does not show what groups specific accounts are added to

### ISSUE THREAD

**Issue by grrrrr** [jonjomckay/fritter#462]
**Describe the bug**
In the subscription tab, if you select the "person" icon to the right of a subscription and select add groups it does not show what groups it is already added to.     

This makes it hard to see: 
1. What group the subscription is already in
2. Remove a subscription from a group

**To Reproduce**
1. Start Fritter
3. Select `Subscription` tab
4. Click on the person icon to the right of a subscription
5. Select `Add to group`
6. Add the subscription to any existing group (you can additionally go to the group tab to verify subscription is now in the group
7. click on the person icon to the right of the subscription you just added to a group
8. subscription to group is not shown - check boxes are empty for any group they were added to

**Device**

Android 10

**Comment by jonjomckay** [comment]
Fixed in #463
