### ISSUE TITLE
[BUG] Media doesn't work in 3.0.0 beta 2.

### ISSUE THREAD

**Issue by THElegend5** [jonjomckay/fritter#470]
**Describe the bug**
Any type of media shows "Oops something went wrong."

**To Reproduce**
1. Open the app.
2. Navigate to a tweet which has some kind of media.

**Screenshots**
![Screenshot_2022-09-05-02-26-35-806_com.jonjomckay.fritter.png](https://user-images.githubusercontent.com/63903377/188333160-a16f00e2-e6a6-4041-afff-1ec67de964b9.png)

**Device**
Redmi Note 9 Pro Max
Android 11
English

**Comment by iamtalhaasghar** [comment]
The issue still persists in beta 3 release.

**Comment by iamtalhaasghar** [comment]
The issue still persists in beta 3 release.

![Screenshot_20220905-121809_Fritter](https://user-images.githubusercontent.com/46928648/188391261-b45b5f71-670d-492b-add0-f6567dc2c181.png)

**Comment by THElegend5** [comment]
> The issue still persists in beta 3 release.
> 
> ![Screenshot_20220905-121809_Fritter](https://user-images.githubusercontent.com/46928648/188391261-b45b5f71-670d-492b-add0-f6567dc2c181.png)
> 
> 
> Edit: this happens only with tweets under trending tab.

It seems to have been fixed for me, where are you getting the error.
