### ISSUE TITLE
[BUG] Leaving a clicked-on tweet or image reloads trending or search page returning it to the top

### ISSUE THREAD

**Issue by amka985** [jonjomckay/fritter#473]
When you search for a term or click on a trending term, it is not possible to click on an image or tweet and then return to where you were as you can on people's profiles of the home tab. Instead the whole search term is reloaded, sometimes returning you to the search person tab or back to the top of the search term tab. This is quite frustrating and doesn't allow you to view information on a topic or people's opinions easily.

1. Go to search and search a term
2. Scroll down and click on an image or tweet
3. Leave tweet or image
4. Term is reloaded and takes you to the top of the list of tweets on it 

Looking through term and finding a tweet:
![Screenshot_20220906-133953](https://user-images.githubusercontent.com/112728177/188637614-b4552a1e-5b25-44b0-a887-96eec28fc928.png)

Clicking on the tweet:
![Screenshot_20220906-133956](https://user-images.githubusercontent.com/112728177/188637542-94797422-d794-40c6-b5f8-81d57f71bf07.png)

Leaving the tweet sends you here:
![Screenshot_20220906-134001](https://user-images.githubusercontent.com/112728177/188637513-ae88b485-1db6-455f-a8c9-42f5c2ffb234.png)

Google Pixel 4a, Android 13, UK, English, v3.0.0-beta1+20220820

**Comment by Aga-C** [comment]
The newest version is v3.0.0-beta3, and there this issue is solved.

**Comment by amka985** [comment]
> The newest version is v3.0.0-beta3, and there this issue is solved.

Yes thank you. I didn't see the latest update. Thank you for your work.
