### ISSUE TITLE
Twitter search results fail ( BUG)

### ISSUE THREAD

**Issue by rsssxd** [jonjomckay/fritter#476]
https://user-images.githubusercontent.com/60405617/188744914-2e5061db-dba9-4bcd-8cdd-8d0f3691a94e.mp4

**Comment by rsssxd** [comment]
Actions new versions

**Comment by Aga-C** [comment]
It's the same as in https://github.com/jonjomckay/fritter/issues/472.

**Comment by jonjomckay** [comment]
Closing as a duplicate of #472.
