### ISSUE TITLE
[REQ] shadowbox view for feed and profile pages

### ISSUE THREAD

**Issue by 404b** [jonjomckay/fritter#478]
**Describe the problem that needs solving**
clicking a tweet media take one to a one way jailed view, which is counter intuitive compared to lot of viewing models

**Describe the solution you'd like**
when on feed selecting a tweet meia should load it into a sliding shadow box from tweets meida already loaded next/before and lazy load next ones. Thus one don't need to swipe back a tweet to go back to feed. They can just slide onto the next. Same goes for profile pages. It saves a lot of clicks and interactions while sorting thru feed.

fritter is refreshing app than official bs

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
