### ISSUE TITLE
[REQ] Do not open the keyboard when tapping on a trend 

### ISSUE THREAD

**Issue by VovoloGames** [jonjomckay/fritter#483]
**Describe the problem that needs solving**
Currently when you tap a trend it focuses on the text field and opens the androids keyboard. This is a bit annoying.

**Describe the solution you'd like**
Add an option to disable this.

**Comment by jonjomckay** [comment]
This is fixed in the latest v3.0.0-beta3. Please re-open if this is still an issue!
