### ISSUE TITLE
[BUG] Tabs Disappear After Searching

### ISSUE THREAD

**Issue by cohesive-flight** [jonjomckay/fritter#489]
**Describe the bug**
The tabs at the bottom on pages such as feed, groups, subs, etc. disappear after using the search function.

**To Reproduce**
I've not been able to reproduce this, but it went something like this:
1. Search anything
2. Interact with your results
3. Go back
4. Tabs are gone

**Screenshots**

https://user-images.githubusercontent.com/106868963/189475775-60fd5add-9c87-4327-8613-798803c09673.mp4

**Device**
Model: Samsung S10+
OS: Android 12 (LineageOS 19)
Language: English
Fritter Version: 3.0.0-beta3

**Comment by Aga-C** [comment]
I've found steps to reproduce it every time, but it's not related to search:
1. Go to tab, that has enough content to scroll.
2. Scroll down, so tabs are no longer visible.
3. Switch to tab, that hasn't enough content to scroll. Do it by swiping left/right.

If there's no possibility to scroll, I'm unable to get tabs back. I have to go back to another tab that has more content, and not just by scrolling up, but first by scrolling down and later scrolling up.

https://user-images.githubusercontent.com/85929121/189518090-2a569414-ee54-46d7-97aa-6df30e12aad1.mp4

**Comment by geominorai** [comment]
This also happens to the tabs in settings (along with the horrendous stretching):

https://user-images.githubusercontent.com/13911156/189557109-1e0b6b05-653a-41c5-80fa-91dd9e07e831.mp4
