### ISSUE TITLE
Pinch Zoom Pics

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#49]
Cannot do that in version 2.2.1.

**Comment by RequestPrivacy** [comment]
I would love if the zoom is steady, so that you can remove your fingers after the zoom without the picture minimizing back to the original size.

**Comment by jonjomckay** [comment]
Fixed in the upcoming v2.6.0 (#103). Closing this issue as the PR didn't close it for some reason 😅
