### ISSUE TITLE
[BUG] Unable to scroll sideways when image is zoomed

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#492]
**Describe the bug**

When zoomed in on an image, dragging to start scrolling the image does not work when dragging horizontally.

This may be caused by swipe gestures for switching between multiple images in the same post (even when there is only one image). These should be disabled when zooming. 

This stretchy effect is also nauseating.

**To Reproduce**
1. Go to an image post
2. Pinch to zoom in
3. Attempt to scroll sideways by dragging horizontally

**Screenshots**

https://user-images.githubusercontent.com/13911156/189501507-cd832dd1-0eab-4b09-a6d8-a30e7ba11469.mp4

**Device**

Model: Samsung Galaxy S9+
OS: Android 10
Language: English
Fritter Version: v3.0.0-beta3

**Comment by Solarunit** [comment]
I just wanted to create this issue! Same problem here.

**Comment by jonjomckay** [comment]
I think I fixed this today in 976ca5175e3b2eeab075e2bf8751ca06d3f133f3. Would you mind trying the latest CI build to confirm?

**Comment by geominorai** [comment]
Thanks, I can confirm this fixed in the latest CI build but the zoomed image scrolls unusually slowly compared to normal image viewers image gallery apps or even web browsers, but this might be better filed as another issue.
