### ISSUE TITLE
Wrong App Version?

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#50]
Even after installing the latest version (2.2.1) from Github, the app version remains 2.2.0. Please investigate and let me know if the problem is at my end or not.

**Comment by WindHun7er** [comment]
It's not only at your end. I think it's just a little mistake in the version tag ^^
In 2b221f8, the version has not been changed correctly ;)

**Comment by jonjomckay** [comment]
Whoops, sorry about that. I've just fixed and retagged v2.2.1
