### ISSUE TITLE
[BUG] "subscribe"/"unsubscribe" button barely visible

### ISSUE THREAD

**Issue by genodeftest** [jonjomckay/fritter#505]
**Describe the bug**
With the update to Fritter 3.0.0-beta3 (compared to 3.0.0-beta1 and previous 2.x versions), the button to (un-)subscribe has very little contrast to the background. This makes it hard to spot the button at all. At first, I thought, the button was entirely gone, but if you look very carefully, you can still spot it.

**To Reproduce**
1. Open any twitter account

**Screenshots**
![Screenshot_20220915-003307](https://user-images.githubusercontent.com/934401/190275001-c2c4ffe8-6046-41b8-b0a1-92f436490831.png)

**Device**
Fritter 3.0.0-beta3 from F-Droid on Android 11 (Fairphone 4)

**Comment by geominorai** [comment]
Looks like the fix for #433 on the dark theme shifted the issue over to the light theme instead.
