### ISSUE TITLE
Issue with Sorting Subscriptions

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#51]
I'm following over 25 accounts. The name of only one those accounts begins with an underscore. And I suspect it's this _hipster which is messing up the alphabetical order of the subscriptions.

For whatever reason, Fritter has placed _hipster after WhatsApp and not after the account whose name starts with Z. Following _hipster is a new list of accounts in alphabetical order starting all the way from A to Z. These are different accounts, not duplicates.

Please investigate. 

App Version: 2.2.1

**Comment by alphanerdgen** [comment]
@jonjomckay Please reopen this issue as it hasn't been fixed properly.

The old problem which I mentioned above still exists even after unfollowing that account which started with an underscore. See screenshot:

![Accounts](https://user-images.githubusercontent.com/83120103/116992353-7da61980-acf3-11eb-8f6b-b3d79cebba53.png)

**Comment by jonjomckay** [comment]
@alphanerdgen which field are you sorting the subscriptions by (the icons at the top right)? I tested each with a mix of lowercase and uppercase names and it sorted fine on my device!

**Comment by alphanerdgen** [comment]
@jonjomckay Maybe that's the reason why the app has put 'MetalHammer' between W and Z accounts. Not under Subscriptions, though. There, it's sorted correctly according to its username. But when I long-press on any group, I find it above Z letter accounts. metalhammer is its name, MetalHammer, the username. Please follow it and see if you also face the same issue.

Note: Accounts are sorted according to Name by default in the list that opens after one long-presses on a group.

**Comment by alphanerdgen** [comment]
@jonjomckay One more example. This is a screenshot of the accounts that show up when you long-press a Group.

![Sorting New](https://user-images.githubusercontent.com/83120103/117164090-ee2b6400-ade1-11eb-8b1a-388e1afcf9e4.png)

**Comment by nannadroid** [comment]
Hello, this problem still exists. I'm using android 11, fritter beta 3.0.0.
I have two usernames that have '_' in the name; both start with letter 'k'. Only one of them is sorted correctly. The other one is always shown at the end. I refreshed, re-sorted but nothing helped.
