### ISSUE TITLE
[BUG] Replies do not load for retweets 

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#517]
**Describe the bug**

Opening retweeted posts show no replies, even if the actual post does when opened directly via the original poster's profile. 

**To Reproduce**

1. Go to a profile feed with a retweet post with replies (has a total) 
2. Click on the post
3. See no replies

**Device**

Model: Samsung Galaxy S9+
OS: Android 10
Language: English
Fritter Version: v3.0.0-beta3+20220904 CI 9acbab6

**Comment by Aga-C** [comment]
I confirm that's in v3.0.0-beta4 too.

**Comment by AndiDink00x** [comment]
Also confirmed by me in v3.0.0-beta4

**Comment by Aga-C** [comment]
It's fixed in [v3.0.0-beta5](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta5).
