### ISSUE TITLE
[REQ] Add an option to hide retweets of a specific profile

### ISSUE THREAD

**Issue by Darkempire78** [jonjomckay/fritter#519]
**Describe the problem that needs solving**
There is an option on Twitter to hide retweets of a specific profile. It is very useful when an account retweets a lot.

**Describe the solution you'd like**
Add an option to hide retween of a specific profile as Tweeter do

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
