### ISSUE TITLE
[BUG] Settings Page Scroll Behavior

### ISSUE THREAD

**Issue by johann-gambol** [jonjomckay/fritter#522]
**Describe the bug**
If you scroll the settings page, the Title-Bar and  Navigation-Bar at the bottom disappear suddenly.

**To Reproduce**
1. Go to 'Settings'
2. scroll 
3. See error

**video**
![settings_scroll_bug](https://user-images.githubusercontent.com/66774071/192090345-9a8e916a-8aec-42cc-ada1-0c5b785e49d2.gif)

**Device**
device model: Pixel 4 [emulator] 
OS version: Android 11
Fritter version: commit 04e7a85c5285ebc3820c9715fc3f0c4bfe95543b

**Comment by jonjomckay** [comment]
I think you may be running an older version - there should also be an extra option on that screen for the non-confirmation bias setting. This should be fixed, as I've removed the library that was causing it. Please could you confirm on the latest version?

**Comment by Aga-C** [comment]
It works properly for me in the latest version.

**Comment by johann-gambol** [comment]
You're right! My bad - my fork was not up to date. Something went wrong with git :)
