### ISSUE TITLE
[REQ] no addiction 

### ISSUE THREAD

**Issue by NSTAdventure** [jonjomckay/fritter#524]
**Describe the problem that needs solving**
Trending, homepage, counts of view like and such of any platform included twitter is usually addictive due to news and such it's really annoying me as a user

**Describe the solution you'd like**
At least add option to disable those

**Comment by NSTAdventure** [comment]
I am not done yet and i gonna edit this issues soon

**Comment by jonjomckay** [comment]
You can already remove the Trending and Feed pages in the latest beta versions (along with any other page).

Removing the interaction counts is being tracked in #234.

Closing this for now, unless I've missed something!

**Comment by NSTAdventure** [comment]
Bruh 🤦

Sorry i didn't know this issues was posted before
🙏😥
