### ISSUE TITLE
Some features To add

### ISSUE THREAD

**Issue by TheOnlyIsmail** [jonjomckay/fritter#53]
First of all Thanks For doing this app, Newpipe is one of my Favorite apps cuz I like The idea That you can subscribe To channels and add playlists locally, Without Tracking any data from users, And You doing this for twitter, Thats a great work! The app Is great so far, but it's lack of some features That I hope You adding them To the app, like:

-Add bookmarks.

-Add what's new like Newpipe.

- Be able To share a tweet

- Be able To save a photos

- Be able To view quoted retweets

And I have Some problems with The app :
-It doesn't show the recent Tweets immediately

- Some tweets appear and some don't! And that's pretty strange.

Finally, Thanks for this app again and sorry If there some grammar mistakes English is Not my native language.

**Comment by alphanerdgen** [comment]
@TheOnlyIsmail If you installed the app from F-Droid then you're probably using an older version. Download the latest version from Github and install that instead. 

It's now possible to view quoted tweets. Also, the option to save media has already been asked for before (#27).

**Comment by TheOnlyIsmail** [comment]
> @TheOnlyIsmail If you installed the app from F-Droid then you're probably using an older version. Download the latest version from Github and install that instead. 
> 
> It's now possible to view quoted tweets. Also, the option to save media has already been asked for before (#27).

I'm running The latest version which is 2.2.2
And Still I can't view the quoted tweets.

**Comment by jonjomckay** [comment]
@TheOnlyIsmail thank you for the kind words - I'm glad you're enjoying Fritter! 

In regards to your feature requests:

* I merged in support for bookmarking/saving tweets just yesterday (#43), so it should be in the next major release (v2.3.0), which is coming soon. In the meantime, you can download the latest development version from [GitHub Actions](https://github.com/jonjomckay/fritter/actions) if you'd like to test it out. 
* A feed (similar to What's New) is being tracked in #23 
* I merged in support for sharing tweets yesterday too (#52)
* Saving photos is tracked in #27 as @alphanerdgen mentioned

About the bugs - are you able to link to some tweets or accounts that are not displaying properly? It'd help a lot to narrow down the problem 😅

**Comment by TheOnlyIsmail** [comment]
> @TheOnlyIsmail thank you for the kind words - I'm glad you're enjoying Fritter! 
> 
> In regards to your feature requests:
> 
> * I merged in support for bookmarking/saving tweets just yesterday (#43), so it should be in the next major release (v2.3.0), which is coming soon. In the meantime, you can download the latest development version from [GitHub Actions](https://github.com/jonjomckay/fritter/actions) if you'd like to test it out. 
> * A feed (similar to What's New) is being tracked in #23 
> * I merged in support for sharing tweets yesterday too (#52)
> * Saving photos is tracked in #27 as @alphanerdgen mentioned
> 
> About the bugs - are you able to link to some tweets or accounts that are not displaying properly? It'd help a lot to narrow down the problem 😅 
> 

I will trying to explain it by an example :
I created a group and name it " Football "
And added to it some accounts 

![IMG_20210504_195836.jpg](https://user-images.githubusercontent.com/57960792/117050033-2e70e080-ad15-11eb-93c0-c0b44ba3f0dc.jpg)

Lets focus on This account 

`Jordan@la_notice_`

When I open this group ( football ) It should display The latest Tweets of the accounts in this group, Right ? But it didn't

So The last tweet of the account ( Jordan )
Is 5 hours ago, in the group.

![IMG_20210504_200605.jpg](https://user-images.githubusercontent.com/57960792/117050832-1cdc0880-ad16-11eb-815c-8bdef76896f2.jpg)


But when I open his account It display That his last Tweet was 12 minutes ago ! 

![IMG_20210504_200640.jpg](https://user-images.githubusercontent.com/57960792/117051030-5e6cb380-ad16-11eb-887d-86b3d56f7d5e.jpg)

So my question is why the group didn't display The latest tweets of the accounts ?

I hope I did explain it Well.


One last thing I hope you consider it, when I open any account It displays his tweets and his mentions or replies which make it too messy ( at least for me ) could You make it to display The Tweets only ? Or at lasts has option to choose.
Thanks again

**Comment by alphanerdgen** [comment]
@TheOnlyIsmail 

> could You make it to display The Tweets only ? Or at least has option to choose.

Already asked for, buddy. See #24 and give it a 👍.

**Comment by jonjomckay** [comment]
It looks like everything in this issue has been fixed or implemented, except for the missing tweets - that's being tracked in #68 (an issue with using the Twitter Search API), so closing. Please open a new issue if something else isn't working for you!
