### ISSUE TITLE
[REQ] New release?

### ISSUE THREAD

**Issue by Myzel394** [jonjomckay/fritter#530]
I noticed that the last release has been released in January and a lot of improvements / features have been added since then. When will there be a new release?

**Comment by jonjomckay** [comment]
I've recently been releasing beta versions regularly. You can find them here: https://github.com/jonjomckay/fritter/releases

They're also available on F-Droid and Google Play under the beta programme.

I'll release a final version for v3.0.0 once I'm happy with the stability.
