### ISSUE TITLE
[BUG] "Error: The translation API failed to translate the tweet"

### ISSUE THREAD

**Issue by oliver-cfc** [jonjomckay/fritter#539]
**Describe the bug**
If I hit the translate icon, I get the following error message every time:  "Error: The translation API failed to translate the tweet"

**To Reproduce**
1. Go to 'Trending'
2. Hit the "+" button and select "Panama" (but it fails for every one I try)
3. Pick any trending topic in a foreign language
4. Hit the translate icon

**Screenshots**
![Screenshot_20221007-110418](https://user-images.githubusercontent.com/1508844/194585912-f7730d8b-b172-4f5b-ab5f-980180979e4d.png)

**Device**
LG K51/mdh30xlm, Android 11, Fritter 3.0.0-beta4+20220923

**Comment by jonjomckay** [comment]
This should now be fixed in 07743af4fe11a501a118cf12ddcf81b4bdabd63a.
