### ISSUE TITLE
[BUG] NO Push-Notification

### ISSUE THREAD

**Issue by Salva-C** [jonjomckay/fritter#546]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
I don't know if this app gives push notifications, but I don't get any.

**Device**
SM-G975F/DS, Android 12, Germany DBT,
Fritter version 3.0.0-Beta3

**Comment by jonjomckay** [comment]
Fritter does not currently give out any push notifications. Please follow #110 for updates.
