### ISSUE TITLE
[BUG] Translations no longer supported

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#547]
**Describe the bug**

Starting around today languages previously translatable (e.g. Japanese or Korean) stopped working. This may be due to a change to the translations API.

**To Reproduce**

1. Go to any non-English post, e.g. https://twitter.com/OPcom_info/status/1583654521036627969 or https://twitter.com/ieul_7/status/1577878285123407872
2. Click on translate 
3. See error

**Screenshots**

<img src="https://user-images.githubusercontent.com/13911156/197724548-fad7384c-08e3-476d-aca7-166597a7b200.png" width=250 /> <img src="https://user-images.githubusercontent.com/13911156/197726144-a2afa5ca-4cd4-474f-964c-47a990524ff0.png" width=250 />

**Device**

Model: Samsung Galaxy S9+
OS: Android 10
Language: English
Fritter Version: v3.0.0-beta4

**Comment by RickyM7** [comment]
Same for pt-BR language.

**Comment by geominorai** [comment]
This seems to have fixed itself yesterday, so it may have been a revert of the API change.
