### ISSUE TITLE
[REQ] Push beta4 to F-Droid

### ISSUE THREAD

**Issue by ZJaume** [jonjomckay/fritter#548]
Can beta4 code be pushed to F-Droid or it is responsability of the F-Droid team to pull the changes? F-Droid build status says highest metadata version is beta3.

**Comment by fbobraga** [comment]
yeap (I'm waiting https://github.com/jonjomckay/fritter/issues/229 :P)

**Comment by ZJaume** [comment]
beta5 installed from F-Droid. Thanks!
