### ISSUE TITLE
[REQ] Remember last post, so you can keep swiping up to see newer tweets

### ISSUE THREAD

**Issue by ForceConstant** [jonjomckay/fritter#552]
Currently, fritter loads newest tweets when opening, and places newest tweet at the top. I would like it when I open app, that the currently viewed tweet was the last one I was looking at, and all the newer ones above that.

**Comment by AlDollaz** [comment]
Would make this app absolutely perfect.

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
