### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Erictheplague** [jonjomckay/fritter#564]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

Currently using fritter version from the Google play store 
**Describe the bug**
Consistent notification of reporting bug and bug is persistent

**To Reproduce**
1. Go to feed
2. Click on refresh 
3. See error

**Screenshots**
![Screenshot_20221115-022511.png](https://user-images.githubusercontent.com/81354428/201803968-f2ecd527-5d36-47bc-a663-df991c1c3a66.png)

![Screenshot_20221115-022442.png](https://user-images.githubusercontent.com/81354428/201804053-4fb680c3-207f-48e3-8b67-7cc36167f928.png)

**Device**
Samsung Galaxy S7, Android 9

**Comment by Aga-C** [comment]
The latest version is [v3.0.0-beta4](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta4), and only available to download on GitHub.

**Comment by jonjomckay** [comment]
To add - the error in your first screenshot is because that profile is not public. You're only able to import subscriptions from a public Twitter account, unfortunately.
