### ISSUE TITLE
push v3.0.0-beta4 to f-droid

### ISSUE THREAD

**Issue by grrrrr** [jonjomckay/fritter#566]
Currently f-droid is only aware of [v3.0.0-beta3](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.jonjomckay.fritter.yml),  it would be useful to get this updated to beta4 is made available on f-droid

**Comment by jonjomckay** [comment]
Sorry about this. I've just opened a PR for v3.0.0-beta5 to get into F-Droid!
