### ISSUE TITLE
[BUG] Picture flick blanks whole screen while scrolling

### ISSUE THREAD

**Issue by kachapman** [jonjomckay/fritter#568]
This is a bug that appeared after an update a month or so ago.
If I'm scrolling and flick an image to quickly, the image moves up and away like it's being discarded and the whole app goes black and unusable.

I have to restart the app multiple times per session as a result.

**Comment by jonjomckay** [comment]
This duplicates #444, and has been fixed in the latest v3.0.0-beta4!
