### ISSUE TITLE
[Feature request] Persistent timeline position

### ISSUE THREAD

**Issue by ghost** [jonjomckay/fritter#57]
I would be nice if I reopen a group or subscription that I continue in that timeline where I left off last time, so that I can scroll up and read discussions in order, and don't miss anything.

**Comment by paulverbeke** [comment]
Yes really important to know what the last unreads are after a refresh, even in the main feed

**Comment by Friptick** [comment]
Even better: **this plus reversible order, so you can consume the timeline in chronological order**, as God intended.

Should be merged with #183

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
