### ISSUE TITLE
[BUG] Showing repeating tweets on feed

### ISSUE THREAD

**Issue by BASETO** [jonjomckay/fritter#571]
When scrolling on the feed, it shows repeating tweets. For example when I scroll down through tweets 1 hour old, then 2 hours old, then 3 hours hold, it then shows 1 hours old tweets then 2 hour old tweets and so on, instead of showing 4 hour old tweets. It eventually shows 4 hour old tweets but it takes you through the loop several times. 1-2-3-1-2-3-1-2-3-4-5-6-3-4-5-6

Version 2.16.3
Android 12

**Comment by jonjomckay** [comment]
Does this still happen in the latest beta version (v3.0.0-beta4?)

**Comment by hauptkern** [comment]
It doesn't appear to repeat feed tweets for me on v3.0.0-beta4

**Comment by jonjomckay** [comment]
Closing as this appears to be fixed in the v3.0.0 betas.
