### ISSUE TITLE
[REQ]  Faster loading time of feed

### ISSUE THREAD

**Issue by powerfulsaber** [jonjomckay/fritter#572]
**Describe the problem that needs solving**
I'm following about 250 people, so it takes a while to load my feed (10 seconds). While it's loading, the app becomes very laggy, and sometimes this lag carries over for a few seconds after it's done loading. Also, when a twitter link is clicked and Fritter opens, the extreme lag takes place despite only one tweet bring displayed (feed is probably being loaded in the background).

**Describe the solution you'd like**
Much shorter loading time, no extreme lag when loading, and prevent feed from loading in background when opening a twitter link.
Maybe also prevent feed from refreshing when clicked on, and only do so if the refresh button is clicked, or after some time passed since the previous refresh.

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
