### ISSUE TITLE
[REQ] Media only tab/filter

### ISSUE THREAD

**Issue by Thang1191** [jonjomckay/fritter#574]
Yknow sometimes I just want to look at media and media only. No more talks, horrible takes or just words in general. 

I would like to request a media only filter that only shows tweets with media attached or a separate gallery like tab. 

Harpy's implementation is a really good way of doing it.
![Screenshot_20221128_122240_harpy free](https://user-images.githubusercontent.com/101631480/204200157-010f40ce-7008-4986-a90b-3c4e737a660b.jpg)

**Comment by Aga-C** [comment]
It's the same as https://github.com/jonjomckay/fritter/issues/330.

**Comment by Thang1191** [comment]
> It's the same as #330.
Oh shoot, sorry i didnt look far enough
