### ISSUE TITLE
[BUG] Clicking on any trending topic leads to "catastrophic failure"

### ISSUE THREAD

**Issue by poubellier** [jonjomckay/fritter#580]
**Describe the bug**
When i click on any trend, a "catastrophic failure" screen appears. 

**To Reproduce**
1. Go to the trending tab
2. Click on any trending topic
3. See error

**Screenshots**
![Screenshot_20221201-200740](https://user-images.githubusercontent.com/98282479/205139479-fe26db09-d29a-4e3d-b9b3-580ce8d2226e.png)

**Device**
Pixel 7 running latest GrapheneOS stable version.
Fritter version: problem appears on both 3.0.0 beta 4 and 3.0.0 beta 5 (v3.0.0-beta5+20221126).

**Comment by Rmn382** [comment]
there is already an open issue for that bug

https://github.com/jonjomckay/fritter/issues/577

**Comment by jonjomckay** [comment]
This should be fixed now. Sorry for the delay - I haven't been able to spend as much time as I'd like on Fritter recently :slightly_frowning_face:

**Comment by poubellier** [comment]
It's ok, this is not you main activity that's the base of FOSS to have to wait a bit!
This will ne fixed in the next update or it's somehow server si de?
