### ISSUE TITLE
Could not contact  Twitter [BUG]

### ISSUE THREAD

**Issue by rsssxd** [jonjomckay/fritter#582]
![Screenshot_20221206-221422_Fritter](https://user-images.githubusercontent.com/60405617/206001712-334870b4-10d2-483a-8d3d-70784ba00c00.png)
Device: Xiiaomi Mi 9T
Android 13
Fritter v3.0.0-beta5+20221126

**Comment by jcperil** [comment]
I am facing the same issue. Fritter does not load anything.
