### ISSUE TITLE
[REQ] Content Displayed

### ISSUE THREAD

**Issue by ghost** [jonjomckay/fritter#583]
**Describe the problem that needs solving**
1) Retweets and likes of users you follow do not show up in the feed
2) Responses of people you follow to other user tweets shows but it never shows the actual tweet being responded to)
3) No login account

**Describe the solution you'd like**
1) Include some likes and retweets of users you follow in your feed content (or a checkbox option)
2) When a user you follow responds to a tweet, display the actual tweet being responded to above the response tweet
3) Is it possible to add an account feature like the reddit Infinity android app?

Thank you, love the app!

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
