### ISSUE TITLE
[REQ] Customize default feed group

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#588]
**Describe the problem that needs solving**

Performance issues may arise when opening the app or feed from excessively large number of subscriptions, such as UI freezing and persistent stutters. (Original issue this was reported in seems to have been deleted.) 

**Describe the solution you'd like**

This sounds like an unavoidable problem since having that many subscriptions would mean loading the feed hammers the server, so the delayed response may be server-side.

Even if the app loads subscriptions in chunks with threads separate from the UI, the delayed responses from the server would make feed items pop in suddenly, since it is sorted by time the items in a subscription may come earlier in the feed despite loading later than previous items.

It may be better to implement a way to choose one or more feed groups to include in the default feed aside from just the default _all subscriptions_.

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
