### ISSUE TITLE
Add to Group Shortcut

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#59]
The current method becomes tedious if you're following a lot of accounts so a quicker method is needed.

How about long-pressing on the Follow icon to bring up an 'Add to a Group' option? 

Or a separate 'Add to a Group' icon next to the Follow icon?

**Comment by TheOnlyIsmail** [comment]
Agreed

**Comment by jonjomckay** [comment]
Looks like this was duplicated in #114 (0462aa5cc316d201377a7958b82ac0b9f9bf07b9), but it's implemented now - I've extended the subscribe button to allow selecting one or more groups to add the user to. It'll work whether you're already subscribed to the user or not. It'll go out in v2.9.0!
