### ISSUE TITLE
[BUG] Blank screen on first app startup 

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#592]
**Describe the bug**

App UI does not load on first launch, but works on subsequent launches, suggesting a possibly incomplete initialization. 

**To Reproduce**

(Warning: Backup data before testing!)

1. Go to Android app settings
2. Stop app
3. Clear all app data
4. Open app
3. See error

**Screenshots**

<img src="https://user-images.githubusercontent.com/13911156/206998821-8aebc619-270c-4bf1-bd0f-06a31e360d37.png" width =250 />

**Device**

Model: Samsung Galaxy S9+
OS: Android 10
Language: English
Fritter Version: v3.0.0-beta6+300000772
CI Build: 7203e69

**Comment by jonjomckay** [comment]
This should be fixed by aeeb6b60496eaf65fa03b829ae2a23ca2e84eb15. The database migration wasn't idempotent and failed sometimes.

**Comment by jonjomckay** [comment]
Scratch that - fixed in 4ed00ce!

**Comment by geominorai** [comment]
Nice.
