### ISSUE TITLE
[BUG] NoSuchMethodError when opening a deleted profile from subscriptions

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#593]
**Describe the bug**

Opening a deleted profile from the Subscriptions tab throws a runtime error. 

**To Reproduce**

1. Go to Subscriptions
2. Click on a deleted profile
3. See error

**Screenshots**

<img src="https://user-images.githubusercontent.com/13911156/207003684-8d52206f-8dc7-4457-a6d6-8ce6370b3b54.png" />

**Device**

Model: Samsung Galaxy S9+
OS: Android 10
Language: English
Fritter Version: v3.0.0-beta6+300000772
CI Build: 7203e69

**Comment by jonjomckay** [comment]
I think this is fixed, but I can't find a deleted account to test with! Please let me know if it's still broken.

**Comment by geominorai** [comment]
Thanks, it worked: 

<img src="https://user-images.githubusercontent.com/13911156/209345703-fe844c0e-4df6-42ff-a453-6d945a87b449.png" width=200 />
