### ISSUE TITLE
Media Size Selection Not Functioning[BUG]

### ISSUE THREAD

**Issue by rjm831** [jonjomckay/fritter#596]
Using a stock Samsung Tab A-7 with Android 11 and v2.16.4 Fritter.  The Media Size selection in the settings is totally non-functional regardless of setting:  the screen will always show media in full-size {note I keep my tablet in landscape mode};  This bug has been constant since I began using Fritter (two versions ago).

**Comment by Aga-C** [comment]
The current version is: [v3.0.0-beta6](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta6).

**Comment by rjm831** [comment]
My apologies for my incorrect post.  The setting is working properly.  The problem I'm having is the size of the images displayed on posts with media:  in landscape mode (only in landscape mode) the pictures on most posts are so large they take up 2.5 full screens {i.e., not possible to view the full image in one screen - can only be seen by scrolling it}.  So I guess this boils down to a feature request of being able to reduce a post's image size somehow (or the entire post itself perhaps).  And thank you for continuing development of this app - it's really fills a public need.

**Comment by rjm831** [comment]
My apologies for my incorrect post.  The setting is working properly.  The problem I'm having is the size of the images displayed on posts with media:  in landscape mode (only in landscape mode) the pictures on most posts are so large they take up 2.5 full screens {i.e., not possible to view the full image in one screen - can only be seen by scrolling it}.  So I guess this boils down to a feature request of being able to reduce a post's image size somehow (or the entire post itself perhaps).  And thank you for continuing development of this app - it's really fills a public need.

**Comment by rjm831** [comment]
My apologies for my incorrect post.  The setting is working properly.  The problem I'm having is the size of the images displayed on posts with media:  in landscape mode (only in landscape mode) the pictures on most posts are so large they take up 2.5 full screens {i.e., not possible to view the full image in one screen - can only be seen by scrolling it}.  So I guess this boils down to a feature request of being able to reduce a post's image size somehow (or the entire post itself perhaps).  And thank you for continuing development of this app - it's really fills a public need.

**Comment by rjm831** [comment]
My apologies for my incorrect post.  The setting is working properly.  The problem I'm having is the size of the images displayed on posts with media:  in landscape mode (only in landscape mode) the pictures on most posts are so large they take up 2.5 full screens {i.e., not possible to view the full image in one screen - can only be seen by scrolling it}.  So I guess this boils down to a feature request of being able to reduce a post's image size somehow (or the entire post itself perhaps).  And thank you for continuing development of this app - it's really fills a public need.

**Comment by rjm831** [comment]
My apologies for my incorrect post.  The setting is working properly.  The problem I'm having is the size of the images displayed on posts with media:  in landscape mode (only in landscape mode) the pictures on most posts are so large they take up 2.5 full screens {i.e., not possible to view the full image in one screen - can only be seen by scrolling it}.  So I guess this boils down to a feature request of being able to reduce a post's image size somehow (or the entire post itself perhaps).  And thank you for continuing development of this app - it's really fills a public need.

**Comment by rjm831** [comment]
My apologies for my incorrect post.  The setting is working properly.  The problem I'm having is the size of the images displayed on posts with media:  in landscape mode (only in landscape mode) the pictures on most posts are so large they take up 2.5 full screens {i.e., not possible to view the full image in one screen - can only be seen by scrolling it}.  So I guess this boils down to a feature request of being able to reduce a post's image size somehow (or the entire post itself perhaps).  And thank you for continuing development of this app - it's really fills a public need.

**Comment by jonjomckay** [comment]
No worries! Feel free to track #101, which appears to be what you're asking for
