### ISSUE TITLE
[BUG] whenever scrolling on images, the app is closing intermittently 

### ISSUE THREAD

**Issue by phanib91** [jonjomckay/fritter#606]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
A clear description of what the bug is.

**To Reproduce**
3. See error

**Screenshots**

**Device**
Your device model, OS version, device locale/language and Fritter version. Please supply the actual
version of Fritter being used, and **do not** just write "latest version" or similar, as this
changes constantly.

**Comment by jonjomckay** [comment]
Closing as no details have been filled in
