### ISSUE TITLE
[BUG] tweets not in feed or group

### ISSUE THREAD

**Issue by Mmuk2022** [jonjomckay/fritter#612]
Hardly any tweets show in the main feed or in groups I have setup. 

However if I click on accounts there are recent tweets which I have not seen in my feed. 

In some of my groups where tweets have been made, the error says no tweets in last 7 days. 

I'm using android 13, fully up to date. Have uninstalled fritter, reinstalled and cleared cache. All have failed to remedy the issue. Can you help please?

**Comment by enticedwanderer** [comment]
I am also seeing this behavior on both [v3.0.0-beta6](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta6) manually installed and [v3.0.0-beta5](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta5) through f-droid.

After some troubleshooting (wiping state/settings/cache, restarting and trying to add a few subscriptions) it seems that all NSFW tweets are now excluded from the feed, but visible when opening individual profiles directly. Following a regular tweeter account still shows tweets in the feed, but NSFW accounts do not. I'm on Android 13 as well (CalyxOS specifically) but this likely doesn't matter as I suspect something changed on tweeter API endpoints. All of this used to work until roughly 3-4 days ago.

Happy to help troubleshoot further if you need it, but should be easy to confirm on your side as well.

**Comment by Mmuk2022** [comment]
Interesting. I've done a bit of testing and your assessment seems to be spot on. Hopefully full functionality is restored in future....

**Comment by enticedwanderer** [comment]
I don't think you should close this issue until it is actually resolved with a new release. Maybe just update the title to be more descriptive of the problem i.e. sensitive tweets not displayed in main or group feeds on versions up until at least v3.0.0-beta6.

**Comment by HarriBuh** [comment]
I can confirm, that the issue has been solved (by itsself?). Groups posting are back at working.

**Comment by Mmuk2022** [comment]
So it is
