### ISSUE TITLE
[BUG] Shadowbanned user's tweet does not show on feed

### ISSUE THREAD

**Issue by RoonMoonlight** [jonjomckay/fritter#615]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
When Twitter user is shadowbanned, their tweets does not show up on feed.

Here is example of some shadowbanned user:
[https://hisubway.online/shadowban?username=I_Nozomi_](https://hisubway.online/shadowban?username=I_Nozomi_)

**To Reproduce**
1. Follow users who has been shadowbanned
2. Click on Feed
3. The shadowbanned user's tweet does not appear

**Screenshots**
![Screenshot_20230117_122910_Fritter](https://user-images.githubusercontent.com/25527589/212803593-d98b10f0-757c-4eb5-90ae-98b0b0264c36.jpg)

**Device**
Galaxy S22, One UI 5 (Android 13), en-US, Fritter 3.0.0-beta6

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
