### ISSUE TITLE
[BUG] v2.16.4: Search results: From the reply thread view, back button should go to convo search results. 

### ISSUE THREAD

**Issue by superfawkes** [jonjomckay/fritter#617]
*Version:* 2.16.4, tested in Android 11 & 12. Devices: Oppo Reno Z, Samsung A51.

*Context:*
Searching for a phrase (e.g "Fritter app"), switching to the conversation tab, perusing a response thread and coming back to saarch context.

*Steps:*
1. From home page, click Search
2. enter a phrase (e.g "LineageOS update") - this shows username results for the phrase.
3. switch to conversations (i.e. searching for content)
4. scroll down to a search result with a thread.
5. click messages icon below to look at conversation.
6. press the Android back control - or tap the back arrow on the top left in the app.
7. Note that the page now shows the initial username search results. You will need to redo steps 3 and 4 again to go back to context.

**Comment by jonjomckay** [comment]
This has already ben fixed, and is available in the latest beta version 🙂
