### ISSUE TITLE
[REQ] Mute someone's tweet to not show up on all feeds

### ISSUE THREAD

**Issue by RoonMoonlight** [jonjomckay/fritter#618]
**Describe the problem that needs solving**
On Twitter, there is mute system which hides individual's tweets (Including retweets) when they are muted. I've noticed that this simple feature still haven't been added to Fritter, which made me disappointed.

**Describe the solution you'd like**
Add mute feature, which completely hides muted person's tweet entirely on all feeds.

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
