### ISSUE TITLE
Replies in feed

### ISSUE THREAD

**Issue by nothanks666666** [jonjomckay/fritter#619]
Before this last update there was an option to see peoples tweets and replies, or only see tweets. Now it's permanently in tweets _and_ replies and the feed is cluttered. I don't see an option to change back to tweets only. Was this option removed? 

I'm on version v2.16.4+202212092.

**Comment by c8c8** [comment]
This is my question too. When I installed Fritter, I was asked which I wanted but didn't click the dialogue fast enough and it went away. Now I can't get the question back and there's nothing in settings to set it. I don't want to see people's replies, it's much too chaotic.

**Comment by jonjomckay** [comment]
I haven't removed this option, and it still exists for me in the latest beta version. Please make sure you're on the latest beta - no features have been removed for a long time!

Fritter only asks for an error reporting mode on first startup (well, on first error technically), so I think there may be some confusion here.

**Comment by nothanks666666** [comment]
Thanks for the response. I uninstalled and installed fresh from google playstore. I had installed from f-droid previously. 

The "old" format is back! It has the three dot button at the top of the feed again, that allows for selection of including replies and including retweets. So now my feed is reply-free. So I recommend to all others to do the same, don't forget to export/import your following list.

**Comment by c8c8** [comment]
I uninstalled and reinstalled from the Playstore and have had no such luck unless I'm missing something very obvious.  My original installation was also from the Playstore; I won't sideload a beta from Github.  

![Screenshot_20230124](https://user-images.githubusercontent.com/23272116/214493380-a20827b2-2dc8-498b-af46-999a53dd9ad6.png)

I'd seriously pay money to get rid of replies.  @jonjomckay why is a setting not in the settings?  It doesn't make sense - it's a setting.
