### ISSUE TITLE
New Developer Agreement for the API

### ISSUE THREAD

**Issue by JVT038** [jonjomckay/fritter#620]
Twitter has recently updated its developer agreement terms.
If fritter uses the official Twitter API, fritter will probably be impacted.
It can be read [here](https://developer.twitter.com/en/developer-terms/agreement)

The new update is:
> c) use or access the Licensed Materials to create or attempt to create a substitute or similar service or product to the Twitter Applications;

So they're saying you can no longer use the API to try and create third party clients, as they are a 'substitute or similar service' to the official Twitter application.

**Comment by geominorai** [comment]
Looks like they are also killing off free access to the API starting February 9:

https://twitter.com/TwitterDev/status/1621026986784337922

**Comment by mmkthecoolest** [comment]
I could be wrong on this but I think the dev has since quietly abandoned the project. There have been no commits on the master branch since the development agreement change, and weblate commits have stopped for a while.

**Comment by jonjomckay** [comment]
Fritter doesn't use the official Twitter API, so this change shouldn't affect it.

I've also definitely not abandoned the project! I'm not able to dedicate as much time as I'd like to Fritter, but please be rest assured that it's still very much being maintained 🙂
