### ISSUE TITLE
[REQ] Fritter on Apple Devices

### ISSUE THREAD

**Issue by brunoaintme** [jonjomckay/fritter#628]
Today I installed Fritter for the first time ever on my Android device, and it couldn't be better! I like how it allows me to use Twitter in a more private, less-distracting way. I recently bought an iPhone and in a few days won't have access to my Android device anymore. I wish Fritter was available on iOS, I liked the app so much I was thinking about donating frequently, but it won't be possible if an iOS version don't come out.

**Comment by jonjomckay** [comment]
Please see issue #55. There's a fair bit of discussion on it there - the main points being that I don't have any Apple devices to develop or test on.

I'm definitely open to releasing Fritter for iOS, and have written the application with as much platform-independent code as possible, but there are some hurdles to get over first!
