### ISSUE TITLE
[Question] How to view followers and following when you are on user profile?

### ISSUE THREAD

**Issue by login22rvp** [jonjomckay/fritter#64]
Once i click on the profile after that if i want to view followers and following then it becomes easier to subscribe to the additional profile.

**Comment by iamtalhaasghar** [comment]
Yes, you are right. It would become easier to subscribe to relevant accounts.
Currently clicking on "following" and "followers" buttons on a user's profile does nothing.

**Comment by jonjomckay** [comment]
This is now implemented and will be released in v2.12.0!
