### ISSUE TITLE
[BUG] Giant red error messages 

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#640]
**Describe the bug**

The app occasionally shows a giant red error message in lieu of the usual error panels, such as when having issues contacting Twitter's web server. These seem to be from an old dev or fallback error handler.

Thess rarely appear but a reliable way to show this error message format was found:

**To Reproduce**

1. Create a new subscription group
2. Add a profile to the group that has not posted in a week. 
3. Open the subscription group in the Groups tab. 
4. See error. 

**Screenshots**

<img src="https://user-images.githubusercontent.com/13911156/219236497-db50d1d0-f21f-4add-94c3-01348c500c7e.png" width=200 />

**Device**

Model: Samsung Galaxy S9+
OS: Android 10
Language: English
Fritter Version: v3.0.0-beta6+300000772
CI Build: 46aca26

**Comment by jonjomckay** [comment]
This should no longer be an issue, now that feeds have been removed, so closing.
