### ISSUE TITLE
Add update for Github releases

### ISSUE THREAD

**Issue by TotalCaesar659** [jonjomckay/fritter#65]
Fritter on F-Droid is updating with a delay (there is still [2.2.0](https://f-droid.org/packages/com.jonjomckay.fritter/)).
[NewPipe](https://github.com/TeamNewPipe/NewPipe) has its internal system for updating Github releases.
![0](https://user-images.githubusercontent.com/14265316/117539018-3086b800-b011-11eb-8295-8f27e794ee16.png)
It should be great add this to Fritter if it requires urgent update (e.g. when Twitter changes its work dramatically).

**Comment by jonjomckay** [comment]
Agree - I'm already working on this, and just familiarizing myself with how to run an F-Droid repository. Stay tuned 😄

**Comment by jonjomckay** [comment]
I'm accelerating this, as Twitter just made a breaking change that requires an app update (#77). It happened!
