### ISSUE TITLE
[BUG] Application not functioning

### ISSUE THREAD

**Issue by igorskyflyer** [jonjomckay/fritter#663]
**Describe the bug**
As mentioned in the title, the application stopped functioning since this morning. The feed page does not work - see screenshot - the profiles I'm subscribed to, sometimes open, sometimes don't but almost all of them show 0 media, only text tweets even though the profiles have media.

**To Reproduce**
1. Go to Feed
2. See error

**Screenshots**
![Screenshot_20230421-010141_Fritter](https://user-images.githubusercontent.com/20957750/233506319-33145490-332f-4658-9450-a7b30a14465f.png)

Note: this is the Feed page itself, no profile/status/media open.

**Device**
Device model: Samsung A6+ 2018 (A605FN),
OS version: Android 10,
Device locale/language: English (UK),
Fritter version: 3.0.0-beta6

**Comment by Taijian** [comment]
Over on the nitter bug tracker it says that Twitter just banned unauthenticated access to the endpoint used for search. See here: https://github.com/zedeus/nitter/issues/783#issuecomment-1517046884

**Comment by tadcrazio** [comment]
Same issue here, noticed one nitter instance still working for now. Hopefully there is a way around this.

**Comment by nannadroid** [comment]
Same issue (device: OP6). Though I can browse individual profiles without problem. Can also see media.

**Comment by Akruidenberg** [comment]
Same here

**Comment by perrob70** [comment]
Also here the same issue. Fritter had the last update in December,  looks like it is not maintained anymore

**Comment by arkanoider** [comment]
Same here

**Comment by postacik** [comment]
Same here. Goodbye Fritter  :(

**Comment by Uatschitchun** [comment]
Experienced this right now. Is this able to be solved?
Was using the stable version and also tried latest beta to no avail.

**Comment by Gotchfutchian** [comment]
> Also here the same issue. Fritter had the last update in December, looks like it is not maintained anymore

Categorically false, last commit was on March 15, although that commit and a couple of previous ones were weblate translations.
Either way, dev could just be working on something else right now.

**Comment by ZiXXiV** [comment]
Enough is enough. That was it then. Goodbye Fritter.

**Comment by mmkthecoolest** [comment]
> Also here the same issue. Fritter had the last update in December,  looks like it is not maintained anymore 

Last I checked, the dev said they can't dedicate as much time to Fritter but the project hasn't died. https://github.com/jonjomckay/fritter/issues/620#issuecomment-1415779093

**Comment by HarriBuh** [comment]
Same here. The dev hasn't responded to anything going on here for over a month now. I just hope he didn't get sued or anything like that.

**Comment by HarriBuh** [comment]
Dev needs to either hotfix this asap or his app WILL be dead and useless, this is a sad fact. A non functional app is worth nothing.

**Comment by Uatschitchun** [comment]
Oh dear, what a shit parade swapping over from frustrated twitters.
If this malfunction is caused by changes Twitter has done to it's API, there's nothing a dev can do to keep Twitter from doing so.
As the app was working flawless for the time I'm using it (about a year) and suddenly stops working, I guess it's not caused by a bug in the app.
I'm not able to tell the exact cause or ways to fix it, but blaming a dev for a non working free app caused by API changes makes me sad!

**Comment by igorskyflyer** [comment]
> Oh dear, what a shit parade swapping over from frustrated twitters. If this malfunction is caused by changes Twitter has done to it's API, there's nothing a dev can do to keep Twitter from doing so. As the app was working flawless for the time I'm using it (about a year) and suddenly stops working, I guess it's not caused by a bug in the app. I'm not able to tell the exact cause or ways to fix it, but blaming a dev for a non working free app caused by API changes makes me sad!

Yes, indeed, the dev invested an enormous amount of time in creating and maintaining Fritter so I would definitely not blame the author of Fritter. Even though I haven't done actual tests, my reasoning and professional dev experience tell me this is 100% caused by API changes Twitter did.

Note: I didn't submit this issue for all of you to bash the author, I submitted it so that he can be aware of the new issue.

**Comment by Svetov1d** [comment]
Maybe developer can do some redirect option to nitter to solve twitter restrictions

**Comment by kpg-anon** [comment]
I'd recommend using twitter revanced for now. For anyone else looking to migrate you can get a list of all the accounts you are following with jq:

Settings > Data > Export data > Export subscriptions 

`jq -r '.subscriptions[] | "https://twitter.com/" + .screen_name' fritter-following-2023-04-21.json >> followed_usernames.txt`

**Comment by tadcrazio** [comment]
> 

Correct me if I am wrong but, Revanced is just a modded twitter tho that requires you still to login? The benefit with Fritter at least for me is it doesn't require a login at all. I can just pull it up and see a feed without an account. 

Side note for me anyways. Nitter is great and all, but there is no option to have a real feed. So even using the RSS feeds, still need a feed reader, at which point I'd almost rather just use the "subscription" option that still working in fritter for now to see accounts and can at least navigate the app a but more. 

I don't know enough about mobile development to help with this project unfortunately but seeing  as subscriptions still work, and they appear to be using the GraphQL API as does nitter I'd optimistic it could be patched whether by the dev here or a fork. 
If anyone knows anything similar to getting  the feeds without a login i'd be interested.

**Comment by kpg-anon** [comment]
> Correct me if I am wrong but, Revanced is just a modded twitter tho that requires you still to login? The benefit with Fritter at least for me is it doesn't require a login at all. I can just pull it up and see a feed without an account.

I think the whole point of the API change was to force users to log in. There's no real way around it, using a mobile app at least. 

My [RSSHub](https://github.com/DIYgod/RSSHub) feed appears to still be working. Currently I have [MonitoRSS](https://github.com/synzen/MonitoRSS-Clone) set up to push twitter updates to discord, that works as a decent feed for me.

**Comment by CarlosEkisde** [comment]
If the twitter feed is the real deal, and user pages are not going to be affected. A solution could be recreating the feed locally instead of fetching it from the twitter serves, just like an actual RSS feed client would do.

**Comment by Sdash24** [comment]
https://twitterisgoinggreat.com/#twitter-announces-shutdown-of-free-api-making-it-less-friendly-to-developers

**Comment by kachapman** [comment]
> > Correct me if I am wrong but, Revanced is just a modded twitter tho that requires you still to login? The benefit with Fritter at least for me is it doesn't require a login at all. I can just pull it up and see a feed without an account.
> 
> I think the whole point of the API change was to force users to log in. There's no real way around it, using a mobile app at least.
> 
> My [RSSHub](https://github.com/DIYgod/RSSHub) instance appears to still be working. Currently I have [MonitoRSS](https://github.com/synzen/MonitoRSS-Clone) set up to push twitter updates to discord, that works as a decent feed for me.

So do you just create RSS feeds individually for each person's account that you follow? I'm trying to get this setup right now.

**Comment by perrob70** [comment]
Following individual accounts is still possible in fritter.

**Comment by M-Reimer** [comment]
It is possible to still view tweets individual per followed account and fritter knows the list of followed accounts. Wouldn't it be possible to get a timeline again by fetching tweets per account and sorting the result by time?

**Comment by Svetov1d** [comment]
As for now my solution is Feeder + Nitter.nl instance for following few accounts

**Comment by kachapman** [comment]
How are you getting individual feeds from a nitter instance?

-------- Original Message --------

**Comment by perrob70** [comment]
My solution is fritter as several bookmarks in a browser and to create  a timeline use multiple user  feeds in the link sepeated by momma example Dutch news feeds
https://nitter.net/@nos,@rtlnieuws,@nieuwsuur,@nunl,@teletekst,@op1npo,@nporadio1,@loop_nl,@trouw

**Comment by jonjomckay** [comment]
Hello all - sorry about this. As noted in the linked Nitter thread (https://github.com/zedeus/nitter/issues/783#issuecomment-1517046884), Twitter has recently blocked access to the API Fritter uses to generate group feeds.

I'll try and push a fix up for it this weekend, but I can't make any promises - I don't have as much free time to work on Fritter as I'd like at the moment. Please be patient, and I'll try to fix this ASAP 🙂

**Comment by Uatschitchun** [comment]
Will you do a release, too?

**Comment by perrob70** [comment]
Would be great, fritter is by far the best in it's kind. So I will wait for the fix,  thanks in advance.

**Comment by kachapman** [comment]
Oh wow, I love that method!

-------- Original Message --------

**Comment by jonjomckay** [comment]
A new beta version has been [released](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta7). It appears to fix the latest round of Twitter API breakages, but please report back in another issue if there are still broken pieces of functionality 🙂

**Comment by geominorai** [comment]
> A new beta version has been [released](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta7). It appears to fix the latest round of Twitter API breakages, but please report back in another issue if there are still broken pieces of functionality 🙂 

None of the feeds load for me in beta7:

<img src="https://user-images.githubusercontent.com/13911156/233854959-f0287da0-26e2-4370-9356-860b0ba25598.png" width=200 />

**Comment by moocow1452** [comment]
I got it to work, had to clean install the app and import the previous
settings. Searching for users is still broken but searching across Tweets
and the main feed is working fine.

**Comment by perrob70** [comment]
Yep the import worked on a fresh install

**Comment by mmkthecoolest** [comment]
Will this be available on F-Droid too? F-Droid is still stuck in beta 5.

**Comment by tadcrazio** [comment]
Good stuff. Fresh install working for the feed. Quote replies do not show up tho.

**Comment by geominorai** [comment]
The feeds seem to work without reinstalling if the filter has either replies or retweets enabled.

**Comment by nannadroid** [comment]
> > A new beta version has been [released](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta7). It appears to fix the latest round of Twitter API breakages, but please report back in another issue if there are still broken pieces of functionality 🙂
> 
> None of the feeds load for me in beta7:
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/13911156/233854959-f0287da0-26e2-4370-9356-860b0ba25598.png">

Are the individual twitter profiles accessible with beta7?

**Comment by geominorai** [comment]
> > > A new beta version has been [released](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta7). It appears to fix the latest round of Twitter API breakages, but please report back in another issue if there are still broken pieces of functionality 🙂
> > 
> > None of the feeds load for me in beta7:
> > 
> > <img alt="" width="200" src="https://user-images.githubusercontent.com/13911156/233854959-f0287da0-26e2-4370-9356-860b0ba25598.png">
> 
> Are the individual twitter profiles accessible with beta7?

Tweets on the profile pages were still accessible before and in beta 7. It is just the main and group feeds that were affected.

**Comment by nannadroid** [comment]
> > > > A new beta version has been [released](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta7). It appears to fix the latest round of Twitter API breakages, but please report back in another issue if there are still broken pieces of functionality 🙂
> > > 
> > > 
> > > None of the feeds load for me in beta7:
> > > <img alt="" width="200" src="https://user-images.githubusercontent.com/13911156/233854959-f0287da0-26e2-4370-9356-860b0ba25598.png">
> > 
> > 
> > Are the individual twitter profiles accessible with beta7?
> 
> Tweets on the profile pages were still accessible before and in beta 7. It was just the main and group feeds that were affected.

Thank you!

**Comment by igorskyflyer** [comment]
> Does not work for me. In "Feed", I just get an error message "type 'Null' is not a subtype of type 'String' in type cast".

Indeed, for me too, only individual profiles work. I tried installing from scratch and importing old settings, didn't work.

**Comment by tadcrazio** [comment]
> Does not work for me. In "Feed", I just get an error message "type 'Null' is not a subtype of type 'String' in type cast".
> 
> Edit: After completely deleting all data of the app and reimporting my setting, I can reload the feed twice. Then I'm back to the same "type cast" error.

I get this constantly as well. Playing with filters sometimes brings the feed up. Otherwise, i uninstall, reinstall, and it works again for a bit. Really not ideal, but at least on the reinstall I don't need to re-import everything.
I'm happy to have the feed for sure, but there are certainly more bugs than before.

**Comment by error401de** [comment]
Net beta still does not work for me. Feed is showing "FormatException: Unexpected end of input (at character 1)" after importing backup of prior version.
Does anybody know an alternative app?

**Comment by kachapman** [comment]
> My solution is Nitter as several bookmarks in a browser and to create a timeline use multiple user feeds in the link sepeated by comma example Dutch news feeds https://nitter.net/@nos,@rtlnieuws,@nieuwsuur,@nunl,@teletekst,@op1npo,@nporadio1,@loop_nl,@trouw

This method suddenly stopped working. I was really enjoying it. Is it working for you?

**Comment by perrob70** [comment]
No also for me it stopped. Yesterday nitter.net was not active for a short while and when it became active,  this function was not possible.  I also put nitter now in a RSS reader.  I use nunti,  wich for me is my favorite.  Although the feed can refresh to minimal an hour, the look and feel is good an all can be browsed in the app if you turn this on. For now i wait for a fritter fix,  but probably takes some time and because I really like fritter I will wait patiently and check the git every now and then.
