### ISSUE TITLE
[BUG] Video player not responding on posts 

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#666]
**Describe the bug**

Videos for posts play on the media tab of a profile but do not after opening the post. The video player interface does not seem to respond to taps. This issue was not present until the first beta7 build. 

**To Reproduce**

1. Go to https://twitter.com/discord/status/1649469438691778562
2. Click on video player
3. See error

**Device**

Model: Samsung Galaxy S9+
OS: Android 10
Language: English
Fritter Version: v3.0.0-beta7+300000957

**Comment by moocow1452** [comment]
Happens to me in that videos work in any tab of the profile, but the player doesn't under individual tweets.

**Comment by geominorai** [comment]
This also seems to affect replies with video.
