### ISSUE TITLE
[BUG] Unable to search for users

### ISSUE THREAD

**Issue by moocow1452** [jonjomckay/fritter#669]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
I am unable to search for users within Fritter.

**To Reproduce**
1. Go to the Search Icon in the upper right corner of the main screen.
2. Input a User
3. Failure

**Screenshots**
![Screenshot_20230423-170043.png](https://user-images.githubusercontent.com/1383448/233866153-fea10b82-d5ec-4226-b72b-a7748f0ef452.png)

**Device**

![Screenshot_20230423-143818~2.png](https://user-images.githubusercontent.com/1383448/233866177-8a31b8d5-d4b8-4807-8f69-019f085bfb4c.png)

**Comment by JVT038** [comment]
I have the same issue

**Comment by rickdtc** [comment]
Having the same issue rn
![Screenshot_20230424_185959_Fritter](https://user-images.githubusercontent.com/74096544/234015161-bedb73b4-c8e9-4fcd-8573-b5af1c3c9201.jpg)

**Comment by jh3rn4n** [comment]
Hi i have the same isue
![IMG_20230425_072541](https://user-images.githubusercontent.com/26331827/234262462-4a3ee3bd-3fe0-4d64-8f8a-37b5ac760ddb.jpg)

**Comment by jh3rn4n** [comment]
> Hi i have the same isue ![IMG_20230425_072541](https://user-images.githubusercontent.com/26331827/234262462-4a3ee3bd-3fe0-4d64-8f8a-37b5ac760ddb.jpg)

and the last estable relese 2.16.4 and the beta 5 3.0.0, beta 6 3.0.0 have the same behavior

**Comment by jonjomckay** [comment]
This should now be fixed, thanks to #679
