### ISSUE TITLE
[BUG] Annoying pop up 

### ISSUE THREAD

**Issue by s0mt0chukwu** [jonjomckay/fritter#670]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
Each time I try to use fritter, lt lags then show annoying pop up which reads " An error was reported to Sentry. thank you.

**Device**
Samsung A30
Android 9
English
Fritter version 3.0.0-beta4

**Comment by TheHCJ** [comment]
That's normal, if you want to disable it go into settings and turn off `Enable Sentry`

**Comment by jonjomckay** [comment]
Closing, as there's an option in the settings to disable that functionality
