### ISSUE TITLE
[BUG] Settings like "Include Replies" not saved in 3.0.0-5 backup

### ISSUE THREAD

**Issue by Mrnofish** [jonjomckay/fritter#674]
**Describe the bug**
The 3.0.0-5 backup seemingly does not contain any information on the state of the "Include Replies" checkmark on the main feed. The same appears to be true for the "Include Retweets" option.

**To Reproduce**
1. Export all data
2. Reinstall Fritter
3. Import backup file
4. Visit Feed, replies are included even though the option was disabled previously.

**Device**
Fritter version:
- Import: 3.0.0-7
- Export: 3.0.0-5

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
