### ISSUE TITLE
[BUG] Unable to see feed or search for a user 

### ISSUE THREAD

**Issue by Arthurvip** [jonjomckay/fritter#677]
@jonjomckay 
![Screenshot_20230426-001606_Fritter](https://user-images.githubusercontent.com/131853601/234500152-9156b057-64cf-4bf4-9b89-48753926daff.png)

**Comment by TheHCJ** [comment]
Duplicate #668

**Comment by jonjomckay** [comment]
Closing as a duplicate of #668
