### ISSUE TITLE
[BUG] Quoted tweet not shown in feed, only in tweet detail

### ISSUE THREAD

**Issue by Mrnofish** [jonjomckay/fritter#678]
**Describe the bug**
When a followed user uses the Quote Tweet to retweet, only their comment is shown in feed, the quoted tweet is not displayed, however it appears after tapping the tweet 

**To Reproduce**
1. Follow account that has quote tweets
2. View feed
3. Tap on quoted RT

**Screenshots**

Feed view

![Screenshot_20230426-162345_Fritter](https://user-images.githubusercontent.com/28036193/234607866-f1a78434-f655-4bdf-b7a5-76da68e3f3e3.png)

Tweet view

![Screenshot_20230426-162407_Fritter](https://user-images.githubusercontent.com/28036193/234607966-36613947-94da-4e99-b78a-b152ddaf96f3.png)

**Device**
Fritter Beta 3.0.0-7

**Comment by jonjomckay** [comment]
Closing as the feed has now been removed, due to Twitter blocking access permanently. Please see https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190
