### ISSUE TITLE
Stop creating same issues. Just once is fine and if it is already there, give your reaction in that existing issue.

### ISSUE THREAD

**Issue by worstflimsy** [jonjomckay/fritter#681]
I use Fennec in android and have created my own custom add-on collection and I use Libredirect. It redirects Twitter to nitter. I've also set several bookmarks using twitter.com as web address. That way the links are not stuck on a single nitter instance as Libredirect automatically switches instances to avoid overload of one. For select few accounts I've subscribed them in Fritter to get feed view. Since these Twitter nonsense changes have begin, feed doesn't work. But no issue because I can still view individual accounts. Atleast I'm not dependent on feed view and not opening Fritter for the sake of it, saving valuable time. A positive outcome for me - thanks Twitter.

Wrote this comment to tell folks - there are good options available. Just don't create new same repeated issues to tire developer out. You don't explore solutions and yet expect dev to fix everything when it is a steep uphill battle. Rant over.

**Comment by jonjomckay** [comment]
Thanks for the support. I've added a note to the bug issue template which encourages people to search for existing issue first, as obvious as it may seem 🙂
