### ISSUE TITLE
[BUG] The app always says catastrophic failure, forbidden

### ISSUE THREAD

**Issue by aojedao** [jonjomckay/fritter#689]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
A clear description of what the bug is.

In the latest update the app stopped working, the front page always reports catastrophic error, I try to see an account from the search bar and the same error appears 

**To Reproduce**
3. See error

I just open the app and it says catastrophic error. 

**Screenshots**

**Device**
Your device model, OS version, device locale/language and Fritter version. Please supply the actual
version of Fritter being used, and **do not** just write "latest version" or similar, as this
changes constantly.

Motorola One Vision, Fritter version 2.16.4

**Comment by Ductt2** [comment]
Exactly the same here. 

Samsung Galaxy Note  8 (SM-N950F), Android 9 locale/language german, Fritter v.2.16.4+20221209
