### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DrFriend1** [jonjomckay/fritter#695]
Can't access to Feed

**Comment by TheHCJ** [comment]
Twitter have re-enabled this API endpoint, download the APK at the top of #668 to get your feeds back!

**Comment by TheHCJ** [comment]
This is not a bug, feeds have been removed #668

**Comment by TheHCJ** [comment]
I have just made a pull request to fix this https://github.com/jonjomckay/fritter/pull/698

**Comment by jonjomckay** [comment]
The feed has been removed. Please see #668.
