### ISSUE TITLE
[BUG] no Feed menu on the Fritter v3.0.0-beta8

### ISSUE THREAD

**Issue by fikrighifari** [jonjomckay/fritter#696]
> Please search for similar issues first, and also make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
there is no Feed menu on the latest apps

**To Reproduce**
1. Install
2. Import 
3. no feed menu

**Screenshots**
![Screenshot_2023-05-02-10-45-24-040_com jonjomckay fritter](https://user-images.githubusercontent.com/53219217/235575153-3617a5d7-3ba3-4172-90c7-6d525fa24e72.jpg)

**Device**
Xiaomi Redmi Note 7, Android 9, English and Fritter [v3.0.0-beta8]

**Comment by j-fbriere** [comment]
Not a bug.
The feed menu has been removed.
See #668.

**Comment by fikrighifari** [comment]
ah I see, thanks for your info.
hope Twitter will open its API again soon 😌

**Comment by TheHCJ** [comment]
Twitter have renabled this API endpoint, download the APK at the top of #668 to get your feeds back!

**Comment by TheHCJ** [comment]
I have just made a pull request to fix this https://github.com/jonjomckay/fritter/pull/698

**Comment by Anilya-e** [comment]
this comment dont seem safe at all, it is clean ?

**Comment by TheHCJ** [comment]
Source code is available at Https://github.com/TheHCJ/fritter if you want
to check it

**Comment by Anilya-e** [comment]
thank you ^^

**Comment by TheHCJ** [comment]
No problem 😃

**Comment by jonjomckay** [comment]
The feed has been removed in Fritter. Please see #668.
