### ISSUE TITLE
App Doesn't Show the Tweet That was Replied To

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#70]
**Steps to Reproduce**:

1. Find a reply that appears in your feed.
2. Tap on it.
3. You'll see the tweet (the reply) you opened but not the tweet that was replied to, thus causing a loss of context.

**Screenshots**:

Here's a reply that showed up in my Group feed:

![Ex 1](https://user-images.githubusercontent.com/83120103/117694606-f5d17b00-b1dc-11eb-883a-b50089127df7.png)

**After I tapped on it**:

![Ex 2](https://user-images.githubusercontent.com/83120103/117694736-1b5e8480-b1dd-11eb-806f-3daf8838e3b8.png)

**App Version**: 2.3.0

**Comment by RequestPrivacey** [comment]
The missing link between the tweet/thread and the reply is indeed the feature I'm missing the most. I kind of like the style of twitter:

tweet 1
|
tweet 2
|
tweet 3
|
Reply I clicked on
|
All other replies to the original tweet/thread

Second post for me on github, sorry if I disregard some kind of etiquette. And nice work on Fritter, I love it, thanks!

**Comment by rituraj22** [comment]
Even a link to the parent tweet without explicitly loading it would be enough. Currently tapping on the replying to button takes to the profile page

**Comment by selurvedu** [comment]
Yes, simply being able to view the parent tweet – the same way you can view replies now – would be sufficient.

**Comment by jonjomckay** [comment]
Sorry for the long wait on this one - it should be implemented and will go out in v2.11.0!
