### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Twig6943** [jonjomckay/fritter#705]
A timeline where the latest tweets of the people you follow are shown I mean it should be possible.

**Comment by akawama** [comment]
Now that Twitter has closed its API for feed, web scraping perhaps?

**Comment by ctntt** [comment]
You (@Twig6943) accidentally opened the same issue twice. This is a duplicate of https://github.com/jonjomckay/fritter/issues/704.

**Comment by jonjomckay** [comment]
This was the feed, which has recently been removed due to constant breakage on Twitter's end, and because I don't want to continue the problems that maintaining and using it cause: https://github.com/jonjomckay/fritter/issues/668#issuecomment-1538230835

**Comment by Twig6943** [comment]
I mean isn't it possible without the twitter api? Cant you make the app itself get the latest tweets of the people you folow.

**Comment by ctntt** [comment]
It is possible but jonjomckay already explained in detail why it won't be implemented in fritter https://github.com/jonjomckay/fritter/discussions/699.
Also there is already a fork which includes this feature https://github.com/TheHCJ/Quacker.

**Comment by Twig6943** [comment]
@ctntt Thank you so much for the recommendation have a nice day.
