### ISSUE TITLE
[BUG] Long tweet of blue tick have text mixed with URL

### ISSUE THREAD

**Issue by j-fbriere** [jonjomckay/fritter#711]
**Describe the bug**
Since the fix of the bug #709, long tweet from blue tick user have text which is mixed with its URL

**To Reproduce**
1. Go to [https://twitter.com/YusufCatStevens/status/1655892996544421889](https://twitter.com/YusufCatStevens/status/1655892996544421889)
2. See error

**Screenshots**

Fritter:

![Screenshot_20230512-155915_Fritter_small](https://github.com/jonjomckay/fritter/assets/49044668/82ef7103-cc8f-4c85-88ad-8e1737b09a01)

Browser:

![Screenshot_20230512-155959_Chrome_small](https://github.com/jonjomckay/fritter/assets/49044668/9f175952-2f0b-4381-8d10-e706359ec463)

**Device**
Model: Samsung Galaxy S20FE
OS: Android 10
Language: English
Fritter Version: v3.0.0-beta9+300001014 with the commit 63675c9989cfe8d6cf8ddde18e4f58b86758db01

**Comment by geominorai** [comment]
I also noticed similarly that these long tweets in the profile feed cut off prematurely and end with that same partial URL text instead.
