### ISSUE TITLE
Can't look up anything

### ISSUE THREAD

**Issue by HiddenLeveI** [jonjomckay/fritter#723]
Every time I try to look up something I get "Catastrophic Error Forbidden." 

I'm using GrapheneOS now so maybe that could be affecting it. Other than that, idk.

**Comment by TheHCJ** [comment]
Can your provide a screenshot and version?

**Comment by HiddenLeveI** [comment]
> Can your provide a screenshot and version?

So I downloaded the beta version off of github and now its fine. The version I downloaded from F-Droid was messed up. 

Here are some pics tho.

![Screenshot_20230514-114659.png](https://github.com/jonjomckay/fritter/assets/110350004/76bceffc-d9aa-47fc-bdbe-9ad3cc26758e)

![Screenshot_20230514-114651.png](https://github.com/jonjomckay/fritter/assets/110350004/c444e2e2-1527-46ad-aff1-62bd6bab752a)

**Comment by DHermansson** [comment]
I have the same "Catastrophic Error Forbidden."
For Feeds and if I search
I can read the subscriptions I already have.
v2.16.4+20221209 from Google Play
Android 12, Xperia XQ-AT51
Started som weeks ago. Before that it worked fine.

**Comment by TheHCJ** [comment]
Join the beta program on the play store as any version prior to beta8 are
bugged! 🐛

**Comment by DHermansson** [comment]
Only 3.0.0-beta6 is offered in the beta program and thats a very old one.

**Comment by TheHCJ** [comment]
Try downloading from f-droid or GitHub releases

**Comment by DHermansson** [comment]
Download from F-droid won't  install even if I allow it from that source.
From GitHub.... I'm lost. Don't know where or how.

**Comment by TheHCJ** [comment]
Don't worry about it, lots of people don't even know how to make an issue!
Just go to https://github.com/jonjomckay/fritter

**Comment by DHermansson** [comment]
Been there but it just looks like regular release notes, looking for "download" or any .apk

**Comment by TheHCJ** [comment]
> Been there but it just looks like regular release notes, looking for "download" or any .apk

Check the assets under the release notes. You can download beta9 [here](https://github.com/jonjomckay/fritter/releases/download/v3.0.0-beta9/fritter-v3.0.0-beta9.apk)

**Comment by DHermansson** [comment]
Getting closer, that packet won't install due to a conflict with an existing packet.
No hint about what packet it's in n conflict with.

**Comment by TheHCJ** [comment]
Uninstall fritter then install the update

**Comment by DHermansson** [comment]
Thanks, that worked 
An as a reminder to anyone with the same problem. Make notes or screenshot of the subscriptions before uninstall since they will be lost.

Kudos to TheHJC

**Comment by HiddenLeveI** [comment]
Or you (if you know your old twitter account) can look it up and follow everyone you had on that.

**Comment by DHermansson** [comment]
If I had an account...
