### ISSUE TITLE
Tab "Feeds" is missing

### ISSUE THREAD

**Issue by muet0** [jonjomckay/fritter#730]
The Tab Feeds is missing in the menu

![IMG_20230515_111138](https://github.com/jonjomckay/fritter/assets/133501013/54a738c6-fddc-49bc-b953-5deb68328967)

Also a change of the language didn't change a thing. The tabs is missing. 

I'm using version 3 beta 9.

**Comment by ctntt** [comment]
Here is the detailed explanation https://github.com/jonjomckay/fritter/discussions/699 for the removal.
If you really need the feed there's also a fork of fritter with that feature https://github.com/TheHCJ/Quacker.

**Comment by TheHCJ** [comment]
> Here is the detailed explanation #699 for the removal. If you really need the feed there's also a fork of fritter with that feature https://github.com/TheHCJ/Quacker.

Thanks for the metion! I am also expanding to [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.thehcj.quacker)

**Comment by TheHCJ** [comment]
Jonjomckay doesn't want feeds to be part of fritter. I am happy to work
with them on reintegration if they change their mind 😃

**Comment by geominorai** [comment]
Part of the confusion may be due to the app screenshots not yet being updated to remove the feed tab.

**Comment by muet0** [comment]
It can be closed here, although I don't understand the decision of removing the feeds. Everybody is responsible for himself how to use Social Media.
