### ISSUE TITLE
[BUG] Long tweets by Twitter Blue users  not shown completely

### ISSUE THREAD

**Issue by AndiDink00x** [jonjomckay/fritter#746]
This issue still exist https://github.com/jonjomckay/fritter/issues/644#issue-1599813900 with the latest version of Fritter (3.0-Beta 9). Definitely my main and only issue with this app

**Comment by j-fbriere** [comment]
I tried the [long tweet](https://twitter.com/MishaalRahman/status/1629319713107894274) from https://github.com/jonjomckay/fritter/issues/644#issue-1599813900 with the latest [ci build](https://github.com/jonjomckay/fritter/actions/runs/5072831866) of Fritter and there is no problem.

**Comment by AndiDink00x** [comment]
@j-fbriere downloaded lated ci build of Fritter doesnt seem to be fixed can you provide a pic ?

**Comment by j-fbriere** [comment]
When I click [long tweet](https://twitter.com/MishaalRahman/status/1629319713107894274) it opens the latest [ci build](https://github.com/jonjomckay/fritter/actions/runs/5072831866) of Fritter and it shows:

![Screenshot_20230608-135622_Fritter_small](https://github.com/jonjomckay/fritter/assets/49044668/236d6625-c98e-4a8f-9bdd-3e9e1eaa3822)
