### ISSUE TITLE
[BUG] Cannot use app at all. (404)

### ISSUE THREAD

**Issue by McBaumwolle** [jonjomckay/fritter#768]
**Describe the bug**
I can not search for accounts (screenshot 1) or open links (screenshot 2) with the app, I tried the current F-Droid and GitHub releases (including beta). I tried it on Wi-Fi and mobile data, a VPN also did not change anything. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install version
2. Set app to open links from Twitter
3. Click on a link
4. (search for something)

**Screenshots**
![Screenshot_20230813-135315](https://github.com/jonjomckay/fritter/assets/67203883/e8ad2a81-3b85-4afb-b92d-9760fc4b124b)
![Screenshot_20230813-135332](https://github.com/jonjomckay/fritter/assets/67203883/2951809f-0820-48e2-a719-123d39078832)

**Device**
Google Pixel 5 (English)
Android 13 (TQ3A.230805.001)
Fritter v3.0.0-beta9+300003014

**Comment by TheHCJ** [comment]
Nitter is also down for the same reason

**Comment by McBaumwolle** [comment]
Oh then it's probably an API issue.

**Comment by IL2C** [comment]
https://github.com/zedeus/nitter/issues/983#issuecomment-1684506703

**Comment by Wack0** [comment]
nitter will fix by using "guest tokens", which are limited in some way (most notably a custom rate limit) but otherwise would seem to work: https://github.com/zedeus/nitter/issues/983#issuecomment-1681199357

**Comment by McBaumwolle** [comment]
Thanks, this looks promising!

**Comment by david-vodus** [comment]
If you want and don't mind using twitter account, you can use my commit with twitter account  login and browsing.
[https://github.com/jonjomckay/fritter/issues/756#issuecomment-1682098931](url)

**Comment by david-vodus** [comment]
If you want and don't mind using twitter account, you can use my commit using a twitter account for browsing tweets.
#769

**Comment by McBaumwolle** [comment]
Thank you, but I am relatively new to Git. Could you elaborate on how I can download the .apk with the modified files? I see it has not been merged yet.

**Comment by david-vodus** [comment]
> Thank you, but I am relatively new to Git. Could you elaborate on how I can download the .apk with the modified files? I see it has not been merged yet.

Apk is there [https://github.com/david-vodus/fritter/blob/master/Apk/app-release.apk](url)

**Comment by comomberchese** [comment]
What about adding to the proxy settings?

**Comment by grisu68** [comment]
> > Thank you, but I am relatively new to Git. Could you elaborate on how I can download the .apk with the modified files? I see it has not been merged yet.
> 
> Apk is there https://github.com/david-vodus/fritter/blob/master/Apk/app-release.apk

Unfortunately the link is not working. Error 404

**Comment by Thing221** [comment]
I have the same problem.

**Comment by McBaumwolle** [comment]
Closing this as [Squawker](https://github.com/j-fbriere/squawker) works fine.
