### ISSUE TITLE
No profile is loading

### ISSUE THREAD

**Issue by Hx2-code** [jonjomckay/fritter#77]
Whenever I try to load any profile this error shows up.

**Something went wrong loading the
profile! The error was: Instance of
'Response'**

![Screenshot_20210512-121800_Fritter.png](https://user-images.githubusercontent.com/76239380/117930940-3683de00-b31c-11eb-8c6b-d47c0f551d9b.png)

**Comment by jonjomckay** [comment]
I'm getting this too - the actual error from Twitter is a 403 saying "Your credentials do not have access to this resource". It appears Nitter instances are getting the same error from Twitter (https://github.com/zedeus/nitter/issues/383) so my guess would be Twitter has blocked the method we use 😢

I have an idea that might get around it though...

**Comment by Hx2-code** [comment]
If twitter really did something, nitter might end up like bibliogram. RIP privacy. 😭

**Comment by jonjomckay** [comment]
OK, I was able to fix this by switching to a new endpoint. I've released v2.3.2 which contains the fix - it should be available on in GitHub releases in a few minutes, and on F-Droid in a few days (🙃)

**Comment by Hx2-code** [comment]
Thanks for all you effort.

**Comment by alphanerdgen** [comment]
> and on F-Droid in a few days

You're an optimist. 😄
