### ISSUE TITLE
@jonjomckay is fritter abandoned?

### ISSUE THREAD

**Issue by TheHCJ** [jonjomckay/fritter#774]
### Discussed in https://github.com/jonjomckay/fritter/discussions/773

<div type='discussions-op-text'>

<sup>Originally posted by **mrhcjones** November 25, 2023</sup>
@jonjomckay</div>

**Comment by darlopvil** [comment]
asking the same. App doesn't load very well the feed. It's full of 404's

**Comment by mrhcjones** [comment]
> asking the same. App doesn't load very well the feed. It's full of 404's
You should use [Squawker](https://github.com/j-fbriere/squawker) until we get an answer

**Comment by TheHCJ** [comment]
<img width="705" alt="Screenshot 2024-06-25 at 20 35 54" src="https://github.com/jonjomckay/fritter/assets/150591975/50d2115c-e003-4c2f-baed-950df8c0eabd">

**Comment by Teskann** [comment]
@TheHCJ is squawker the reason why you archived the quacker repository? In my opinion your fork works much better than squawker.

**Comment by TheHCJ** [comment]
> @TheHCJ is squawker the reason why you archived the quacker repository? In my opinion your fork works much better than squawker.

I stopped working on Quacker because I didn't want to continue the cat and mouse game with elon
