### ISSUE TITLE
Country and state wise Twitter trending

### ISSUE THREAD

**Issue by Github-com-foss** [jonjomckay/fritter#87]
Set manually twitter treading country and state wise
![Screenshot_20210514-203712702_1](https://user-images.githubusercontent.com/75672019/118290738-6554ac80-b4f4-11eb-87ef-64333fbb3705.jpg)

**Comment by WindHun7er** [comment]
Duplicate of #21

**Comment by jonjomckay** [comment]
Closing as a duplicate of #21. Feel free to leave a comment on there with any thoughts!
