### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by wilayahapps** [jonjomckay/fritter#89]
Please give us option to take backing up and restoring the Twitter  handles we are following.

**Comment by WindHun7er** [comment]
Import/export feature is already implemented since v2.3.0. It's accessible in the app settings.

You can download the latest version of the app in the github's releases page and close this issue if this is what you were looking for. 🙂

**Comment by login22rvp** [comment]
I tired import and export today. It didn't work.
Tried on V2.5 ans V2.4

**Comment by WindHun7er** [comment]
Curious... It works perfectly smoothly on my side though... 
Maybe you can open a new issue (it was not the subject of this one), indicate your device, app version and software version and specify what precisely is not working.
It will probably be more convenient for @jonjomckay to investigate...

**Comment by jonjomckay** [comment]
@login22rvp can you give any more details as to how import/export didn't work for you? If you're able to supply any output from Logcat, that would be helpful too!

**Comment by wilayahapps** [comment]
> Import/export feature is already implemented since v2.3.0. It's accessible in the app settings.
> 
> You can download the latest version of the app in the github's releases page and close this issue if this is what you were looking for. 🙂

I had downloaded from FDroid but still not seeing anything.

**Comment by WindHun7er** [comment]
![Screenshot_20210526-190533_Fritter](https://user-images.githubusercontent.com/80457123/119703309-b484d080-be56-11eb-9543-b149d0543a3f.jpg)

But maybe you were talking about something else... The direct import/export of subscriptions from a twitter account to the fritter application is indeed not possible for the moment.

**Comment by jonjomckay** [comment]
Closing as import/export has already been imlemented. If this is talking about importing from a real Twitter account, that is now being tracked in #143!
