### ISSUE TITLE
[Question] What information does Twitter get when I use this app?

### ISSUE THREAD

**Issue by eredrolo** [jonjomckay/fritter#93]
I guess they would get my IP address. What else do they get?

Thanks for the app. It's great!

**Comment by login22rvp** [comment]
Yes. I am also curious.

**Comment by jonjomckay** [comment]
I'm looking into adding some details on this to the website ([fritter.cc](https://fritter.cc)), but it pretty much boils down to:

* Your IP address
* A non-identifying user agent (`dart (2.x)`)
* Any queries you might perform (e.g. searches, profile views, tweet views)

The method (API) Fritter uses is the same that the public Twitter Web interface uses (and Nitter), minus all of their client-side tracking scripts. It's not 100% anonymous, but Twitter should have no way to identify a user besides their IP address. Accessing through a proxy should solve that, although you're more likely to run into rate limit errors that way (shared IP, etc.)

**Comment by eredrolo** [comment]
Thanks for the answer. Looks like a good balance between convenience and privacy.
