### ISSUE TITLE
Request : improve The video player

### ISSUE THREAD

**Issue by TheOnlyIsmail** [jonjomckay/fritter#98]
again, Thank You for the amazing work you That you are doing for this app.

The video player is very basic, you cannot know the Duration of the video or control the video watching

**Comment by jonjomckay** [comment]
Good news - I'll be making the video player a bit more usable in the next release (v2.6.0) 😄

**Comment by TheOnlyIsmail** [comment]
> Good news - I'll be making the video player a bit more usable in the next release (v2.6.0) 😄 

Amazing 😃

**Comment by jonjomckay** [comment]
Fixed in the upcoming v2.6.0 (#103). Closing this issue as the PR didn't close it for some reason 😅
