### ISSUE TITLE
New and your own UI

### ISSUE THREAD

**Issue by ansarimohammed422** [jonjomckay/fritter#99]
Can you discard newpipes UI/UX and impliment yours own UI/UX 
Which will be more intuitive 
Newpipes ui is also great but making your own will be more creative

THANKS IN ADVANCE

**Comment by jonjomckay** [comment]
Thanks for your feedback - is there something specifically in the UI, or some bad UX that you can point to? I'm happy to gather some feedback and improve any painful areas, if possible :)

**Comment by alphanerdgen** [comment]
My suggestion 😅: #29

**Comment by jonjomckay** [comment]
Closing, as nothing specific was detailed. Please open a new issue if you have more feedback on UX improvements!
